### PR TITLE
GTK3: Fix caja information panel 

### PR DESCRIPTION
**Pull request by lukefromdc**
The Caja information panel (information option in sidebar) was never fully ported to GTK3, probably still isn't. Set the .view style class on it, and exclude the rest of caja_information_panel_update_appearance as that code segfaults (at least with GTK 3.21) on dragging a background to the info panel.

We now have a demo for background dragging in GTK3: A background can be dragged to the information sidebar and will be displayed. Won't be saved and won't appear in other Cajs navigation windows, something in the code that segfaulted no doubt needs to be fixed for that but that's for later. At least this widget finally works. It will follow any theme I have and no longer fails to update to  BlackMATE or my own theme.

### CODE REVIEW

**Comment by raveit65** [comment]
Well, should be save to merge to master?

**Comment by lukefromdc** [comment]
Should be, though I would have to revert mate-desktop to test. Cherrypick
that one changed file, it should work fine. Test master with mate-desktop
from master as well, though I don't know how much longer the GdkColor
code will be used.

**Comment by raveit65** [comment]
At the moment i'm a bit clueless what is wrong with GdkRGBA port, i hope that some of the other guys will help.
But at least this have to be done before we switch to gtk3.

**Comment by lukefromdc** [comment]
With this last commit I just sent the only thing that is broken as a result of 
the GdkRBGA issue is the gradient backgrounds and the m-c-c icon for 
a color background.  Solid color backgrounds were broken for ages in GTK3,
they now work. I submitted an issue that nobody else ever commented on, 
closed it since that is now fixed-and worked when I first started playing with 
eel-background.

**Comment by lukefromdc** [comment]
For the gradient background, it looks like  eel_gradient_new in gdk_extensions.c 
may be the culprit, since it's the only real difference from the single color background in 
the function eel_bg_get_desktop_color in eel_background.c

**Comment by lukefromdc** [comment]
Just took a look at eel_gradient_new, the color variables there are const char variables, while in eel_bg_get_desktop_color they are GdkRGBA 's.

**Comment by lukefromdc** [comment]
Now playing with the code below:

#if GTK_CHECK_VERSION (3, 0, 0)
    start_color = eel_gdk_rgb_to_color_spec (eel_gdk_rgba_to_rgb (&primary));

    if (use_gradient)
    {
        end_color  = eel_gdk_rgb_to_color_spec (eel_gdk_rgba_to_rgb (&secondary));
#else
    start_color = eel_gdk_rgb_to_color_spec (eel_gdk_color_to_rgb (&primary));

    if (use_gradient)
    {
        end_color  = eel_gdk_rgb_to_color_spec (eel_gdk_color_to_rgb (&secondary));
#endif
        color_spec = eel_gradient_new (start_color, end_color, is_horizontal);
        g_free (end_color);
    }
    else
    {
        color_spec = g_strdup (start_color);
    }
    g_free (start_color);

    return color_spec;``

The start_color and end_color variables both work, as simply setting color_spec = g_strdup to either color works properly. It's when `color_spec = eel_gradient_new ()` is called that a black background results, thus confirming that eel-gdk-extensions.c needs work on the gradient code

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/caja/commit/262492b5ef82faf66b3b6b78aea7d304a52cf2e0
Thank you

**Comment by raveit65** [comment]
Nice analysis, i will look in gdk_extensions.c again.

**Comment by lukefromdc** [comment]
More on the GkdRBGA issue for gradients: the returned "color_spec" value is returned by 
`eel_bg_get_desktop_color` to` set_image_properties` with this code:
static void
set_image_properties (EelBackground *self)
{
#if GTK_CHECK_VERSION (3, 0, 0)
    GdkRGBA c;
#else
    GdkColor c;
#endif

    if (self->details->is_desktop && !self->details->color)
        self->details->color = eel_bg_get_desktop_color (self);``

As you can see from the last line, that "color_spec" returned value must be a valid color in self->details->color to work. Maybe that simply cannot work with a gradient? Images and solid colors are fine.

**Pull request closed without merging**
