### PR TITLE
[notebooks]  Add scroll tabs with mouse wheel

### PR DESCRIPTION
**Pull request by tamplan**
Add scroll tabs with mouse wheel for file's properties and caja's preferences windows.

I plan to work on pane's notebook once this PR merges, i have seen gsettings key 'ctrl-tab-switch-tabs' without GUI that should be add in 'caja-file-management-properties.c'.

Regards

### CODE REVIEW

**Comment by sc0w** [comment]
We have here the same function twice, with duplicate maintenance.

I think it can be done one time into one caja library and called with include.

**Comment by tamplan** [comment]
Ok, let's go this way, i will change my code tomorrow...

**Comment by tamplan** [comment]
Done, did you want i squash my commits?

Regards

**Comment by tamplan** [comment]
I see than the build process failed because of marshaller generation but i don't know what file i must change...

If i understand [this page](https://developer.gnome.org/gobject/stable/glib-genmarshal.html), this is because the function 'dialog_page_scroll_event_cb' must be declared **extern**?

Can some one can confirm that point please?

**Comment by sc0w** [comment]
I can't see the function you have done with previous changes, I think you can put that function in an already existing library, for example, into `eel-gtk-extensions.c` maybe?

**Comment by tamplan** [comment]
Quickly summarized, i change 'libcaja-private/Makefile.am' to add 'caja-dialog-notebook.c' that contents the function 'dialog_page_scroll_event_cb' (callback that manage scroll events for notebooks) hoping this function could be called by 'caja-file-management-properties' and caja for file's properties page.

I change **static gboolean dialog_...** to **gboolean dialog_...** but i must, if i understand well, to declare if **extern gboolean dialog_...**.

I purpose to 'caja-dialog-notebook.c' alone file to not pollute another file.

I need to study more the caja's source code and C in general.

Thanks for your suggestion.

Regards

**Comment by sc0w** [comment]
We have all the time needed :)

> Quickly summarized, i change 'libcaja-private/Makefile.am' to add 'caja-dialog-notebook.c' that contents the function 'dialog_page_scroll_event_cb' 

where is the file `caja-dialog-notebook.c` ?

**Comment by tamplan** [comment]
Just used 'commit -a -m ...' but forgot to add tracking for 'caja-dialog-notebook.h' and 'caja-dialog-notebook.c' :-(

**Comment by sc0w** [comment]
@mate-desktop/core-team do you agree to add new file with one unique function?

I think it can be added to `eel-gtk-extensions.c` for example

**Pull request closed without merging**
