### PR TITLE
Fix GTK2 builds

### PR DESCRIPTION
**Pull request by lukefromdc**
based on https://github.com/emanuele-f/caja/commit/4b36a91af42d8efe0f594a95d28ab8448fd73b31

but including 

https://github.com/mate-desktop/caja/pull/660
and https://github.com/emanuele-f/caja/pull/1

### CODE REVIEW

**Comment by lukefromdc** [comment]
emanuale-f reports this builds and runs fine on GT2, my tests show good builds with GTK 3 both with and without libunique so merging

**Comment by raveit65** [comment]
good,
btw. here is an example how to merge w/o merge commit ;)
```
etc.

git checkout -b pudh4418-fix-200 master
git pull git://github.com/pudh4418/mate-control-center.git fix-200
git rebase master
git checkout master
git merge --ff-only pudh4418-fix-200
git push
```
The right links you'll find in PR under 'command line instructions' near merge button.

**Comment by monsta** [comment]
Confirmed, master branch now builds fine with GTK+2. Thank you @lukefromdc and @emanuele-f :smile:

**Comment by lukefromdc** [comment]
I saved these instructions as a text file where I keep my git documentation
for future use.

**Pull request merged**
