### PR TITLE
Fix for #719 (tasklist icon change when opening new tab)

### PR DESCRIPTION
**Pull request by bl0ckeduser**
this should be pretty straightforward.

### CODE REVIEW

**Comment by raveit65** [comment]
Before anyone merge it...
Please edit commit header.
'Fix for a bug no.' doesn't belongs in commit header.
This belongs in commit body.
The header should only contain a short description what the commit does. 
Thanks

**Comment by bl0ckeduser** [comment]
My apologies, I have recently worked on another FOSS project which has
a different conventions for commit names. I will try to ammend and
re-push soon.

**Comment by raveit65** [comment]
Thanks,
you can use 'git rebase -i lask-good-commit' to reword commit.
i = interactive 
Than choose 'reword' in interactive vi shell.
And do a push -f in you local repo, the Pr will be sync automatic with your repo.
It's pretty easy.

**Comment by raveit65** [comment]
Thanks for editing, you did it already :-)

**Comment by raveit65** [comment]
weird, i can't reproduce it here with mate-1.19 on fedora 26.
If i do a right click on picture folder and choose open in new tab, panel task-list shows me my home folder. Or do i miss something?
Any way i see no regeressions.

**Comment by monsta** [comment]
The issue is that it shows the **icon** from the folder you opened in a new tab. The folder name is correct.

**Pull request merged**
