### PR TITLE
update travis to support archlinux and enable distcheck

### PR DESCRIPTION
**Pull request by yetist**
After merge #1133 , this can works fine.

### CODE REVIEW

**Comment by yetist** [comment]
`make distcheck` failed on debian.

Debian seems to check very strict, these files need to be added to POTFILES.in to fix it:
```
The following files contain translations and are currently not in use. Please
consider adding these to the POTFILES.in file, located in the po/ directory.
sub/data/caja-autorun-software.desktop.in
sub/data/caja-browser.desktop.in
sub/data/caja-computer.desktop.in
sub/data/caja-file-management-properties.desktop.in
sub/data/caja-folder-handler.desktop.in
sub/data/caja-home.desktop.in
sub/data/caja.desktop.in
If some of these files are left out on purpose then please add them to
POTFILES.skip instead of POTFILES.in. A file 'missing' containing this list
of left out files has been written in the current directory.
Please report to http://www.mate-desktop.org
```

**Comment by raveit65** [comment]
They are as *.in.in files in POTFILES.in

```
data/caja-autorun-software.desktop.in.in
data/caja-browser.desktop.in.in
data/caja-computer.desktop.in.in
data/caja.desktop.in.in
data/caja-file-management-properties.desktop.in.in
data/caja-folder-handler.desktop.in.in
data/caja-home.desktop.in.in
```
If i recall correctly than adding them again as .in files willl´ break build.

**Comment by yetist** [comment]
This line is in *.desktop.in.in files, is it useful?
```
X-MATE-Bugzilla-Version=@VERSION@
```
If it doesn't work, I think we can fix the distcheck fail on debian.

**Comment by raveit65** [comment]
I think this is an old remnant from gnome2.
Still wondering if gnome use that today after they switched to gitlab and dropped bugzilla.
But i am not sure if Mate needs that.
@monsta 
Any idea?

**Comment by raveit65** [comment]
It is already removed from nautilus https://gitlab.gnome.org/GNOME/nautilus/commit/3868b4cc871734fe9e9fa3d050dfd70b4b6d6932
We can remove it too.......from all repos :)

**Comment by raveit65** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=776796

**Comment by monsta** [comment]
Ok, that explains what it did originally at least. And our lines look like another case of excessive gnome -> mate renaming back in 2011... So it can be removed, I'm sure we never had any server or tool that parsed `X-MATE-Bugzilla` stuff :slightly_smiling_face:

**Pull request merged**
