### PR TITLE
Add accessible names for buttons in file transfer operations dialog

### PR DESCRIPTION
**Pull request by TheMuso**

### CODE REVIEW

**Comment by sc0w** [comment]
I have tested and I see no differences

@TheMuso can you provide screenshots?

**Comment by TheMuso** [comment]
This change is for assistive technology users. YOu want to test with something like Orca, or examine the accessible object data with accerciser.

**Comment by lukefromdc** [comment]
This is what I get now with caja master accerciser with the file transfer dialog. I assume we are looking for names displayed by those buttons etc? I have never, ever been able to get sound to work with orca, only save dubug output from it to a file.

**Comment by lukefromdc** [comment]
Here's what I got with this PR:

Accerciser_Caja_w_PR

**Comment by lukefromdc** [comment]
Best if someone more familiar than I with accessability reviews this too, but I will merge it if no response in a day or two

**Pull request merged**
