### PR TITLE
Fix for #438

### PR DESCRIPTION
**Pull request by bl0ckeduser**
This should fix the issue and keep the old bugfix still good
Screen shot: http://www.cs.mcgill.ca/~gcormi5/bugfixcaja2016.png

Thank you
Happy new year 2016

Gabriel

### CODE REVIEW

**Comment by raveit65** [comment]
Happy new year and thank you.
merged https://github.com/mate-desktop/caja/commit/61800829da41036da5719b0e39e6f015cbd75f9a

**Comment by monsta** [comment]
Thanks! That was an annoying issue.

I guess we're not reverting https://github.com/mate-desktop/caja/pull/285 then?

**Comment by raveit65** [comment]
> I guess we're not reverting #285 then?

 no, only if you want to intoduced the old bug again :smile: 
But it seems that there is a general failure with this logic because we have the issue with dark themes. https://github.com/mate-desktop/caja/issues/81
I tested local https://git.gnome.org/browse/nautilus/commit/?id=ef74d171892ed7189b4a52695ae8de575d2dac1a
which replace eel-background usage and is used by nemo too, here the issue with dark themes is gone.
But only applying this commit causes other problems.

**Comment by monsta** [comment]
@bl0ckeduser: damn, I can still reproduce it with custom background using steps from https://github.com/mate-desktop/caja/issues/438#issuecomment-169078577. Only it's not light on light, it's dark on dark...

E.g. I have black font in my GTK+ theme, then I set a dark background using Emblems & Backgrounds dialog, then open three tabs using the mentioned steps to reproduce. Text on the third tab is black on dark background... :confused:

**Comment by monsta** [comment]
Note: this is **without** changes from https://github.com/mate-desktop/caja/pull/501.

**Comment by monsta** [comment]
Ok, now fixed with https://github.com/mate-desktop/caja/pull/526.

**Pull request closed without merging**
