### PR TITLE
Fix test-eel-image-table

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
With master the icon is not shown. This builds and runs fine, and the mate icon is shown at various sizes in the table with it, not sure why the size varies

**Comment by raveit65** [comment]
Weird, i don't get it working.
```
[rave@mother caja-dist]$ ./test/test-eel-image-table 

** (lt-test-eel-image-table:257465): CRITICAL **: 15:12:17.042: test_pixbuf_new_named: assertion 'pixbuf != NULL' failed

** (lt-test-eel-image-table:257465): CRITICAL **: 15:12:17.042: test_pixbuf_new_named: assertion 'pixbuf != NULL' failed

** (lt-test-eel-image-table:257465): CRITICAL **: 15:12:17.042: test_pixbuf_new_named: assertion 'pixbuf != NULL' failed

etc.
```
```
[rave@mother caja-dist]$ git branch 
  1.22
  1.24
  gettimeofday
  master
* test-eel-image-table
[rave@mother caja-dist]$ git log
commit a62aee7e25e3e07acf1a9e7f4bacc0701f03a479 (HEAD -> test-eel-image-table)
Author: rbuj <robert.buj@gmail.com>
Date:   Thu Nov 12 09:16:32 2020 +0100

    test-eel-image-table: Fix the filename for the test image

commit cabaa6d47cc74b6ebaf929fa377155cd1e9e7f4d
Author: rbuj <robert.buj@gmail.com>
Date:   Thu Nov 12 09:04:46 2020 +0100

    test-eel-image-table: Use the UTF-8 encoding for the file itself

commit aafb541adef96a7bdf4594ae66dbf0d7b71d2701 (origin/master, origin/HEAD, master)
Author: rbuj <robert.buj@gmail.com>
Date:   Thu Nov 12 12:10:50 2020 +0100

    test-eel-labeled-image: Fix showing the image on the controls

commit 2c61357fa601376e4ab4a1603f814f39315c59ad
Author: rbuj <robert.buj@gmail.com>
Date:   Thu Nov 12 10:32:46 2020 +0100

    fm-properties-window: make the location of system folders portable

commit 47babe69871cd65b2fb3ae2d9f97b5c31331a28f
Author: Pablo Barciela <scow@riseup.net>
Date:   Wed Aug 12 01:41:09 2020 +0200

    Remove unused macros
```

**Comment by rbuj** [comment]
@raveit65 test:
```
git clone git@github.com:mate-desktop/caja.git
cd caja
git checkout test-eel-image-table 
git rebase master 
git submodule init
git submodule update --recursive --remote
./autogen.sh --prefix=/usr && make && sudo make install
```

**Comment by raveit65** [comment]
Caja is already installed with patches form this branch via dnf package manger in /usr.
Now compiling and runing test binary with
`./autogen.sh && make && ./test/test-eel-image-table`
gives me the error (/usr/local/ is default).
But compiling and runing test binary with
`./autogen.sh --prefix=/usr && make && ./test/test-eel-image-table`
works like a charm :smile:

**Review by raveit65 — APPROVED** [review]
LGTM

**Pull request merged**
