### PR TITLE
caja properties-window: display dir last modified

### LINKED ISSUE #1406: Directory properties does not display last modified date
https://gitlab.gnome.org/GNOME/nautilus/-/merge_requests/409

#### Expected behaviour
Display last modified date on directories

#### Actual behaviour
Last modified date not displayed in UI properties

#### Steps to reproduce the behaviour
 - Select folder, open properties

### PR DESCRIPTION
**Pull request by wesinator**
closes #1406 

based on https://gitlab.gnome.org/GNOME/nautilus/-/merge_requests/409/diffs

### CODE REVIEW

**Comment by rbuj** [comment]
`Modified` should not be displayed on a mount point:

Before:

Screenshot at 2020-06-30 14-41-47

After:

Screenshot at 2020-06-30 14-56-49

**Comment by raveit65** [comment]
Oh, i didn't check that.
But why it is bad?

@wesinator 
Any idea to exclude that for mount points?

**Comment by wesinator** [comment]
> Oh, i didn't check that.
> But why it is bad?
> 
> @wesinator
> Any idea to exclude that for mount points?

No - I just adopted the fix from the upstream nautilus change 

I don't think it's really a problem 
It seems from the screenshot the mount point is identified as a directory in the file manager, hence why it shows modified date.

**Comment by rbuj** [comment]
PR #1424

**Comment by rbuj** [comment]
From my point of view, it's a date that makes no sense for mount points and it can lead to confusion, since it displays the date on which the volume was mounted, which has nothing to do with the date on which the volume was last modified.

**Pull request merged**
