### PR TITLE
restore DBus interface initialization

### PR DESCRIPTION
**Pull request by monsta**
Fixes https://github.com/mate-desktop/caja/issues/771

Copied from 1.16 code. Not sure if it should be placed at that point or somewhere below in the code, so feel free to move it if there's a reason for it.

### CODE REVIEW

**Comment by clefebvre** [comment]
Looks good to me.

Just need to confirm whether it was removed by @lukefromdc by mistake or if there was a reason for it not to be there. Maybe he removed it to workaround another issue? I don't know, Luke should review/confirm.

**Comment by lukefromdc** [comment]
I will be testing this momentarily, looks like a simple piece left out by accident-and that didn't show itself on a system with both Nemo and Nautilus also installed.

**Comment by lukefromdc** [comment]
Rebased and merged with 
https://github.com/mate-desktop/caja/commit/00a679615d135db4016330c18ee731a668cdd8b4

**Comment by lukefromdc** [comment]
I would now advise this be cherrypicked for 1.18 as it is a bugfix

**Comment by monsta** [comment]
Thanks for testing. Yes, it's a fix for regression so it should go into 1.18 too.

**Comment by monsta** [comment]
Picked for 1.18 in https://github.com/mate-desktop/caja/commit/6ece67ffa2b3c90f4c0ae69147b62ea255da3636.

**Pull request closed without merging**
