### PR TITLE
Fix backgrounds and emblems dialog

### PR DESCRIPTION
**Pull request by lukefromdc**
Fetch name and not display_name due to xmlGetProp returning NULL on the latter. Note that use of accelerators is the only difference within the XML file

### CODE REVIEW

**Comment by lukefromdc** [comment]
Fix https://github.com/mate-desktop/caja/issues/1480

**Comment by raveit65** [comment]
Just a rebase with master.

**Comment by raveit65** [comment]
Buttons are there with commit but they are untranslated.
Bildschirmfoto zu 2021-04-27 19-08-11

**Comment by lukefromdc** [comment]
OK, someone who knows how to work on that will have to fix translations as I cannot test or work on those. 
Otherwise I have a one-line fix suitable for my own use, might be good enough if nobody else ever gets this. Still no idea the reason for that though

**Comment by lukefromdc** [comment]
Called for another review, we need to decide what to do with this. I cannot fix the translations

**Comment by vkareh** [comment]
@lukefromdc I cannot reproduce this issue in F34.

However, I _think_ you can try translating the `name` attribute by making this change:
```diff
diff --git a/its/browser.its b/its/browser.its
index 163cca01..9c091109 100644
--- a/its/browser.its
+++ b/its/browser.its
@@ -3,6 +3,7 @@
            xmlns:gt="https://www.gnu.org/s/gettext/ns/its/extensions/1.0"
            version="2.0">
        <its:translateRule selector="/categories" translate="no"/>
+       <its:translateRule selector="//category/@name" translate="yes"/>
        <its:translateRule selector="//category/@display_name" translate="yes"/>
        <its:translateRule selector="//category/@description" translate="yes"/>
        <its:translateRule selector="//category/pattern/@display_name" translate="yes"/>
```
However, if this works, then it begs the question, what's different between `name` and `display_name`? And it's the accelerator. So if you just remove the underscores from the `display_name` attributes, and revert all other changes, does it work? If so, then that should be the solution for now, as using `name` means we lose the accelerators anyway.

Translating the `name` attribute might have unintended consequences, as it's probably used as an internal ID. I think we should try removing the accelerator markers in the `display_name` and see if that fixes it for you. Basically just change `_Patterns` to `Patterns`, `C_olors` to `Colors`, and `_Emblems` to `Emblems`.

**Comment by lukefromdc** [comment]
OK,I will test this as soon as I get home from this road trip(2 daya expected)

On 7/15/2021 at 8:31 AM, "Victor Kareh" ***@***.***> wrote:
>
***@***.*** I cannot reproduce this issue in F34.
>
>However, I _think_ you can try translating the `name` attribute by 
>making this change:
>```diff
>diff --git a/its/browser.its b/its/browser.its
>index 163cca01..9c091109 100644
>--- a/its/browser.its
>+++ b/its/browser.its
>@@ -3,6 +3,7 @@
>            
>xmlns:gt="https://www.gnu.org/s/gettext/ns/its/extensions/1.0"
>            version="2.0">
>        <its:translateRule selector="/categories" translate="no"/>
>+       <its:translateRule ***@***.***" 
>translate="yes"/>
>        <its:translateRule ***@***.***_name" 
>translate="yes"/>
>        <its:translateRule ***@***.***" 
>translate="yes"/>
>        <its:translateRule 
***@***.***_name" translate="yes"/>

**Comment by lukefromdc** [comment]
Just confirmed that removing accelerators works, we get back the patterns/colors/emblems options without the changes that would affect translations.  Question then becomes why do accelerators not work with the new code?

**Comment by lukefromdc** [comment]
Updates this PR to just remove accelerators and rebase against master

**Review by vkareh — APPROVED** [review]
LGTM

**Comment by raveit65** [comment]
Same problem as before. Only the emblems button is translated in my language.
Normal screenshot without this code.
caja_emblems_full_translated
With this code!
caja-emblems_new
Is it better with other languages?
Any chance that someone with debian or unbuntu installed can confirm the issue before we break translations?

**Comment by lukefromdc** [comment]
We can reopen this if someone else ever gets this issue, but the issue this fixes is now gone in Debian Unstable.

I am guessing something was wrong related to libxml and got fixed. Libxml itself hasn't changed since May, so wondering what is different but the problem is now gone and this change breaks translations it seems

**Pull request closed without merging**
