### PR TITLE
Support querying files by contained text

### PR DESCRIPTION
**Pull request by ptrNine**
ODF files also supported via odt2txt

### CODE REVIEW

**Comment by ptrNine** [comment]
There was a mistake with mime-types. I used `g_content_type_equals` with `"text/plain"`. But content type of text files may be different (`"text/x-c"` for C files, `"text/x-diff"` for diff files, etc.)
Now used `g_content_type_is_mime_type` with `"text/plain"`. That matches all text files.
I had the same problem before that fix. Now all works fine.

**Comment by lukefromdc** [comment]
Out of time today, will have to retest tomorrow at the earliest

**Comment by raveit65** [comment]
Steps to reproduce the issue?
Steps to reproduce the PR?

**Comment by lukefromdc** [comment]
This is a new feature: adding the ability to search files for contained text in Caja's search function as you can in mate-search-tool

**Comment by lukefromdc** [comment]
I just looked over the memory management, matching up new dynamically allocated variables to g_free statements, we should be OK on that assuming I didn't miss anything.

**Comment by raveit65** [comment]
I created a file `test` with the content `sex sells`
But search with `sex sells`, `sells` or `sex` doesn't find this file.
Please provide detailed `steps to test` if you want that i spend more of my spare time to review your PR.

**Comment by lukefromdc** [comment]
The overall UI is a pain to use, the text string to use goes in the box labelled "matches files that contain specified text. The problem is the top  "search:" entry also exists and is very confusing. Ideally when using additional options that would be somehow cleared up

**Comment by raveit65** [comment]
Ok, now it works.
I would really like to see some more explanation from author how to use it.
Than our user-guide can be updated by @mate-desktop/documentation-team

**Comment by raveit65** [comment]
@ptrNine ^^^^^^^

**Comment by ptrNine** [comment]
@raveit65 
For using search by contained text you should:

1. Enable search by clicking on the magnifier sign (or CTRL + F);
2. Run search for any text for enabling  'Search results' bar;
3. Add row by clicking '+' and select 'Contained text' in the combo box;
4. Enter search text in the label and click 'Reload'.

It works for all text files. 
ODF files (Texts, Presentations, Sheets) also supported if you have odt2txt on your system. odt2txt is a simple converter from ODF to plain text available on many repositories. Basically you should simply install odt2txt package for enabling ODF files search.

**Pull request merged**
