### PR TITLE
Rename wallpaper pattern name from MATE to GNOME

### PR DESCRIPTION
**Pull request by rbuj**
browser.xml: use two white spaces for indentation

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
This works and testing it is not affected by https://github.com/mate-desktop/caja/issues/1480 as the "patterns" window is the one that shows by default in the backgrounds and emblems dialog.
I assume this is to reflect GNOME's authorship of the artwork in question?

**Comment by raveit65** [comment]
Why renaming back after 8 years?

**Comment by lukefromdc** [comment]
I have no idea, I only did a functional test

**Comment by rbuj** [comment]
The footprint is the [logo of gnome](https://www.gnome.org/logo-and-trademarks/).

**Comment by raveit65** [comment]
Indeed, there is a gnome footprint :)

**Review by raveit65 — APPROVED** [review]
LGTM

**Pull request merged**
