### PR TITLE
Add scroll tabs with mouse wheel

### PR DESCRIPTION
**Pull request by tamplan**
Add scroll tabs with mouse wheel for file's properties and caja's preferences windows.

### CODE REVIEW

**Comment by sc0w** [comment]
file properties, folder properties, caja preferences, all work now changing tabs with mouse wheel 👍 

The caja tabs <kbd>ctrl</kbd><kbd>T</kbd> don't work with this PR, so, I think the commit message can be changed with a detalied description with the affected tabs.

**Comment by tamplan** [comment]
I wanted to keep the behavior with Ctrl + Tab and not change it to allow just mouse wheel navigation.

I will study the code to see if the two behaviors can cohabit together and eventually change the description later.

**Comment by sc0w** [comment]
@tamplan you can do that in other PR if you like

I mean the commit message needs detailed description to know where works mouse wheel

**Comment by tamplan** [comment]
Houston we've had a problem!

I try to amend message with correct command **commit --amend -m "File's properties and caja's preferences windows : Add scroll tabs with mouse wheel"**
Then **git push**, and i have this message:
>  ! [rejected]        notebook -> notebook (non-fast-forward)

What i need to do now?

Thanks for any help by advance.

**Comment by raveit65** [comment]
Try `git push -f` (--force) to override your remote repo with your local changes.

**Comment by tamplan** [comment]
@raveit65 thanks again.

@sc0w commit message updated, hope is what you want.

**Comment by sc0w** [comment]
but now gihub show us the commit message splitted:



you can use the commit message into a file instead:

first line: little summary
next lines: description

 and later:

```
git commit --amend -F filename

git push -f
```

**Comment by tamplan** [comment]
Better like this?

**Comment by N0rbert** [comment]
I have just reported this on LaunchPad - https://bugs.launchpad.net/ubuntu/+source/caja/+bug/1839539 .

**Comment by sc0w** [comment]
@N0rbert no, this PR doesn't affect that tabs.

**Comment by N0rbert** [comment]
@sc0w OK, I see. Thank you!

**Comment by ericek111** [comment]
Why can't we have this globally for every tab bar (notebook) in GTK and configurable with gsettings? :(

**Pull request merged**
