### PR TITLE
avoid gtk_dialog_new_with_buttons with stock ids

### PR DESCRIPTION
**Pull request by sc0w**

### CODE REVIEW

**Comment by lukefromdc** [comment]
Looks the same to me too

**Comment by raveit65** [comment]
@sc0w 
Today i found a warning in build log while building new PR,
```
caja-query-editor.c: In function 'type_combo_changed':
caja-query-editor.c:718:9: warning: implicit declaration of function 'eel_dialog_add_button'; did you mean 'gtk_dialog_add_button'? [-Wimplicit-function-declaration]
         eel_dialog_add_button (GTK_DIALOG (dialog),
         ^~~~~~~~~~~~~~~~~~~~~
         gtk_dialog_add_button
```
https://github.com/mate-desktop/caja/commit/4fb359018441a9a80984a7a94be1a939efc51bde#diff-a6f962b6bf62a6e0b85df6ada9cc255fR718

**Comment by sc0w** [comment]
@raveit65 oops, yes, confirmed, fixed in https://github.com/mate-desktop/caja/commit/7991810e1214fbe606e6d4de9bcb6417a8256660

**Comment by raveit65** [comment]
Thanks, warning is gone with 1.21.0 tarball.

**Pull request merged**
