### PR TITLE
local #include files who are libraries inside <> instead ""

### PR DESCRIPTION
**Pull request by sc0w**

### CODE REVIEW

**Comment by rbuj** [comment]
You should also modify the eel/check-program.c file:
https://github.com/mate-desktop/caja/blob/e50549cf502f988ff214a2714a8cdd6fb6892244/eel/check-program.c#L31-L34
eel/Makefile.am
```
check_program_SOURCES = check-program.c
check_program_DEPENDENCIES = libeel-2.la
check_program_LDADD = $(EEL_LIBS)
check_program_LDFLAGS = $(check_program_DEPENDENCIES) -lm
```

**Comment by sc0w** [comment]
@rbuj  ok, done

**Comment by rbuj** [comment]
test:
```shell
./autogen.sh --prefix=/usr && make V=1
```
gcc -I option flag is **-I..** for local static libraries.

**Comment by rbuj** [comment]
You can also remove -I../libcaja-private:
```patch
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -11,7 +11,6 @@ bin_PROGRAMS = \
 
 AM_CPPFLAGS = \
        -I$(top_srcdir) \
-       -I$(top_builddir)/libcaja-private \
        $(CORE_CFLAGS) \
        $(WARNING_CFLAGS) \
        $(EXIF_CFLAGS) \
```

**Comment by rbuj** [comment]
If you want to prevent that [gcc looks for headers](https://gcc.gnu.org/onlinedocs/gcc-4.8.0/cpp/Search-Path.html) in system directories in the case of local includes:
```shell
$ cpp -v /dev/null -o /dev/null
...
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-redhat-linux/9/include
 /usr/local/include
 /usr/include
End of search list.
..
```
Then, you can run these commands to use `#include "..."` instead of `#include <...>`:
```shell
find . -type f -name "*.c" -o -name "*.h" -exec sed -i 's/^#include <eel\/\(.*\)>$/#include \"eel\/\1\"/g' {} +
find . -type f -name "*.c" -o -name "*.h" -exec sed -i 's/^#include <libcaja-extension\/\(.*\)>$/#include \"libcaja-extension\/\1\"/g' {} +
find . -type f -name "*.c" -o -name "*.h" -exec sed -i 's/^#include <libcaja-private\/\(.*\)>$/#include \"libcaja-private\/\1\"/g' {} +
find . -type f -name "*.c" -o -name "*.h" -exec sed -i 's/^#include <libegg\/\(.*\)>$/#include \"libegg\/\1\"/g' {} +
```

**Comment by sc0w** [comment]
@rbuj thanks for the info

If this PR is ok, please merge, more improvements can be done in more PRs

**Pull request merged**
