### PR TITLE
Remove the use of the gettimeofday function

### PR DESCRIPTION
**Pull request by rbuj**
Test 1 : see ~/caja-debug-log.txt
```
#!/bin/bash
cat << EOF > ~/caja-debug-log.conf
[debug log]
max lines = 1000
enable domains = async;GLog
EOF

# To write the debug log to disk immediately, send a SIGUSR1 to Caja:
# kill -s SIGUSR1 $(pgrep caja)

# To see Caja log:
# cat ~/caja-debug-log.txt
```
Test 2 : call ./test/test-eel-pixbuf-scale FILENAME
```
./test/test-eel-pixbuf-scale /usr/share/pixmaps/fedora-logo.png
```

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
Builds and runs fine, and caja -c completes without error, but I do not know how to fully test this in terms of the caja-debug-log file's function unless this is it.

**Comment by raveit65** [comment]
Test 2 seems OK, btw. it scales faster now. (msecs --> usecs)
master:
```
[rave@mother caja-test]$ ./test/test-eel-pixbuf-scale /usr/share/pixmaps/fedora-logo.png
scale factors: 16,281250, 5,125000
Time for eel_gdk_pixbuf_scale_down: 10 msecs
Time for INTERP_NEAREST: 0 msecs
Time for INTERP_BILINEAR: 21 msecs
[rave@mother caja-test]$ ./test/test-eel-pixbuf-scale /usr/share/pixmaps/fedora-logo.png
scale factors: 16,281250, 5,125000
Time for eel_gdk_pixbuf_scale_down: 9 msecs
Time for INTERP_NEAREST: 0 msecs
Time for INTERP_BILINEAR: 20 msecs
[rave@mother caja-test]$ ./test/test-eel-pixbuf-scale /usr/share/pixmaps/fedora-logo.png
scale factors: 16,281250, 5,125000
Time for eel_gdk_pixbuf_scale_down: 15 msecs
Time for INTERP_NEAREST: 0 msecs
Time for INTERP_BILINEAR: 21 msecs
```
with that branch:
```
[rave@mother caja-dist]$ ./test/test-eel-pixbuf-scale /usr/share/pixmaps/fedora-logo.png 
scale factors: 16,281250, 5,125000
Time for eel_gdk_pixbuf_scale_down: 150 usecs
Time for INTERP_NEAREST: 14 usecs
Time for INTERP_BILINEAR: 373 usecs
[rave@mother caja-dist]$ ./test/test-eel-pixbuf-scale /usr/share/pixmaps/fedora-logo.png 
scale factors: 16,281250, 5,125000
Time for eel_gdk_pixbuf_scale_down: 107 usecs
Time for INTERP_NEAREST: 8 usecs
Time for INTERP_BILINEAR: 268 usecs
[rave@mother caja-dist]$ ./test/test-eel-pixbuf-scale /usr/share/pixmaps/fedora-logo.png 
scale factors: 16,281250, 5,125000
Time for eel_gdk_pixbuf_scale_down: 159 usecs
Time for INTERP_NEAREST: 10 usecs
Time for INTERP_BILINEAR: 308 usecs
[rave@mother caja-dist]$ ./test/test-eel-pixbuf-scale /usr/share/pixmaps/fedora-logo.png 
scale factors: 16,281250, 5,125000
Time for eel_gdk_pixbuf_scale_down: 258 usecs
Time for INTERP_NEAREST: 24 usecs
Time for INTERP_BILINEAR: 656 usecs
```

But i am missing the the date in `caja-debug-log.txt` with test 1.
```
[rave@mother ~]$ cat caja-debug-log.txt.old 
===== BEGIN MILESTONES =====
0x562b12d2de90 2020/11/15 11:29:04.7438 (USER): user requested dump of debug log
===== END MILESTONES =====
===== BEGIN RING BUFFER =====
0x562b12d2de90 2020/11/15 11:29:01.3358 (USER): Error loading keys from file: Datei oder Verzeichnis nicht gefunden

0x562b12d2de90 2020/11/15 11:29:01.3474 (USER): Error loading keys from file: Datei oder Verzeichnis nicht gefunden

0x562b12d2de90 2020/11/15 11:29:01.3488 (USER): Error loading keys from file: Datei oder Verzeichnis nicht gefunden

0x562b12d2de90 2020/11/15 11:29:01.4140 (USER): window 0x562b130da4c0 open location: old="(none)", new="x-caja-desktop:///"
0x562b12d2de90 2020/11/15 11:29:01.4236 (USER): Bus acquired at org.freedesktop.FileManager1
0x562b12d2de90 2020/11/15 11:29:01.4242 (USER): Acquired the name org.freedesktop.FileManager1 on the session message bus

0x562b12d2de90 2020/11/15 11:29:02.1275 (USER): finished loading window 0x562b130da4c0: x-caja-desktop:///
0x562b12d2de90 2020/11/15 11:29:04.7438 (USER): user requested dump of debug log
===== END RING BUFFER =====


This configuration for the debug log can be re-created
by putting the following in ~/caja-debug-log.conf
(use ';' to separate domain names):

[debug log]
max lines=1000
[rave@mother ~]$ 
```
with that branch:
```
[rave@mother ~]$ cat caja-debug-log.txt
===== BEGIN MILESTONES =====
0x55ce9fd6ee90 (null) (USER): user requested dump of debug log
===== END MILESTONES =====
===== BEGIN RING BUFFER =====
0x55ce9fd6ee90 (null) (USER): Error loading keys from file: Datei oder Verzeichnis nicht gefunden

0x55ce9fd6ee90 (null) (USER): Error loading keys from file: Datei oder Verzeichnis nicht gefunden

0x55ce9fd6ee90 (null) (USER): Error loading keys from file: Datei oder Verzeichnis nicht gefunden

0x55ce9fd6ee90 (null) (USER): window 0x55cea011c500 open location: old="(none)", new="x-caja-desktop:///"
0x55ce9fd6ee90 (null) (USER): Bus acquired at org.freedesktop.FileManager1
0x55ce9fd6ee90 (null) (USER): Acquired the name org.freedesktop.FileManager1 on the session message bus

0x55ce9fd6ee90 (null) (USER): finished loading window 0x55cea011c500: x-caja-desktop:///
0x55ce9fd6ee90 (null) (USER): create new navigation window=0x55cea07623d0
0x55ce9fd6ee90 (null) (USER): window 0x55cea07623d0 open location: old="(none)", new="file:///home/rave"
0x55ce9fd6ee90 (null) (USER): change view of window 0x55cea07623d0: "file:///home/rave" to "OAFIID:Caja_File_Manager_Icon_View"
0x55ce9fd6ee90 (null) (USER): finished loading window 0x55cea07623d0: file:///home/rave
0x55ce9fd6ee90 (null) (USER): user requested dump of debug log
===== END RING BUFFER =====


This configuration for the debug log can be re-created
by putting the following in ~/caja-debug-log.conf
(use ';' to separate domain names):

[debug log]
max lines=1000
```
Is that intend?

**Comment by raveit65** [comment]
> .....but I do not know how to fully test this in terms of the caja-debug-log file's function unless this is it.

1. create `~/caja-debug-log.conf `
```
[rave@mother ~]$ cat ~/caja-debug-log.conf 
#!/bin/bash
cat << EOF > ~/caja-debug-log.conf
[debug log]
max lines = 1000
enable domains = async;GLog
EOF

# To write the debug log to disk immediately, send a SIGUSR1 to Caja:
# kill -s SIGUSR1 $(pgrep caja)

# To see Caja log:
# cat ~/caja-debug-log.txt
```
2. make it executable
3. run `kill -s SIGUSR1 $(pgrep caja)`

This will create `~/caja-debug-log.txt`

For some reasons a `killall caja` is needed to create `~/caja-debug-log.txt` again.

**Comment by raveit65** [comment]
@rbuj 
Before we missed this PR.
The date is missing in caja-debug-log.txt with this PR. See my previous comment.

**Comment by lukefromdc** [comment]
What is the purpose removing gettimeofday?

**Comment by rbuj** [comment]
There is no Y2038 problem: nowadays, time_t is 64-bit on almost all platforms.
```C
       #include <sys/time.h>

       int gettimeofday(struct timeval *tv, struct timezone *tz);

           struct timeval {
               time_t      tv_sec;     /* seconds */
               suseconds_t tv_usec;    /* microseconds */
           };
```
However, if we use glib, we can consider gettimeofday a low-level API, which in this case has other better choices:
- g_date_time_format: It's a function intended to use for printing dates with specific placeholders
- g_get_monotonic_time: it's a more suitable function for measuring short time intervals

**Comment by lukefromdc** [comment]
OK, we are waiting for another review, by someone more familiar with using debug logs than I am

**Comment by raveit65** [comment]
@rbuj 
once again, the date is missing in log with this PR.
```
[rave@mother ~]$ cat caja-debug-log.txt
===== BEGIN MILESTONES =====
0x55ce9fd6ee90 (null) (USER): user requested dump of debug log
===== END MILESTONES =====
===== BEGIN RING BUFFER =====
0x55ce9fd6ee90 (null) (USER): Error loading keys from file: Datei oder Verzeichnis nicht gefunden

0x55ce9fd6ee90 (null) (USER): Error loading keys from file: Datei oder Verzeichnis nicht gefunden

0x55ce9fd6ee90 (null) (USER): Error loading keys from file: Datei oder Verzeichnis nicht gefunden

0x55ce9fd6ee90 (null) (USER): window 0x55cea011c500 open location: old="(none)", new="x-caja-desktop:///"
0x55ce9fd6ee90 (null) (USER): Bus acquired at org.freedesktop.FileManager1
0x55ce9fd6ee90 (null) (USER): Acquired the name org.freedesktop.FileManager1 on the session message bus

0x55ce9fd6ee90 (null) (USER): finished loading window 0x55cea011c500: x-caja-desktop:///
0x55ce9fd6ee90 (null) (USER): create new navigation window=0x55cea07623d0
0x55ce9fd6ee90 (null) (USER): window 0x55cea07623d0 open location: old="(none)", new="file:///home/rave"
0x55ce9fd6ee90 (null) (USER): change view of window 0x55cea07623d0: "file:///home/rave" to "OAFIID:Caja_File_Manager_Icon_View"
0x55ce9fd6ee90 (null) (USER): finished loading window 0x55cea07623d0: file:///home/rave
0x55ce9fd6ee90 (null) (USER): user requested dump of debug log
===== END RING BUFFER =====
```

**Comment by rbuj** [comment]
@raveit65 I didn't get null values for date entries after installing the PR and starting a fresh mate-session.
```C
[robert@localhost caja]$ kill -s SIGUSR1 $(pgrep caja)
[robert@localhost caja]$ cat ~/caja-debug-log.txt
===== BEGIN MILESTONES =====
0xccf090 2020/11/23 11:17:32.095659 (USER): user requested dump of debug log
===== END MILESTONES =====
===== BEGIN RING BUFFER =====
0xccf090 2020/11/23 11:16:57.594515 (GLog): Parsing local command line, no_default_window 1, quit 0, self checks 0, no_desktop 0
0xccf090 2020/11/23 11:16:57.604482 (GLog): unsetenv() is not thread-safe and should not be used after threads are created
0xccf090 2020/11/23 11:16:58.261507 (GLog): _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
0xccf090 2020/11/23 11:16:58.340105 (GLog): _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
0xccf090 2020/11/23 11:16:58.474058 (GLog): na_settings_register_type
0xccf090 2020/11/23 11:16:58.474071 (GLog): na_settings_class_init: klass=0xe4ec70
0xccf090 2020/11/23 11:16:58.474078 (GLog): na_settings_instance_init: instance=0xf15c40 (NASettings), klass=0xe4ec70
0xccf090 2020/11/23 11:16:58.474083 (GLog): na_settings_new: reading mandatory configuration
0xccf090 2020/11/23 11:16:58.489191 (GLog): na_settings_key_file_new: out=
0xccf090 2020/11/23 11:16:58.489206 (GLog): na_settings_key_file_new: err=ls: cannot access '/etc/xdg/caja-actions/caja-actions.conf': No such file or directory

0xccf090 2020/11/23 11:16:58.489373 (GLog): na_settings_content_load_keys: /etc/xdg/caja-actions/caja-actions.conf: file doesn't exist
0xccf090 2020/11/23 11:16:58.489378 (GLog): na_settings_new: reading user configuration
0xccf090 2020/11/23 11:16:58.522606 (GLog): na_settings_key_file_new: out=-rw-r--r--. 1 robert robert 34 Nov 23 08:31 /home/robert/.config/caja-actions/caja-actions.conf

0xccf090 2020/11/23 11:16:58.522623 (GLog): na_settings_key_file_new: err=
0xccf090 2020/11/23 11:16:58.523228 (GLog): na_boxed_register_type
0xccf090 2020/11/23 11:16:58.523905 (GLog): na_boxed_class_init: klass=0xea8490
0xccf090 2020/11/23 11:16:58.523912 (GLog): na_boxed_instance_init: instance=0xebe1a0 (NABoxed), klass=0xea8490
0xccf090 2020/11/23 11:16:58.523919 (GLog): na_settings_read_key_value_from_key_file: group=runtime, key=items-level-zero-order, value=, mandatory=False
0xccf090 2020/11/23 11:16:58.551606 (USER): Error loading keys from file: No such file or directory

0xccf090 2020/11/23 11:16:58.570698 (USER): Error loading keys from file: No such file or directory

0xccf090 2020/11/23 11:16:58.580637 (USER): Error loading keys from file: No such file or directory

0xccf090 2020/11/23 11:16:58.747016 (USER): window 0x10c44b0 open location: old="(none)", new="x-caja-desktop:///"
0xccf090 2020/11/23 11:16:58.754468 (USER): Bus acquired at org.freedesktop.FileManager1
0xccf090 2020/11/23 11:16:58.755774 (USER): Acquired the name org.freedesktop.FileManager1 on the session message bus

0xccf090 2020/11/23 11:16:58.979618 (async): files added in window 0x10c44b0: x-caja-desktop:///
	x-caja-desktop:///trash
	x-caja-desktop:///computer
	x-caja-desktop:///home
0xccf090 2020/11/23 11:16:59.188233 (USER): finished loading window 0x10c44b0: x-caja-desktop:///
0xccf090 2020/11/23 11:16:59.225811 (async): files changed in window 0x10c44b0: x-caja-desktop:///
	x-caja-desktop:///trash
0xccf090 2020/11/23 11:16:59.225838 (async): files changed in window 0x10c44b0: x-caja-desktop:///
	x-caja-desktop:///home
0xccf090 2020/11/23 11:16:59.225979 (async): files changed in window 0x10c44b0: x-caja-desktop:///
	x-caja-desktop:///computer
0xccf090 2020/11/23 11:17:32.095659 (USER): user requested dump of debug log
===== END RING BUFFER =====


This configuration for the debug log can be re-created
by putting the following in ~/caja-debug-log.conf
(use ';' to separate domain names):

[debug log]
enable domains=async;GLog;
max lines=1000
```

**Comment by raveit65** [comment]
I rebuilt the RPM and tested again with same result.
```
===== BEGIN MILESTONES =====
0x56338a3a7e90 (null) (USER): user requested dump of debug log
===== END MILESTONES =====
===== BEGIN RING BUFFER =====
0x56338a3a7e90 (null) (USER): Error loading keys from file: Datei oder Verzeichnis nicht gefunden

0x56338a3a7e90 (null) (USER): Error loading keys from file: Datei oder Verzeichnis nicht gefunden

0x56338a3a7e90 (null) (USER): Error loading keys from file: Datei oder Verzeichnis nicht gefunden

0x56338a3a7e90 (null) (USER): window 0x56338a7583d0 open location: old="(none)", new="x-caja-desktop:///"
0x56338a3a7e90 (null) (USER): Bus acquired at org.freedesktop.FileManager1
0x56338a3a7e90 (null) (USER): Acquired the name org.freedesktop.FileManager1 on the session message bus
 <cut>
```
No idea what is different....

**Comment by rbuj** [comment]
Test 1: check the md5 of the modified files
```
cat <<EOF >> md5
7859695caf4bc2e7e20d7429b0cbb900  libcaja-private/caja-debug-log.c
a042dc4e714e9781450ddd33f295385e  test/test-eel-pixbuf-scale.c
EOF
md5sum -c md5
rm -f md5
```
Test 2: check the glib functions
```
cat <<EOF > datetime.c
/*
 * Copyright (C) 2011 Red Hat, Inc.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of the
 * licence, or (at your option) any later version.
 *
 * This is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, see <http://www.gnu.org/licenses/>.
 */

#include <locale.h>
#include <glib.h>

int
main (int argc, char *argv[])
{
  gchar *fmt;
  GDateTime *dt;
  gchar *str;

  setlocale (LC_ALL, "");

  if (argc > 1)
    fmt = argv[1];
  else
    fmt = "%x %X";

  dt = g_date_time_new_now_local ();
  str = g_date_time_format (dt, fmt);
  g_print ("%s\n", str);
  g_free (str);
  g_date_time_unref (dt);

  return 0;
}
EOF
gcc datetime.c `pkg-config --cflags --libs glib-2.0` -o datetime
./datetime
rm -f datetime.c datetime
```

**Comment by raveit65** [comment]
```
[rave@mother Schreibtisch]$ ./datetime 
24.11.2020 15:00:20
[rave@mother Schreibtisch]$ 
```
```
[rave@mother caja]$ git branch 
  1.22
  1.24
* gettimeofday
  master
  test-eel-image-table
  
[rave@mother caja]$ md5sum libcaja-private/caja-debug-log.c
7859695caf4bc2e7e20d7429b0cbb900  libcaja-private/caja-debug-log.c

[rave@mother caja]$ md5sum test/test-eel-pixbuf-scale.c
a042dc4e714e9781450ddd33f295385e  test/test-eel-pixbuf-scale.c

[rave@mother caja]$ git log
commit 6efd06203df394310089e9eb05db3903321d5d06 (HEAD -> gettimeofday)
Author: rbuj <robert.buj@gmail.com>
Date:   Thu Nov 12 13:30:05 2020 +0100

    test-eel-pixbuf-scale: Profile only the scaling functions just once

commit ac7414cba06d55d37f8eb00809a907b843282d01
Author: rbuj <robert.buj@gmail.com>
Date:   Thu Nov 12 12:58:25 2020 +0100

    Remove the use of the gettimeofday function

commit c3b53c8c877536f04ea6de0aeea709833b90c94c (origin/master, origin/HEAD, master)
Author: rbuj <robert.buj@gmail.com>
Date:   Thu Nov 12 09:16:32 2020 +0100

    test-eel-image-table: Fix the filename for the test image

commit 5948777212d5f37fb9a8fa51913079872b7e9fdc
Author: rbuj <robert.buj@gmail.com>
Date:   Thu Nov 12 09:04:46 2020 +0100
```
I don't install applications by hand from github repos. I prefer to use commit as patches for my official fedora RPMs with dnf package-manager.
In this case i am using 1.25.0 tarball + those patches.
```
Patch1:         caja_0001-caja-properties-window-display-dir-last-modified.patch
# https://github.com/mate-desktop/caja/pull/1424
Patch2:         caja_0001-fm-properties-window-Do-not-display-Modified-field-f.patch
# https://github.com/mate-desktop/caja/pull/1421
Patch3:         caja_0001-Remove-unused-variable-from-eel_notebook_scroll_even.patch
# https://github.com/mate-desktop/caja/pull/1423
Patch4:         caja_0001-caja-file-management-properties-Reduce-the-height-of.patch
# https://github.com/mate-desktop/caja/pull/1429
Patch5:         caja_0001-fm-icon-view-totem-audio-preview-was-removed-in-tote.patch
# https://github.com/mate-desktop/caja/pull/1422
Patch6:         caja_0001-caja-notebook-Add-notebook-scroll-event.patch
# https://github.com/mate-desktop/caja/commit/afc16dc
Patch7:         caja_0001-Guard-block-is-missing.patch
# https://github.com/mate-desktop/caja/commit/969fe79
Patch8:         caja_0002-Add-a-Bookmarks-sidebar-to-Caja.patch
# https://github.com/mate-desktop/caja/pull/1436
Patch9:         caja_0003-caja-dnd-Create-links-by-default-on-dnd-from-Web-Bro.patch
Patch10:        caja_0001-Remove-trailing-spaces-tabs.patch
Patch11:        caja_0001-eel-editable-label-Consecutive-break-return-statemen.patch
# https://github.com/mate-desktop/caja/pull/1447
Patch12:        caja_0001-fm-directory-view-Error-message-when-a-link-could-no.patch
# https://github.com/mate-desktop/caja/pull/1448
Patch13:        caja_0001-Remove-unused-macros.patch
# https://github.com/mate-desktop/caja/pull/1461
Patch14:        caja_0001-Fix-i18n-in-backgrounds-and-emblems-dialog.patch
# https://github.com/mate-desktop/caja/pull/1456
Patch15:        caja_0001-middle-clicking-the-reload-button-duplicates-tab.patch
# https://github.com/mate-desktop/caja/pull/1465
Patch16:        caja_0001-Remove-the-use-of-the-gettimeofday-function.patch
Patch17:        caja_0002-test-eel-pixbuf-scale-Profile-only-the-scaling-funct.patch
# https://github.com/mate-desktop/caja/pull/1463
Patch18:        caja_0001-fm-properties-window-make-the-location-of-system-fol.patch
# https://github.com/mate-desktop/caja/commit/aafb541
Patch19:        caja_0001-test-eel-labeled-image-Fix-showing-the-image-on-the-.patch
# https://github.com/mate-desktop/caja/pull/1462
Patch20:        caja_0002-test-eel-image-table-Use-the-UTF-8-encoding-for-the-.patch
Patch21:        caja_0003-test-eel-image-table-Fix-the-filename-for-the-test-i.patch
```
So this should be exactly the same like this branch. And i recreated the patches several times for a rebuild of the RPM, to get sure.

@cwendling 
Maybe you can confirm that the date in caja-debug-log.txt is working?

**Comment by raveit65** [comment]
Good news. I have a log with a date in f33.
```
[rave@localhost ~]$ kill -s SIGUSR1 $(pgrep caja)
[rave@localhost ~]$ cat caja-debug-log.txt 
===== BEGIN MILESTONES =====
0x558cbc3e8890 2020/11/24 20:47:40.765608 (USER): user requested dump of debug log
===== END MILESTONES =====
===== BEGIN RING BUFFER =====
0x558cbc3e8890 2020/11/24 20:44:18.601725 (USER): Error loading keys from file: No such file or directory

0x558cbc3e8890 2020/11/24 20:44:18.603889 (USER): Error loading keys from file: No such file or directory

0x558cbc3e8890 2020/11/24 20:44:18.605152 (USER): Error loading keys from file: No such file or directory

0x558cbc3e8890 2020/11/24 20:44:18.741555 (USER): window 0x558cbc780480 open location: old="(none)", new="x-caja-desktop:///"
0x558cbc3e8890 2020/11/24 20:44:18.753116 (USER): Bus acquired at org.freedesktop.FileManager1
0x558cbc3e8890 2020/11/24 20:44:18.754486 (USER): Acquired the name org.freedesktop.FileManager1 on the session message bus

0x558cbc3e8890 2020/11/24 20:44:19.270651 (USER): finished loading window 0x558cbc780480: x-caja-desktop:///
0x558cbc3e8890 2020/11/24 20:44:28.219521 (USER): create new navigation window=0x558cbcbc83b0
0x558cbc3e8890 2020/11/24 20:44:28.219531 (USER): window 0x558cbcbc83b0 open location: old="(none)", new="file:///home/rave"
0x558cbc3e8890 2020/11/24 20:44:28.465612 (USER): change view of window 0x558cbcbc83b0: "file:///home/rave" to "OAFIID:Caja_File_Manager_Icon_View"
0x558cbc3e8890 2020/11/24 20:44:28.552660 (USER): finished loading window 0x558cbcbc83b0: file:///home/rave
0x558cbc3e8890 2020/11/24 20:44:36.636025 (USER): finished loading window 0x558cbcbc83b0: file:///home/rave
0x558cbc3e8890 2020/11/24 20:44:37.576299 (USER): finished loading window 0x558cbcbc83b0: file:///home/rave
0x558cbc3e8890 2020/11/24 20:44:37.576774 (USER): finished loading window 0x558cbc780480: x-caja-desktop:///
0x558cbc3e8890 2020/11/24 20:46:24.764236 (USER): selection changed in window 0x558cbcbc83b0
	file:///home/rave/neue%20Datei
0x558cbc3e8890 2020/11/24 20:46:31.012253 (USER): rename file old="file:///home/rave/neue%20Datei", new="caja-debug-log.conf"
0x558cbc3e8890 2020/11/24 20:46:31.012758 (USER): selection changed in window 0x558cbcbc83b0
0x558cbc3e8890 2020/11/24 20:46:31.803847 (USER): selection changed in window 0x558cbcbc83b0
	file:///home/rave/caja-debug-log.conf
0x558cbc3e8890 2020/11/24 20:46:32.049490 (USER): caja_mime_activate_files window=0x558cbcbc83b0
	file:///home/rave/caja-debug-log.conf
0x558cbc3e8890 2020/11/24 20:47:11.638608 (USER): selection changed in window 0x558cbcbc83b0
0x558cbc3e8890 2020/11/24 20:47:40.765608 (USER): user requested dump of debug log
===== END RING BUFFER =====


This configuration for the debug log can be re-created
by putting the following in ~/caja-debug-log.conf
(use ';' to separate domain names):

[debug log]
max lines=1000
[rave@localhost ~]$ 
```
I just rebuilt mate-1.25.x from my local f32 repository 1:1 for a local f33 repository.
Do we require > glib2-2.64.6-1.fc32.x86_64 for this feature?
```
[rave@localhost ~]$ rpm -qa glib2
glib2-2.66.3-1.fc33.x86_64
```

**Comment by rbuj** [comment]
Maybe it’s because the microsecond placeholder was added in August.
```
Date:   Wed Aug 5 13:27:47 2020 +0200

    gdatetime: Add %f format specifier for microseconds
    
    Same specifier used as in pythons datetime.strptime
```
https://github.com/GNOME/glib/commit/3b0eca5be69059d920253d0f54e54d9aef4d87d9

**Comment by rbuj** [comment]
@raveit65 done

**Review by raveit65 — APPROVED** [review]
After latest changes caja-debug-log.txt shows the date with older an newer glib version.
See comments for details.

**Pull request merged**
