### PR TITLE
Remove dead code, fix a memory leak

### PR DESCRIPTION
**Pull request by lukefromdc**
Remove two dead code blocks and fix a memory leak left over from last commit

### CODE REVIEW

**Comment by klemsgithub** [comment]
you can add a g_free (uri); just before the for to take into account the first occurence of g_file_get_uri (locations[0]).

**Comment by lukefromdc** [comment]
Done and force-pushed

**Comment by raveit65** [comment]
Please do not merge. I get an abrt alarm from fedora-bug-reporting-tool every time when i start caja as root.
I will give you more info later.

**Comment by raveit65** [comment]
Forgot my last reply, the segfault with `/usr/libexec/xdg-desktop-portal` and starting caja as root, is gone after a session restart.
Btw. i could reproduce the segfault without this PR and the commit before.
So, it seems that everything is fine.

**Pull request merged**
