### PR TITLE
avoid deprecated 'gtk_dialog_get_action_area'

### PR DESCRIPTION
**Pull request by sc0w**

### CODE REVIEW

**Comment by lukefromdc** [comment]
On the crash I got this:
`
[ 2644.816519] traps: caja[7024] general protection ip:7f95865e3f8e sp:7ffc081d9198 error:0 in libgobject-2.0.so.0.5600.1[7f95865b0000+50000]
`
Since it happened some of the time but not all of the time I cannot reliably reproduce it, but will play with it from gdb a bit

**Comment by lukefromdc** [comment]
I got these warningsfrom autorun in GDB but no crashes, and they seem to be the same in master, both versions shown here with my annotations to show when things are happening:

This PR:
```

On opening preferences dialog:
Gtk-Message: 15:35:53.948: GtkDialog mapped without a transient parent. This is discouraged.

On going to "Media" tab:
no warnings
On selecting "never prompt..."
no warnings
On enabling Autorun:
(caja:8604): Gtk-CRITICAL **: 15:37:34.882: gtk_builder_get_object: assertion 'GTK_IS_BUILDER (builder)' failed

(caja:8604): Gtk-CRITICAL **: 15:37:34.883: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

On closing dialog:
no warnings

Autorun prompt pops up:
Gtk-Message: 15:38:17.107: GtkDialog mapped without a transient parent. This is discouraged.

On close of Autorun popup by starting DVD:
(caja:19877): Gtk-CRITICAL **: 15:50:19.587: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed


stopping DVD: 
no warnings

Reopening prefs:
Gtk-Message: 15:39:57.572: GtkDialog mapped without a transient parent. This is discouraged.

Setting "never prompt" after it has been used:
(caja:8604): Gtk-CRITICAL **: 15:40:18.091: gtk_builder_get_object: assertion 'GTK_IS_BUILDER (builder)' failed

(caja:8604): Gtk-CRITICAL **: 15:40:18.091: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

(caja:8604): Gtk-CRITICAL **: 15:40:18.091: gtk_builder_get_object: assertion 'GTK_IS_BUILDER (builder)' failed

(caja:8604): Gtk-CRITICAL **: 15:40:18.091: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

Ejecting disk:
No warnings

Closing dialog: Caja did not crash this time (not reliably reproduceable)

```
MASTER:
```

Opening prefs:

Gtk-Message: 15:44:43.862: GtkDialog mapped without a transient parent. This is discouraged.

Opening "media"tab:
No warnings

Enabling autorun:
No warnings

Autorun popup appears:

Gtk-Message: 15:46:28.186: GtkDialog mapped without a transient parent. This is discouraged.
[New Thread 0x7fffcf0cf700 (LWP 17083)]

on CLOSING autorun popup by starting DVD:

(caja:15680): Gtk-CRITICAL **: 15:46:45.995: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

Stopping playback: no warnings

Ejecting: no warnings

On setting "never prompt..."

(caja:15680): Gtk-CRITICAL **: 15:47:35.938: gtk_builder_get_object: assertion 'GTK_IS_BUILDER (builder)' failed

(caja:15680): Gtk-CRITICAL **: 15:47:35.939: gtk_widget_set_sensitive: assertion 'GTK_IS_WIDGET (widget)' failed

Closing prefs: no warnings

```

**Comment by sc0w** [comment]
The code is clean, and it doesn't change the behavior of buttons, only the look

I did the same code in fm-properties-window.c in this PR, it crashes using the buttons in the "properties of file" dialog?

I think the crash is not related to this PR

This PR only affects this two dialogs:

screenshot at 2018-05-14 23-09-52

screenshot at 2018-05-14 23-07-38

The expected: the same look as before, the buttons in the same place

**Comment by lukefromdc** [comment]
Closing the second dialog was where I had problems, but the warnings are the same in this PR and in master. I never got the crash in master, but could not duplicate it every time I tried another test build of this PR either so I cannot verify that the PR has anything to do with it.  If anyone can ever invoke that crash consistantly, gdb can then be used to find the problem

**Pull request merged**
