### PR TITLE
Backport: HiDPI Support

### LINKED ISSUE #933: [HiDPI] Icons could be created beyond screen boundaries
#### Expected behaviour

When creating icons on the desktop, icons should be wrapped to a second column if the first is exhausted in its vertical space.

#### Actual behaviour

With `window-scaling-factor=2`, the vertical space is not properly scaled, that icons could be put in the same column until it reaches approximately twice the vertical space.

#### Steps to reproduce the behaviour

Set `window-scaling-factor=2`, then open a terminal emulator on the desktop, run the following command...

```
mkdir 1
mkdir 2
mkdir 3
...
```

Until issue is prevalent.

#### MATE general version

MATE 1.20.0.

#### Package version

mate-* 1.20.0.

#### Linux Distribution

AOSC OS, package tree: https://github.com/AOSC-Dev/aosc-os-abbs/tree/staging/extra-mate/.

#### Link to downstream report of your Distribution

N/A

### PR DESCRIPTION
**Pull request by vkareh**
Most of these commits applied pretty cleanly with some massaging (`:1,%s/nautilus/caja/g`, etc). The biggest one: https://github.com/mate-desktop/caja/commit/e2c58c9e3fb0efa7ad613da101a993ff68b37061 required quite a bit of manipulation to get right.

* Fixes mate-desktop/mate-desktop/issues/304
* Fixes #933

### CODE REVIEW

**Comment by vkareh** [comment]
This is good feedback, thanks.

The sidebar icons scaled up, but are blurry. If we want that size, I can try changing them to cairo surfaces, otherwise I might just not scale them instead (and hope that they are no longer blurry). Un-scaling them would fix the emblems.

The build warnings should be easy to fix. I'll work on this either tonight or tomorrow morning

**Comment by flexiondotorg** [comment]
First of all, thanks for working on the @vkareh! We are getting closer :smile: 

# Warnings

I've also compared warnings and found the following.

## `real_map_pixbuf` to `real_map_surface`

One warning is retained but the function name has changed. So not a new warning really.

### Before
```
caja-icon-canvas-item.c: In function ‘real_map_pixbuf’:
caja-icon-canvas-item.c:1745:17: warning: ‘gtk_style_context_get_background_color’ is deprecated: Use 'gtk_render_background' instead [-Wdeprecated-declarations]
                 gtk_style_context_get_background_color (style, GTK_STATE_FLAG_SELECTED, &color);
```

### After
```
caja-icon-canvas-item.c: In function ‘real_map_surface’:
caja-icon-canvas-item.c:1774:17: warning: ‘gtk_style_context_get_background_color’ is deprecated: Use 'gtk_render_background' instead [-Wdeprecated-declarations]
                 gtk_style_context_get_background_color (style, GTK_STATE_FLAG_SELECTED, &color);
```

I confirm this new warning also noted by @raveit65 

```
In file included from caja-icon-canvas-item.h:28:0,
                 from caja-icon-canvas-item.c:27:
caja-icon-canvas-item.c: In function ‘caja_icon_canvas_item_get_icon_rectangle’:
../eel/eel-canvas.h:110:41: warning: passing argument 1 of ‘get_scaled_icon_size’ from incompatible pointer type [-Wincompatible-pointer-types]
 #define EEL_CANVAS_ITEM(obj)            (G_TYPE_CHECK_INSTANCE_CAST ((obj), EEL_TYPE_CANVAS_ITEM, EelCanvasItem))
                                         ^
caja-icon-canvas-item.c:2465:27: note: in expansion of macro ‘EEL_CANVAS_ITEM’
     get_scaled_icon_size (EEL_CANVAS_ITEM (item), &width, &height);
                           ^~~~~~~~~~~~~~~
caja-icon-canvas-item.c:502:1: note: expected ‘CajaIconCanvasItem * {aka struct CajaIconCanvasItem *}’ but argument is of type ‘EelCanvasItem * {aka struct _EelCanvasItem *}’
 get_scaled_icon_size (CajaIconCanvasItem *item,
 ^~~~~~~~~~~~~~~~~~~~
```

And also this one which @raveit65 spotted too.

```
fm-list-model.c: In function ‘fm_list_model_get_icon_scale’:
fm-list-model.c:273:9: warning: ‘gdk_screen_get_monitor_scale_factor’ is deprecated: Use 'gdk_monitor_get_scale_factor' instead [-Wdeprecated-declarations]
         retval = gdk_screen_get_monitor_scale_factor (gdk_screen_get_default (), 0);
         ^~~~~~
In file included from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31:0,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from fm-list-model.h:25,
                 from fm-list-model.c:28:
/usr/include/gtk-3.0/gdk/gdkscreen.h:103:15: note: declared here
 gint          gdk_screen_get_monitor_scale_factor (GdkScreen *screen,
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

# Icons 

I've had a good poke around and found some places where icons are not the correct size, but the icons in the file manager itself are crisply scaled now :smile: 

## Sidebar and Location Bar

As mentioned icons in the side bar and location appear over sized and blurred.

sidebar and location bar

The icons in the Back and Forward drop downs are possibly oversize and blurred.

back and forward dropdowns

## Menus

Some icons in menus are over sized.

go menu

bookmarks menu

## Context Menus

Some icons are over sized in the context menus, these all appear to be icons for extensions. This is present for extension icons in the Desktop context menu too.

context menus

## Media Handling Preferences

Some icons in the Media Handling preferences drop downs are bigger than others. This is the only scaling issue I've found in the Preferences.

media dropdowns

**Comment by raveit65** [comment]
The problem that some icons displays bigger than other ones i noticed also in sidebars.
Also when you go back to scale=1.

**Comment by vkareh** [comment]
ok! that thing was hard, but I'm satisfied: https://github.com/mate-desktop/caja/pull/962/commits/53c888fbda5cfe42c801a354ca3edde8c5bd0a71

@flexiondotorg, @raveit65 - please re-test. I think I've managed to hidpify all icon _except_ emblems, those are tricky :/

One thing, how are you guys compiling this? I'm not getting extensions to load at all...

**Comment by lukefromdc** [comment]
To load extensions, make sure you configure to install into the same prefix your extensions are installed into. Not the first time this has come up.

In my case, all my Debian packages are build with the same options I use to test, for Caja I configure by running
./autogen.sh --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu  --sysconfdir=/etc --enable-shared=yes --disable-maintainer-mode  --disable-schemas-compile 
and I use the same for caja-extensions, so they always load. If you install Caja into /usr/local but your extensions are in /usr they won't load

**Comment by flexiondotorg** [comment]
I'm, unable to apply the diff of this pull request to caja 1.20.1. If I build from this hidpi-scaling branch Caja doesn't start at all.

**Comment by vkareh** [comment]
Hmmm... I can rebase from master just in case. I suspect the issue is with extensions. Even following @lukefromdc's advice I'm not able to get the extensions to show up. I imagine that something I did for the extensions is crashing caja...

**Comment by vkareh** [comment]
Btw, I'm using the same configure arguments that show up in the bionic rules file from apt showsrc for both extensions and caja. I also tried with different prefixes and lib directories and nothing... Not really sure what I'm missing here, everything builds fine, but no extensions show up.
I'll try again tonight :/

**Comment by raveit65** [comment]
With the new commits
caja_0009-list-view-use-the-cairo-surface-as-a-drag-icon.patch
caja_0010-HiDPI-Convert-pixbufs-to-cairo-surfaces.patch
caja_0011-general-use-gdk_monitor_get_scale_factor.patch

caja doesn't start any more in VM and causes a high cpu load.
If i only use * caja_0009-list-view-use-the-cairo-surface-as-a-drag-icon* than caja starts well.
So, **caja_0010-HiDPI-Convert-pixbufs-to-cairo-surfaces** is definitely the first bad commit.
Are the last 2 commits independent from each other and can i use 0011 without 0012 ? 

Btw, I always use 'git rebase master' before i generate the patches with 'git format-patch .....'
So, rebasing with master won't hurt.

**Comment by lukefromdc** [comment]
On thing users can do right now of course is set Caja to zoom icons 200%, and in that case too many png icons will render a bit blurry

**Comment by vkareh** [comment]
@flexiondotorg, @raveit65 - okay, just redid this thing from scratch. I force-pushed to remove old garbage commits.

**Comment by raveit65** [comment]
Much better but...., a little gallery.
caja-bookmarks-menu
The folders in bookmark-menu are blurred.

caja-go-menu
My home folder is blurred in history section of the go-menu, in location section same folder scaled fine.

caja-places-sidebar
Here the eject-buttons have wrong size, after i hovered with the mouse.
And after i switched back to scale=1 the eject-button stays huge for a while, until the next redraw is triggered.

caja-tree-sidebar
After expanding a folder with the GtkExpander sub-folders are to huge
And i am thinking that the icons are blurred in places-, and tree-sidebars
sidebar-increased
After i increase the width of the sidebar i can't make the them smaller again.

In general it is much better as before, great job.....
I saw a few other issues , blurred icons in extensions tab of preferences and emblems tab in 'emblems&backgrounds GUI, but sidebars are more important for the moment.

**Comment by vkareh** [comment]
@raveit65 - hmmm... are we testing the same hash? Of the things you mention, I can only reproduce the sidebar expanding and not being able to shrink it back, and the extensions tab blurred icons. All the other issues should be resolved with my latest hash - keep in mind that I force-pushed it, so it replaces older patches (in case you're still using those)

I'll work on the sidebar expanding too much. I can try to address the extensions tab, but it doesn't look that bad in my system and in my first pass of that code it broke a lot of things, so I might just skip it for now :/

**Comment by raveit65** [comment]
@vkareh 
I did re-create all patches after your last post. Btw. i deleted the branch an pulled them again.
But i can do this again to be sure.
I tested all in a Qemu VM which is running on a Samsung 960 Evo NVMe drive, so i don't think i have performance issues.

As i said , forgot the extensions tab for the moment.

**Comment by raveit65** [comment]
OK, after rebuilding caja most issues are gone.
@flexiondotorg 
Can you test it?
I think we can do a new release and fix the remaining issues later.

**Comment by vkareh** [comment]
@raveit65 - I also fixed the sidebar dimensions. I'll work on dynamic re-scaling notifications on a separate branch as this one is becoming unwieldy.

**Comment by raveit65** [comment]
Cool, resizing sidebar width is working well now with scale=2
Ready to go....
You did really a great job....., thanks for all.

**Comment by raveit65** [comment]
sure, this is for 1.20.
HiDIPI support is very incomplete without it.

**Comment by lukefromdc** [comment]
Rebased and merged with

https://github.com/mate-desktop/caja/commit/35eb4160b389bce690202122f4c5d802e226a0d4
through
https://github.com/mate-desktop/caja/commit/9ea3b711a6a24d4b68231711129982a34938479b

Didn't squash so as to maintain the correlation with the original Nautilus commits from
which these were based, and to make it easier to bisect this if it ever becomes necessary.

**Comment by monsta** [comment]
Hmm, I get a load of runtime warnings in `~/.xsession-errors` while just browsing the folders...

```
(caja:25690): Gtk-CRITICAL **: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(caja:25690): Gtk-CRITICAL **: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(caja:25690): Gdk-CRITICAL **: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(caja:25690): Gdk-CRITICAL **: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(caja:25690): Gdk-CRITICAL **: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(caja:25690): Gdk-CRITICAL **: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(caja:25690): Gtk-CRITICAL **: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(caja:25690): Gtk-CRITICAL **: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(caja:25690): Gdk-CRITICAL **: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(caja:25690): Gdk-CRITICAL **: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
```
...and so on. I don't have any HiDPI hardware, just an old monitor with 1280x1024.

**Comment by lukefromdc** [comment]
Bisecting to find the warnings now...

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/commit/4bf67ac8fff8555bf784d8cd7e1611829a9fca44
"support HiDPI icons" has been identified as first commit in this series in which the warnings appear,
so the problem should be somewhere within it

**Comment by lukefromdc** [comment]
The first warning on starting sudo caja
gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
has been traced to 
gint icon_scale = gtk_widget_get_scale_factor (GTK_WIDGET (button_data->button));
in function 
setup_file_path_mounted_mount (GFile *location, ButtonData *button_data)
in caja-pathbar.c
this problem may be related to 
https://github.com/mate-desktop/caja/issues/903
in that the pathbar is to blame, probably some widget in it not coming up properly. At least this one isn't a segfault. The g_unref warnings are elsewhere, will look for them later as I am out of time

**Comment by lukefromdc** [comment]
first commit to branch to fix this (not ready for PR yet)
https://github.com/mate-desktop/caja/commit/19e7acfc0200b18a19102505bbc819ccde0c944b
also seemed to fix https://github.com/mate-desktop/caja/issues/903 , as I was unable to provoke the segfault on clicking a mounted drive from the desktop, which previously had started happening a lot more. Won't know for sure until I've run it a while though. Now for the rest of the warnings...

**Comment by lukefromdc** [comment]
This test code:

```
    if (details->rendered_surface != NULL)
    {
        if (details->rendered_surface == NULL)
            g_message("freed");
        if (!details->rendered_surface)
            g_message("NULLED");
        if (details->rendered_surface)
            g_message("not freed");
        g_message("nulling out");
        details->rendered_surface = NULL;
        if (details->rendered_surface == NULL)
            g_message("freed");
        if (!details->rendered_surface)
            g_message("NULLED");
        if (details->rendered_surface)
            g_message("not freed");
    }

```
returns

```
** Message: 23:52:21.547: not freed
** Message: 23:52:21.547: nulling out
** Message: 23:52:21.547: freed
** Message: 23:52:21.547: NULLED

```
implying that both the contents of details->rendered_surface and details->rendered_surface itself are gone after details->rendered_surface = NULL so this should be enough. Using g_object_unref 
in the same block returns
```

** Message: 23:54:19.259: not freed
** Message: 23:54:19.259: nulling out

(caja:12829): GLib-GObject-CRITICAL **: 23:54:19.259: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
** Message: 23:54:19.259: not freed

```
Showing that the warnings indicate that details->rendered_surface is not being removed and still holds a non-null value when g_object_unref is used. It worked fine with the former details->rendered_pixbuf but does not work with  details->rendered_surface

**Comment by monsta** [comment]
In another part of file, there's this code block:

```C
    if (details->rendered_surface != NULL)
    {
        cairo_surface_destroy (details->rendered_surface);
        details->rendered_surface = NULL;
    }
```

I guess it's the proper way to free `cairo_surface_t`. It's not a GObject, therefore `G_IS_OBJECT (object)` assertion message appears.

**Comment by monsta** [comment]
Yeah, in other parts of https://github.com/mate-desktop/caja/commit/4bf67ac8fff8555bf784d8cd7e1611829a9fca44 `g_object_unref (details->rendered_pixbuf)` is properly replaced with `cairo_surface_destroy (details->rendered_surface)`. Looks like just an oversight.

**Comment by raveit65** [comment]
Honestly, i can't reproduce those warning with non released caja-1.20.2 from pre-release folder.
Tested in 3 fedora installations.
What did i wrong ?    :)

**Comment by sc0w** [comment]
we have a regression with this PR, the icons are gone here:

bug_icons_caja

culprit commit: 554a036

**Comment by sc0w** [comment]
@mate-desktop/core-team 

seems the commit https://github.com/mate-desktop/caja/commit/554a036710b18d2573810265c69be6e83033af63 give us a lot of warnings, already presents in git master:

```
caja-ui-utilities.c:195:37: warning: passing argument 4 of ‘g_object_set_data_full’ from incompatible pointer type [-Wincompatible-pointer-types]
                                     cairo_surface_destroy);
                                     ^~~~~~~~~~~~~~~~~~~~~

caja-ui-utilities.c:244:37: warning: passing argument 4 of ‘g_object_set_data_full’ from incompatible pointer type [-Wincompatible-pointer-types]
                                     cairo_surface_destroy);
                                     ^~~~~~~~~~~~~~~~~~~~~

fm-directory-view.c:4430:8: warning: passing argument 4 of ‘g_object_set_data_full’ from incompatible pointer type [-Wincompatible-pointer-types]
        cairo_surface_destroy);
        ^~~~~~~~~~~~~~~~~~~~~

fm-directory-view.c:4973:7: warning: passing argument 4 of ‘g_object_set_data_full’ from incompatible pointer type [-Wincompatible-pointer-types]
       cairo_surface_destroy);
       ^~~~~~~~~~~~~~~~~~~~~

fm-directory-view.c:5440:6: warning: passing argument 4 of ‘g_object_set_data_full’ from incompatible pointer type [-Wincompatible-pointer-types]
      cairo_surface_destroy);
      ^~~~~~~~~~~~~~~~~~~~~

fm-directory-view.c:5691:6: warning: passing argument 4 of ‘g_object_set_data_full’ from incompatible pointer type [-Wincompatible-pointer-types]
      cairo_surface_destroy);
      ^~~~~~~~~~~~~~~~~~~~~

caja-window-menus.c:200:29: warning: passing argument 4 of ‘g_object_set_data_full’ from incompatible pointer type [-Wincompatible-pointer-types]
                             cairo_surface_destroy);
                             ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by vkareh** [comment]
@sc0w - #1130

**Pull request closed without merging**
