### PR TITLE
avoid deprecated 'gtk_window_set_wmclass'

### PR DESCRIPTION
**Pull request by sc0w**

### CODE REVIEW

**Comment by raveit65** [comment]
I think `wmclass_class` i used by compiz (plugin window-rule) or devilspie to write a specific rule for application windows.
But you can use `wmclass_name` or other identifier to match a window.
And i can't imagine that someone wants to write a rule for caja-desktop or the dialog windows.
So, this should be save to remove.
Interesting is the hint about the replacement/helper for session-manager https://developer.gnome.org/gtk3/stable/GtkWindow.html#gtk-window-set-wmclass
But i don't think someone wants to restore dialog-windows with session-management with `gtk_window_set_role()`  in this case.

**Comment by raveit65** [comment]
This works like expected, eg. file-properties-dialog use now `wmclass_class= caja`.
From docs:
"According to the ICCCM, you should always set these to the same value for all windows in an application, and GTK+ sets them to that value by default"
Tested with compiz window-rules plugin.
caja-properties-window-window-class

**Comment by raveit65** [comment]
Huston we have a problem!
It seems that this commit causes a caja crash.
```
(caja:16863): Gdk-ERROR **: 19:50:30.740: The program 'caja' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadDrawable (invalid Pixmap or Window parameter)'.
  (Details: serial 8449 error_code 9 request_code 62 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```
Steps to reproduce:
Build caja from master or 1.21.1 + this patches from master.
```
# https://github.com/mate-desktop/caja/pull/989
Patch2:         caja_0001-avoid-deprecated-gtk_style_context_get_background_co.patch
# https://github.com/mate-desktop/caja/commit/5ed053f
Patch3:         caja_0001-libcaja-private-fix-Wlogical-not-parentheses-build-w.patch
# https://github.com/mate-desktop/caja/commit/2392093
Patch4:         caja_0002-replace-deprecated-gdk_flush.patch
# https://github.com/mate-desktop/caja/commit/fc70465
Patch5:         caja_0003-fm-desktop-icon-view-replace-deprecated-gdk_error_tr.patch
# https://github.com/mate-desktop/caja/commit/ded490e
Patch6:         caja_0004-libcaja-private-replace-deprecated-gdk_error_trap-fu.patch
# https://github.com/mate-desktop/caja/commit/ddf6f38
Patch7:         caja_0005-Replace-deprecated-gtk_menu_popup.patch
# https://github.com/mate-desktop/caja/commit/42e5c91
Patch8:         caja_0006-zoom-control-don-t-use-eel_pop_up_context_menu-funct.patch
# https://github.com/mate-desktop/caja/commit/c4777b0
Patch9:         caja_0007-eel-gtk-extensions-replace-deprecated-gtk_menu_popup.patch
# https://github.com/mate-desktop/caja/pull/993
Patch10:        caja_0001-eel-editable-label-avoid-deprecated-gtk_style_contex.patch
# https://github.com/mate-desktop/caja/pull/995
Patch11:        caja_0001-eel-editable-label.c-avoid-deprecated-gdk_keymap_get.patch
# https://github.com/mate-desktop/caja/commit/7cae49a
Patch12:        caja_0001-use-NULL-instead-of-uninitialized-variable.patch
# https://github.com/mate-desktop/caja/commit/13fe58e
Patch13:        caja_0002-remove-unused-function.patch
# https://github.com/mate-desktop/caja/commit/9bf65ee
Patch14:        caja_0003-zoom-control-use-NULL-instead-of-uninitialized-varia.patch
# https://github.com/mate-desktop/caja/commit/9f08546
Patch15:        caja_0004-editable-label-avoid-deprecated-gtk_im_multicontext_.patch
# https://github.com/mate-desktop/caja/commit/c0f159d
Patch16:        caja_0005-Pathbar-button-fix-poor-response-to-right-click.patch
# https://github.com/mate-desktop/caja/pull/994
Patch17:        caja_0001-avoid-deprecated-gtk_dialog_get_action_area.patch
# https://github.com/mate-desktop/caja/commit/eb65d22
Patch18:        caja_0001-icon-container-avoid-deprecated-gtk_style_context_ge.patch
# https://github.com/mate-desktop/caja/commit/a3195d0
Patch19:        caja_0002-caja-bookmark.c-Fix-icons-in-bookmarks.patch
# https://github.com/mate-desktop/caja/commit/cfc9b47
Patch20:        caja_0001-caja-bookmark.c-drop-unused-variable.patch
# https://github.com/mate-desktop/caja/pull/1005
Patch21:        caja_0001-avoid-deprecated-gtk_window_set_wmclass.patch
```
2 . restart session
3. Switch themes with mate-appearance-properties (several times)
4. Caja will crash and restart, and you will find the error message in xsession-errors log.

I tested this with f28 on my notebook and in a f28 VM.
Removing `caja_0001-avoid-deprecated-gtk_window_set_wmclass.patch` from build fixes the issue.
All other mate packages are build from master or 1.21.x releases + patches from master.

@sc0w @lukefromdc @monsta @vkareh 
Can you reproduce this?

**Comment by lukefromdc** [comment]
This is also not the only crash I get in recent weeks

**Comment by vkareh** [comment]
Yep, I just got this:
```bash
(caja:28204): Gdk-ERROR **: 14:42:26.523: The program 'caja' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadDrawable (invalid Pixmap or Window parameter)'.
  (Details: serial 2400 error_code 9 request_code 53 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
./caja.sh: line 12: 28204 Trace/breakpoint trap   (core dumped) ./src/caja
```

This is a fresh compile from master, and a caja restart - happens almost every time

**Comment by lukefromdc** [comment]
Looking back at the code, I see that all this PR did was to remove
gtk_window_set_wmclass () and no code was added. Why would this cause GDK to get bad drawables, indeed how would this affect GDK drawing at all? Is there something in it that is affected by wmclass?

I just reinstalled systemd-coredump(it cannot handle a Kdenlive crash so normally not installed) and I am waiting for the next crash

**Pull request merged**
