### PR TITLE
use git submodule for libegg

### PR DESCRIPTION
**Pull request by yetist**
The code under caja/libegg is merged into the master branch of libegg, so we can use git submodule in caja.

More info about git submodule, please see: https://git-scm.com/book/en/v2/Git-Tools-Submodules

### CODE REVIEW

**Comment by raveit65** [comment]
```
git submodule init
git submodule update
```
is needed to restore libegg files from `https://github.com/mate-desktop/libegg.git`
Then the compiler will run.

**Comment by yetist** [comment]
Please don't merge it before https://github.com/mate-desktop/mate-submodules/pull/2 done.

**Comment by sunweaver** [comment]
Hi,

On  Mi 29 Apr 2020 05:27:12 CEST, Wu Xiaotian wrote:

> The code under caja/libegg is merged into the master branch of  
> libegg, so we can use git submodule in caja.
>
> More info about git submodule, please see:  
> https://git-scm.com/book/en/v2/Git-Tools-Submodules
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/mate-desktop/caja/pull/1380
>

We (Debian, Ubuntu MATE) use Git release tarballs as our upstream orig  
tarballs. Normally, code that is pulled in via git submodules is  
missing in those tarballs.

I'd strongly advise against submodule usage in upstream projects  
unless there are downloadable release tarballs available somewhere  
that contain the complete source code.

Submodules are painful to package maintainers, if only Git repos are  
available for downloading release tarballs.

Thanks+Greets,
Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler Str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4351) 850 8940

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by raveit65** [comment]
What exactly are you doing with `Git release tarballs`?
Commands?
You should use ``git submodule init && git submodule` before using the tarball.
`git submodule init && git submodule update && autogen.sh && make && make distcheck`
and everything is in the tarball.
@yetist 
I think we need to do this when creating tarballs with travis CI

**Comment by raveit65** [comment]
> I'd strongly advise against submodule usage in upstream projects
unless there are downloadable release tarballs available somewhere
that contain the complete source code.

You can download tarball from https://pub.mate-desktop.org/releases, since years....
Or from github release page from a repo.

**Comment by raveit65** [comment]
You only needs to update `rules` file of your package build!
https://github.com/mate-desktop/debian-packages/blob/master/caja/debian/rules#L21
Change
```
override_dh_auto_configure:
	# upstream tarball is without configure. autogen.sh will create it
	NOCONFIGURE=1 ./autogen.sh
	dh_auto_configure $(DHFLAGS) -- \
		--disable-silent-rules \
		--libexecdir=/usr/lib/caja \
		--includedir=/usr/include/$(dpkg-architecture -qDEB_BUILD_MULTIARCH) \
		--disable-update-mimedb \
		--disable-static \
		--localstatedir=/var \
		--enable-introspection \
		--enable-gtk-doc
```
to
```
override_dh_auto_configure:
	# upstream tarball is without configure. autogen.sh will create it
        git submodule init
        git submodule update
	NOCONFIGURE=1 ./autogen.sh
	dh_auto_configure $(DHFLAGS) -- \
		--disable-silent-rules \
		--libexecdir=/usr/lib/caja \
		--includedir=/usr/include/$(dpkg-architecture -qDEB_BUILD_MULTIARCH) \
		--disable-update-mimedb \
		--disable-static \
		--localstatedir=/var \
		--enable-introspection \
		--enable-gtk-doc
```
Of course `git` needs to be installed in your buildroot.

**Comment by raveit65** [comment]
```
[rave@mother caja]$ LANG=C
[rave@mother caja]$ git branch 
  1.22
  1.24
  address
* master
  plonibarploni-patch-1
  prescott66-patch-1
  trashed-on-date
[rave@mother caja]$ git checkout git-submodule 
Branch 'git-submodule' set up to track remote branch 'git-submodule' from 'origin'.
Switched to a new branch 'git-submodule'
[rave@mother caja]$ ls
AUTHORS             ChangeLog        NEWS        configure.ac  git.mk     libcaja-extension  po
COPYING             HACKING          README      data          gla11y.mk  libcaja-private    src
COPYING.EXTENSIONS  Makefile.am      autogen.sh  docs          icons      makepot            test
COPYING.LIB         Makefile.shared  caja.pot    eel           its        mate-submodules    update-authors.pl
[rave@mother caja]$ 
@yetist 
Why is there a new dir called `mate-submodules` ?

**Comment by sunweaver** [comment]
On  Mo 11 Mai 2020 16:39:14 CEST, raveit65 wrote:

>> I'd strongly advise against submodule usage in upstream projects

> unless there are downloadable release tarballs available somewhere
> that contain the complete source code.
>
> You can download tarball from https://pub.mate-desktop.org/releases,  
> since years....

Ah, ok. I wasn't aware of that. That could be a workaround.

> Or from github release page from a repo.

We (Debian/Ubuntu) obtain Git release tarballs from  
https://git.mate-desktop.org/ and those tarballs won't contain git  
submodule pulled-in code subprojects.

As those tarballs are in a state where autogen.sh has not been run  
prior to packaging the tarball, they are my preferred (more pristine)  
upstream tarballs.

Mike

-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler Str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4351) 850 8940

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by sunweaver** [comment]
Hi Wolfgang,

On  Mo 11 Mai 2020 19:13:05 CEST, raveit65 wrote:

> You only needs to update `rules` file of your package build!
> https://github.com/mate-desktop/debian-packages/blob/master/caja/debian/rules#L21
> Change
> ```
> override_dh_auto_configure:
> 	# upstream tarball is without configure. autogen.sh will create it
> 	NOCONFIGURE=1 ./autogen.sh
> 	dh_auto_configure $(DHFLAGS) -- \
> 		--disable-silent-rules \
> 		--libexecdir=/usr/lib/caja \
> 		--includedir=/usr/include/$(dpkg-architecture -qDEB_BUILD_MULTIARCH) \
> 		--disable-update-mimedb \
> 		--disable-static \
> 		--localstatedir=/var \
> 		--enable-introspection \
> 		--enable-gtk-doc
> ```
> to
> ```
> override_dh_auto_configure:
> 	# upstream tarball is without configure. autogen.sh will create it
>         git submodule init
>         git submodule update
> 	NOCONFIGURE=1 ./autogen.sh
> 	dh_auto_configure $(DHFLAGS) -- \
> 		--disable-silent-rules \
> 		--libexecdir=/usr/lib/caja \
> 		--includedir=/usr/include/$(dpkg-architecture -qDEB_BUILD_MULTIARCH) \
> 		--disable-update-mimedb \
> 		--disable-static \
> 		--localstatedir=/var \
> 		--enable-introspection \
> 		--enable-gtk-doc
> ```
> Of course `git` needs to be installed in your buildroot.

this won't work in Debian packaging. First, because of the Git repo of  
the Debian project does not contain any upstream code, only the  
debian/ folder. Secondly, because in Debian packages (built on Debian  
infrastructure), I cannot use Git as all .git folders get stripped off  
of the source package and during builds I don't have internet access  
(so, git submodule update would fail).

Is libegg statically linked into caja? Wouldn't it be much more  
generic to make libegg a proper shared library (maybe as libmate-egg)?

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler Str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4351) 850 8940

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by raveit65** [comment]
Please show me your `rules` and `control` file of you Debian package?
I sure you are downloading the sources from `https://github.com/mate-desktop/caja.git`, right?
And i am sure that debian build system is connected to the internet, right?
So , you only need to updated the build sources with `git submodule init && git submodule update` before calling `autogen.sh`.

In fedora build system (koji) all those are simple tasks an can be done easily :P

Any way, we will update our tarball to include this code, so you don't need to think about to update your scripts.

**Comment by raveit65** [comment]
Ok, i guess the new folder `mate-submodules` is the result or renaming the repo `libegg` to `mate-submodules/libegg`, should be Ok.
I tested the PR again and `git submodule init && git submodule update && ./autogen.sh && make && make distcheck` is working fine. All libegg files are in generated tarball.

@yetist 
So we only need to find a way to include the `mate-submodules/libegg` folder when creating tarballs with travis.
Than all distos can be use ready-to-compile tarballs from `https://pub.mate-desktop.org/releases` or `https://github.com/mate-desktop/caja/releases`, which are the same.

If someone like to built from `https://github.com/mate-desktop/caja.git` or our back-up git server `https://github.com/mate-desktop/caja.git`, than those 2 steps are needed after cloning from our git repos before starting package building.
`git submodule init && git submodule update`

**Comment by raveit65** [comment]
Indeed, `https://git.mate-desktop.org/caja/tree/` doesn't have a `.git/` folder.
So, downloading the source from our git server is ***strongly obsolete***.
Please clone from `https://github.com/mate-desktop/caja.git` than you will have a .`git/` folder in your buildroot.

**Comment by sc0w** [comment]
maybe is good to add the steps (`git submodule init && git submodule update`) to `README` file

**Comment by sc0w** [comment]
@raveit65 

> Indeed, https://git.mate-desktop.org/caja/tree/ doesn't have a .git/ folder.

seems it is hidden at website, I did `git clone` manually, and `.git` folder is there

**Comment by raveit65** [comment]
Ok, good,
....than i don't understand why git command can't be used at debian build server.

Any way, i took a look at travis build logs and it is clear that new tarball will be generated by travis with all needed files.
mate-submodules are loaded into buildroot here:
https://travis-ci.org/github/mate-desktop/caja/jobs/685510578#L135
```
$ git clone --depth=50 https://github.com/mate-desktop/caja.git mate-desktop/caja

Cloning into 'mate-desktop/caja'...

$ cd mate-desktop/caja

0.40s$ git fetch origin +refs/pull/1380/merge:

From https://github.com/mate-desktop/caja

 * branch            refs/pull/1380/merge -> FETCH_HEAD

$ git checkout -qf FETCH_HEAD

git.submodule

0.51s$ git submodule update --init --recursive

Submodule 'mate-submodules' (https://github.com/mate-desktop/mate-submodules.git) registered for path 'mate-submodules'

Cloning into '/home/travis/build/mate-desktop/caja/mate-submodules'...

Submodule path 'mate-submodules': checked out '88b91f59f268e8188fec2f5187431ad7b360e8c4'
```
And finally distcheck runs successfully and creates a tarball with all files here:
https://travis-ci.org/github/mate-desktop/caja/jobs/685510578#L6557
```
=============================================

caja-1.24.0 archives ready for distribution: 

caja-1.24.0.tar.xz

=============================================

+ '[' 0 -eq 0 -a -d /rootdir ']'

+ chown -R 2000 /rootdir

The command "./docker-build --name ${DISTRO} --verbose --config .build.yml --build scripts" exited with 0.

after_success

0.48s$ if [[ "$TRAVIS_SECURE_ENV_VARS" == "true" && "$TRAVIS_PULL_REQUEST" != "false" && ${DISTRO} =~ ^fedora.*$ ]]; then REPO_SLUG_ARRAY=(${TRAVIS_REPO_SLUG//\// }); REPO_NAME=${REPO_SLUG_ARRAY[1]}; URL="https://${REPO_NAME}.mate-desktop.dev"; COMMENT="Code analysis completed"; curl -H "Authorization: token $GITHUB_TOKEN" -X POST -d "{\"state\": \"success\", \"description\": \"$COMMENT\", \"context\":\"scan-build\", \"target_url\": \"$URL\"}" https://api.github.com/repos/${TRAVIS_REPO_SLUG}/statuses/${TRAVIS_PULL_REQUEST_SHA}; fi

Skipping a deployment with the pages provider because the current build is a pull request.

Skipping a deployment with the script provider because the current build is a pull request.

Done. Your build exited with 0.
```
When commit has a release tag than a new tarball will deployedand can be download at.
https://pub.mate-desktop.org/releases or https://github.com/mate-desktop/caja/releases
So all is fine.

**Comment by raveit65** [comment]
> I think you can squash all the commits into one

@sc0w 
We can do that with the  `squash and merge` button

> maybe is good to add the steps (git submodule init && git submodule update) to README file

@yetist 
Can you please add this info to README?

**Comment by lukefromdc** [comment]
Session saving works fine too with this

**Comment by yetist** [comment]
> @yetist
> Can you please add this info to README?

Please see #1388

**Pull request merged**
