### PR TITLE
caja-bookmarks-window.ui: remove deprecated GtkAlignment, remove empt…

### PR DESCRIPTION
**Pull request by mbkma**
…y labels

caja-file-management-properties.ui: remove deprecated GtkAlignment (use
margin-property instead), reduce default size (at the moment it is unnecessarily large)

... and do not indent the Defaults GtkNotebook nor the list column:

Screenshot at 2021-04-24 12-46-10
Screenshot at 2021-04-24 12-45-59

### CODE REVIEW

**Review by rbuj — CHANGES_REQUESTED** [review]
The commit title doesn't match the changes you made. It only contains one file, while you have edited two ui files. The title of the commits helps to keep track of the changes made.

**Review by raveit65 — APPROVED** [review]
LGTM,
builds and runs fine.

**Comment by mbkma** [comment]
@rbuj done :)

**Review by lukefromdc — COMMENTED** [review]
I didn't get time to review this before it was merged, but found a problem: scrollbars in the bookmarks window can be used by using the mouse scrollwheel over them, but the scrolled window is undersize (even if the dialog window is resized taller) and the scrollbar slider fills the scrollbar so it cannot be dragged with the mouse.

**Comment by mbkma** [comment]
@lukefromdc thanks for testing! A fix is coming...

**Comment by mbkma** [comment]
see #1524

**Pull request merged**
