### PR TITLE
fix fg-color of dark themes

### PR DESCRIPTION
**Pull request by raveit65**
fixes https://github.com/mate-desktop/caja/issues/81

### CODE REVIEW

**Comment by raveit65** [comment]
@monsta @bl0ckeduser 
please test, in my test this does not break previous fixes for
https://github.com/mate-desktop/caja/issues/438
https://github.com/mate-desktop/caja/issues/105

**Comment by bl0ckeduser** [comment]
No regressions for me with the foregoing patch

**Comment by monsta** [comment]
Thanks, I don't see https://github.com/mate-desktop/caja/issues/81 anymore here :smile:

But I see it reverts the change from https://github.com/mate-desktop/caja/pull/495 - hope it's ok.

**Comment by raveit65** [comment]
As i said this fixes all 3 issues for me.

**Comment by monsta** [comment]
Ok good, can be merged in both master and 1.12 then :smile:

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/caja/commit/1ff346876afd37a957aa490be25bdd2fd90e4773

**Comment by monsta** [comment]
Well there's a regression after all... When using custom background color (you can set it via Emblems & Background dialog), font color isn't changed. E.g. if I select dark bg color and font of my GTK+ theme is black, it will remain black (and thus unreadable).

Tested in GTK+2 build.

@bl0ckeduser: can anything be done about that?

**Comment by bl0ckeduser** [comment]
It is a quite complex issue. It seems eel_background_is_set and eel_background_is_dark routines are not functioning properly and returning bogus values on repeated calls. It might be a bug in mate-desktop, or in both. It would need some pretty detailed debugging to track down

**Comment by bl0ckeduser** [comment]
I am investigating some more. When the bug happens, for some reason update_label_color() fails to be called whereas in previous instances it is called succesfully. Before the call, eel_background_is_dark returns false which leads to incorrect theming while after the call it returns true.

**Comment by monsta** [comment]
Hmm... but I can reproduce it every time. No matter which background color I choose, the font stays black.

**Comment by raveit65** [comment]
@bl0ckeduser 
any chance that you find a fix before 1.14 release end of march?

**Comment by bl0ckeduser** [comment]
I don't think, sorry

**Comment by monsta** [comment]
@alexandervdm: maybe you know what could cause the problem? See my description above. And if we'll revert https://github.com/mate-desktop/caja/commit/1ff346876afd37a957aa490be25bdd2fd90e4773 (which fixes the issue), we'll get https://github.com/mate-desktop/caja/issues/81 back, which isn't nice as well.

**Comment by monsta** [comment]
Ok, now fixed with https://github.com/mate-desktop/caja/pull/526.

**Pull request closed without merging**
