### PR TITLE
Fix infinite restarting with mate-session 1.24.0

### PR DESCRIPTION
**Pull request by yledoare**

### CODE REVIEW

**Comment by yledoare** [comment]
To fix this issue : https://github.com/mate-desktop/caja/issues/100

**Comment by raveit65** [comment]
I do not agree, with disabling auto restart of caja.
If the process stoped it should be restarted, otherwise you lost desktop icons.
You should find out why caja failed to start with session and not work around the problem.
All major distros with Mate desktop  doesn't have this problem.

**Comment by yledoare** [comment]
It seems that this bug is also into Ubuntu 20.04 nightly
There was no problem with Mate 1.22
Who to find out why caja is always restarting by mate-session ?

**Comment by sc0w** [comment]
@yledoare you can do git bisect to find the culprit commit:

https://git-scm.com/docs/git-bisect

**Comment by raveit65** [comment]
I don't think the issue is in ubuntu when one user did report it.
A lot of people use Mate with ubuntu. Believe me, people would bomb us with reports when this is a general problem.

> Who to find out why caja is always restarting by mate-session ?

You never gave info how do you use Mate, distro, self compiled, systemd, etc.?
How should we help?
But , anything useful in logs?

**Comment by lukefromdc** [comment]
Sounds to me like you've got caja crashing when your system starts, and again when it restarts. Also check in dconf-editor to make sure you don't have both org>mate>caja>preferences>exit-with-last-window set to TRUE and org>mate>desktop>background>show-desktop-icons set to FALSE, a combination which at least used to do this in the past and for which no easy fix existed as this would be the expected behavior with telling caja to start with the session, not draw any windows, and restart on closing

**Comment by yledoare** [comment]
> I don't think the issue is in ubuntu when one user did report it.
> A lot of people use Mate with ubuntu. Believe me, people would bomb us with reports when this is a general problem.
> 
> > Who to find out why caja is always restarting by mate-session ?
> 
> You never gave info how do you use Mate.?
> Distro, self compiled, systemd, etc.?
> How do you start mate session?
> Login manager?
> How should we help you without informations?
> But , anything useful in logs?

My distro is self compiled, and works without systemd (init from busybox) 
for the current release (mate 1.22), there was no problem , the complete list of packages is available here : https://bitbucket.org/yourdistrofromscratch/ydfs/src/master/2.7/packages/list-x86
The next release, with mate 1.24 has those packages : https://bitbucket.org/yourdistrofromscratch/ydfs/raw/46090263a70fbd70a672df20412a75e396414b40/2.8/packages/list-x86 

Here is a capture of started processes, with mate 1.22, that runs fine without this patch, 
I run caja --force-desktop -n, then mate-session, that runs also caja (why ?) 

 1552 ?        Sl     0:19 caja --force-desktop -n
 1569 ?        Sl     0:00 /home/linuxconsole2019/x86_64/libexec/dconf-service
 1575 ?        S      0:00 ck-launch-session dbus-launch mate-session
 1578 ?        S<     0:00 [krfcommd]
 1581 ?        Sl     0:00 mate-session
 1585 ?        Ss     0:00 /home/linuxconsole2019/x86_64/bin/dbus-daemon --syslo
 1593 ?        Sl     0:00 /home/linuxconsole2019/x86_64/libexec/dconf-service
 1604 ?        Sl     0:00 /home/linuxconsole2019/x86_64/libexec/mate-settings-d
 1614 ?        Sl     0:00 /home/linuxconsole2019/x86_64/libexec/gvfsd
 1621 ?        Sl     0:00 /home/linuxconsole2019/x86_64/libexec/gvfsd-fuse /hom
 1638 ?        Sl     0:03 mate-panel
 1648 ?        Sl     0:00 /home/linuxconsole2019/x86_64/libexec/gvfs-udisks2-vo
 1653 ?        Sl     0:00 /home/linuxconsole2019/x86_64/libexec/udisks2/udisksd
 1658 ?        Sl     0:00 caja

**Comment by raveit65** [comment]
Maybe consolekit is broken?

**Comment by yledoare** [comment]
Maybe this is a bug from mate-session, here is a capture of looping (Re-starting app: /org/gnome/SessionManager/App32) 

mate-session[25272]: DEBUG(+): GsmManager: restarting app
mate-session[25272]: DEBUG(+): Re-starting app: /org/gnome/SessionManager/App32
mate-session[25272]: DEBUG(+): GsmAutostartApp: sending signal 15 to process 25336
mate-session[25272]: DEBUG(+): Starting app: /org/gnome/SessionManager/App32
mate-session[25272]: DEBUG(+): GsmAutostartApp: starting caja.desktop: command=/home/linuxconsole2020/x86_64/bin/caja startup-id=1046101e0366bd2a9a159204112881053900000252720031
mate-session[25272]: GLib-DEBUG(+): posix_spawn avoided (fd close requested)
mate-session[25272]: DEBUG(+): GsmAutostartApp: started pid:25398
mate-session[25272]: DEBUG(+): GsmStore: Unreffing object: 0x55ddfa5a7b00
mate-session[25272]: DEBUG(+): GsmClient: disposing /org/gnome/SessionManager/Client5
mate-session[25272]: DEBUG(+): GsmStore: emitting removed for /org/gnome/SessionManager/Client5
mate-session[25272]: DEBUG(+): GsmManager: Client removed: /org/gnome/SessionManager/Client5
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
mate-session[25272]: DEBUG(+): GsmAutostartApp: (pid:25336) done (signal:15)
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/gnome/SessionManager interface=org.gnome.SessionManager method=RegisterClient
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/gnome/SessionManager interface=org.gnome.SessionManager method=RegisterClient
mate-session[25272]: DEBUG(+): GsmManager: RegisterClient 1046101e0366bd2a9a159204112881053900000252720031
mate-session[25272]: DEBUG(+): GsmManager: Adding new client 1046101e0366bd2a9a159204112881053900000252720031 to session
mate-session[25272]: DEBUG(+): uid = 0
mate-session[25272]: DEBUG(+): pid = 25402
mate-session[25272]: DEBUG(+): GsmStore: Adding object id /org/gnome/SessionManager/Client7 to store
mate-session[25272]: DEBUG(+): GsmManager: Client added: /org/gnome/SessionManager/Client7
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/gnome/SessionManager/Client7 interface=org.freedesktop.DBus.Properties method=GetAll
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/gnome/SessionManager/Client7 interface=org.freedesktop.DBus.Properties method=GetAll
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/gnome/SessionManager/Client7 interface=org.freedesktop.DBus.Properties method=GetAll
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
mate-session[25272]: DEBUG(+): GsmDBusClient: obj_path=/org/freedesktop/DBus interface=org.freedesktop.DBus method=NameOwnerChanged
mate-session[25272]: DEBUG(+): GsmManager: disconnect client: /org/gnome/SessionManager/Client7
mate-session[25272]: DEBUG(+): GsmManager: restarting app
mate-session[25272]: DEBUG(+): Re-starting app: /org/gnome/SessionManager/App32
mate-session[25272]: DEBUG(+): GsmAutostartApp: Couldn't stop app: Not running

**Comment by raveit65** [comment]
You're way to start MATE session is very uncommon and not supported any more by MATE since a long time.
If you really like to do unsupported things than please replace `consolekit` with `ELOGIND`.
See https://github.com/mate-desktop/mate-session-manager/commit/51f12ece0dcb77f08462ca1ae27a0a571f3b338e and https://github.com/mate-desktop/mate-session-manager/pull/199 or https://github.com/mate-desktop/mate-session-manager/issues/146 for more info.

**Comment by raveit65** [comment]
And please quote logs in postings to avoid linking other reports when posting numbers.

**Comment by yledoare** [comment]
Your are right, elogind shoud remplace consolekit , https://www.gentoo.org/support/news-items/2020-04-14-elogind-default.html 

I am currently starting the mate-session with
`ck-launch-session dbus-launch mate-session`
like documented here : https://wiki.gentoo.org/wiki/MATE

I want also to understand why mate-session starts caja, then kill it with signal 15, and restarts it

**Comment by raveit65** [comment]
Try to add a delay to caja desktop file.
`X-MATE-Autostart-Delay=NN`
NN are in seconds.

**Pull request closed without merging**
