### PR TITLE
editable-label: Don't hyphenate filenames

### PR DESCRIPTION
**Pull request by raveit65**
more fixes for https://github.com/mate-desktop/caja/issues/1284

Renaming a file can make you crazy without this.
Please test.

### CODE REVIEW

**Comment by raveit65** [comment]
@yetist 
Looks like `xorgproto` isn't in default installation any more for ArchLinux.
I guess this will break building for most repos, or is this a package dependency issue by ArchLinux?
https://travis-ci.org/mate-desktop/caja/jobs/628108244#L878

**Comment by raveit65** [comment]
> why the seemingly unrelated Travis change? Is it needed for evaluating the results of this change?

Yes.

> Was this caused by the first commit, since presumably builds on master completed?

No, first commit is fine in general, and is unrelated to archlinux build failure which happens on master too.

**Comment by lukefromdc** [comment]
No sweat: if combining these is OK w you it is OK with me.

**Comment by yetist** [comment]
Archlinux is doing the Xorg cleanup, so we need add `xorgproto` to the `.travis.yml` file.

https://www.archlinux.org/news/xorg-cleanup-requires-manual-intervention/
https://bugs.archlinux.org/task/64892

**Comment by raveit65** [comment]
@yetist 
Seems that was only temporarily needed, build for 1.22 runs fine without adding `xorgproto` to `.travis.yml` file.
https://travis-ci.org/mate-desktop/caja/builds/628661277?utm_source=github_status&utm_medium=notification

**Pull request merged**
