### PR TITLE
fix gfile sort and symlink warnings w glib 2.76 or later

### PR DESCRIPTION
**Pull request by lukefromdc**
*Use code borrowed from Nemo

### CODE REVIEW

**Comment by lukefromdc** [comment]
Fix
https://github.com/mate-desktop/caja/issues/1740
`
caja --check` finishes clean with this applied over glib2.76 or later (Debian Sid is shipping 2.77.1 at this moment)

**Review by raveit65 — APPROVED** [review]
LGTM,
debian build in travis-ci is working again.

**Comment by lukefromdc** [comment]
We may want to redo the caja release (to 1.27.2)  to include this due to all the log spam the gfile issue creates

**Comment by raveit65** [comment]
Sure i can do, but in which (runtime) logs do caja spam without this commit?

**Comment by raveit65** [comment]
Ok, got it, 1.27.1 can't be build on debian:testings systems.

**Comment by lukefromdc** [comment]
A normal build of 1.27.1 on my end w my default build options will finish and will run, but when run from terminal you will see more than a full terminal screen's worth of warnings. After this commit those are gone

**Pull request merged**
