### PR TITLE
avoid deprecated 'gtk_widget_override_font'

### PR DESCRIPTION
**Pull request by sc0w**
I just removed related code, I don't see differences

### CODE REVIEW

**Comment by lukefromdc** [comment]
With this PR:
info_sidebar_pr
With current master:
info_sidebar_master

**Comment by raveit65** [comment]
I think we should follow gtk+ suggestions?
https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-override-font
```
gtk_widget_override_font has been deprecated since version 3.16 and should not be used in newly-written code.
This function is not useful in the context of CSS-based rendering. If you wish to change the font a widget uses to render its text you should use a custom CSS style, through an application-specific GtkStyleProvider and a CSS style class.
```

**Comment by sc0w** [comment]
@lukefromdc @raveit65 please test/review again :)

**Comment by lukefromdc** [comment]
Rebased on master as of now for clean merge

**Comment by sc0w** [comment]
Regression: press F9 several times and see:

bug_broken_image

**Pull request merged**
