### PR TITLE
added rubberband select to list view mode

### PR DESCRIPTION
**Pull request by dsproch**
In "List View" mode, allows the user to perform rubber band selection by starting selection anywhere except the name column of a row.

### CODE REVIEW

**Comment by lukefromdc** [comment]
What should we do with this? It needs to be finished (cork the memory leaks as I suggested, and fix the build warning) but is a very nice feature addition. I don't want this to be forgotten

**Comment by raveit65** [comment]
No idea why authors of PRs don't answer any more, or why they think that we can merge PRs with memleaks.
If you know how to fix the leaks open a new fixed PR and close this one.
@dsproch 
Are you alive?

**Comment by lukefromdc** [comment]
OK, I will do that when I get some time, the memory leak fix is quick and easy to merge into a new PR but I also need to fix the build warning

**Comment by lukefromdc** [comment]
On further testing I discovered that two of the three suspected memory leaks were NOT:
1: freeing path_copy causes a crash on clicking any item, so this must be a pointer to existing data 2: freeing cell_renderers causes a crash on clicking any item,, so this must be a pointer to existing data 

Variable l however (which is inside the loop)  could be freed without crashing anything I could find, so that probably was indeed a memory leak. I also found a fix for the build warning.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/pull/1070
fixes the build warning and corks up one possible memory leak. The other two were false alarms

**Pull request closed without merging**
