### PR TITLE
Bump required version of mate-desktop since pixbuf helper was removed

### LINKED ISSUE #1343: Caja cannot be built against mate-desktop 1.23.3 ; error in fm-properties-windows.c
#### Expected behaviour

Caja building

#### Actual behaviour

Caja is broken while processing fm-properties-windows.c. There is a missing reference to mate_desktop_thumbnails_scale_down_pixbuf

Seems to be related to this commit: https://github.com/mate-desktop/mate-desktop/commit/2bce55bfb71a354402499b497f42d0fe6851350b

#### Steps to reproduce the behaviour

Try to build caja with Mate-Desktop 1.23.3.

#### MATE general version

1.23.3

#### Package version

1.23.2

#### Linux Distribution

Archlinux

#### Link to downstream report of your Distribution

Not done.

Here is a screenshot of the bug:

VirtualBox_Arch Mate 1 23_19_01_2020_17_31_51

### PR DESCRIPTION
**Pull request by rbuj**
See https://github.com/mate-desktop/mate-desktop/commit/8f6e3df4ce1b570a9f71ed0383427b85b4378144
Closes #1343

### CODE REVIEW

**Comment by rbuj** [comment]
All references to `gdk_pixbuf_scale_simple` were removed from caja in https://github.com/mate-desktop/caja/commit/13d04135dda574bbaa51f56df1783778f423e0f2

**Comment by raveit65** [comment]
@rbuj 
I will bump required mate-desktop version in caja and make a new release of caja.

**Comment by raveit65** [comment]
No, i was wrong. We don't need to bump required mate-desktop version here.
The issue is that older caja version can't build against mate-desktop-1.23.3.
That means we need to release a new caja version first and bump required caja version in mate-desktop.
But for the mate-desktop-1.23.3 we are to late for this.
Any way, we need this for upcoming 1.24 release.

**Comment by rbuj** [comment]
@raveit65 
You don't need to bump the required version of mate-desktop to the latest development version in caja. For instance, you can build caja using the latest stable version of mate-desktop without any problem after https://github.com/mate-desktop/caja/commit/13d04135dda574bbaa51f56df1783778f423e0f2. This will avoid headaches on CI builds.

Test:
```shell
$ sudo dnf reinstall -y mate-desktop && ./autogen.sh --prefix=/usr && make && sudo make install
$ rpm -qi mate-desktop | grep Version
Version     : 1.22.2
```

**Comment by raveit65** [comment]
@rbuj 
This is exactly what i said before at https://github.com/mate-desktop/caja/pull/1344#issuecomment-576030477  :wink: 
The issue is that you can't build caja <= 1.23.2 against mate-desktop-1.23.3
So, caja version needs to bump in mate-desktop
But than we need to build caja from git for travis build of mate-desktop.
I am not sure if i want to do this.

**Pull request closed without merging**
