### PR TITLE
Avoid deprecated gdk_cairo_create (rebased again)

### PR DESCRIPTION
**Pull request by lukefromdc**
This is a rebase of
https://github.com/mate-desktop/caja/pull/574
against mate-desktop/master (release 1.15.1) current as of Sat Jul3  6 PM EDT after dev-style-context was merged

gdk_cairo_create is deprecated in GTK 3.21 as of the troublesome commit
https://git.gnome.org/browse/gtk+/commit/?id=ad78daaf8081d8ea72006832ee3dd5df2e1ed3f9

Replace it with cairo_create, no adverse effects observed in tests with compiz or
Marco, with or without compositing.

This removes one more deprecated command in Caja, though it was not enough to fix the redraw issue in Caja with the newest GTK 3.21 master code. GTK development is crawling right not, not sure if they will keep those changes or not with so many issues. On the other hand, no issues I could find were created by replacing gdk_cairo_create, at least not in slightly older or in current GTK 3.21. Even if GTK rolls back their latest changes, using cairo_create() directly decouples this from future Gtk/Gdk changes to some extent.

No idea what this would do in GTK2.  If this does not work in GTK2, each replacement of gdk_cairo_create with cairo_create could be put behind a GTK3 selector but from what I am hearing caja 1.16 is intended to be GTK3 only so I just did a simple find-replace in Pluma on each file.

### CODE REVIEW

**Comment by XRevan86** [comment]
```c
cairo_t *cairo_create(cairo_surface_t *target);
cairo_t *gdk_cairo_create(GdkWindow *window);
```
You can't possibly replace one with another without consequences (GdkWindow is not a cairo surface).
And commit description doesn't even suggest that.

**Comment by lukefromdc** [comment]
What do you suggest doing? I did exactly that and Caja with this has been running
without any problems I can find for two weeks.
I don't know of any other fix for this. If this creates problems or is just bad code,
we can close this one and leave it for someone else to find a solution for this.

I first tried this hoping it was the issue behind the failure to redraw the desktop
with GTK 3.21.3
https://github.com/mate-desktop/caja/issues/575
but no such luck. No new issues but didn't help either. I submitted the PR because
this is one less deprecated command but if it creates problems, build warnings,
or runtime warnings feel free to close it.

**Comment by XRevan86** [comment]
I'm not sure (didn't test it) but I think this is how gdk_cairo_create() supposed to be replaced:
```c
cairo_region_t *region = gdk_window_get_clip_region(window);
GdkDrawingContext *context = gdk_window_begin_draw_frame(window, region);
cr = gdk_drawing_context_get_cairo_context(context);
<..>
gdk_window_end_draw_frame(window, context);
```

**Comment by lukefromdc** [comment]
I won't be able to properly play with that until tomorrow night
but will see if I can get that working. Wonder if what I'm using
now works because of some corner case or undocumented 
feature which should never be used?

**Comment by lukefromdc** [comment]
OK, I just found out what's going on: It turns out Caja only uses gdk_cairo_create
in GTK2 already! Every single instance was behind GTK2 only selectors, in some
cases very widely separated and away from the code in question. Also, some of 
the commenting wasn't very good, with this format used in worst cases:

#if GTK_CHECK_VERSION(3,0,0)
#else /* GTK_CHECK_VERSION(3,0,0) */
#endif /* GTK_CHECK_VERSION(3,0,0) */

I will now close this PR as it has no effect on the code built in GTK3 and probably
has no effect at all but to break GTK2 builds.

**Comment by lukefromdc** [comment]
Closing this as it does not change code actually built with GTK3, presumably breaks GTK2 builds.

**Pull request closed without merging**
