### PR TITLE
image properties: Support webp & svg, check most common mime-types first

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by mbkma** [comment]
How to test this?

**Comment by rbuj** [comment]
@mbkma There is another approach, checking whether the mime type is supported by the loader at runtime. https://github.com/mate-desktop/caja/commit/a15c4e1b75bb70931c9ad1315806be28e84eb85b based on https://github.com/GNOME/nautilus/commit/7aef6beb47bf5bb212d4cd59089ff410b863170e

**Comment by mbkma** [comment]
yeah, that looks like the proper way to do it

**Comment by rbuj** [comment]
Ok #1661

**Pull request closed without merging**
