### PR TITLE
Caja zoom in list view is broken

### LINKED ISSUE #790: Caja zoom in list view is broken [$30]
Downstream bug report for Ubuntu MATE 17.04

https://bugs.launchpad.net/ubuntu/+source/caja/+bug/1680604

I've reproduced on Caja 1.18.2 and 1.18.3

<bountysource-plugin>

---
There is a **[$30 open bounty](https://www.bountysource.com/issues/45835489-caja-zoom-in-list-view-is-broken?utm_campaign=plugin&utm_content=tracker%2F651521&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F651521&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by snaiperskaya96**
Fixes #790 

Hello, it's me again.
```
git clone https://github.com/snaiperskaya96/caja.git
git checkout caja-zoom-in-list-view-is-broken
...
```
or if you don't want to clone another repository 
```
git remote add snaiperskaya https://github.com/snaiperskaya96/caja.git
git fetch snaiperskaya
git checkout snaiperskaya/caja-zoom-in-list-view-is-broken
```

### CODE REVIEW

**Comment by raveit65** [comment]
Up-zooming works great with your PR in list-view, but after down-zooming the list-viev looks weird.
Don't know how did that works before with gtk2 as i don't use list-view normal.
caja-list-view
I tested this with several gtk+ themes (include adwaita) to be sure it's not a theming issue.
Switching to another theme or to another folder and back fixes the list-view.

**Comment by snaiperskaya96** [comment]
Thanks for your tests! It must have to do with the columns width. Gonna have a look

**Comment by snaiperskaya96** [comment]
@raveit65 If you have a second test it again please :)

**Comment by raveit65** [comment]
Issue with columns is fixed.

**Comment by raveit65** [comment]
merged
841f54b9acecfd1b2696b91eb41fb6b212bf76e3
https://github.com/mate-desktop/caja/commit/0b1ffa6ff494e4a50053b283707c1b8b4f486129
https://github.com/mate-desktop/caja/commit/2a424fca8bd928223e92570fa692266c471a52b3
Thanks, you should claim the bounty....

**Comment by monsta** [comment]
Thanks, the issue is fixed. However, after 2a424fca8bd928223e92570fa692266c471a52b3 I can't manually resize columns anymore.

**Comment by monsta** [comment]
>  Don't know how did that works before with gtk2 as i don't use list-view normal.

For the record, I just tested it with 1.16, there was no such problem with small zoom level.

**Comment by monsta** [comment]
Ok, https://github.com/mate-desktop/caja/pull/838 should make it better. Please test, maybe I missed something or added another regression (it happens).

**Pull request closed without merging**
