### PR TITLE
Support Back/Forward Mouse Buttons to navigate (gtk2 and gtk3)

### PR DESCRIPTION
**Pull request by mmatuska**
mate-desktop #78 

https://bugzilla.gnome.org/show_bug.cgi?id=660006
https://github.com/GNOME/nautilus/commit/3deb33d449f293b8e2597ccd7cc3bacec7b40ca2
https://github.com/GNOME/nautilus/commit/ae375b34c28c157950069e8bae8e033f5c12a556

Fix works only on gtk3 because requires (but has no impact on gtk2):
https://bugzilla.gnome.org/show_bug.cgi?id=673441
https://github.com/GNOME/gtk/commit/45a5151f940399a0d53109b9ae36e6eed27c21f7

### CODE REVIEW

**Comment by monsta** [comment]
@raveit65 @XRevan86 @lukefromdc @flexiondotorg 

Guys, anyone has the proper mouse to test it? I'm using a simple mouse with two buttons and a wheel... :smile:

**Comment by lukefromdc** [comment]
Same here: two buttons and a clickable wheel only

**Comment by mmatuska** [comment]
It would really be great to have this included in the next patchlevel release

**Comment by lukefromdc** [comment]
Does anyone here have a mouse that can test this? One person was able to write
the patch at least. I am not employed and cannot afford to buy new hardware for
test purposes.

Alternately, is there aany way to emulate this in (other) software or in xorg.conf
or some such way?

**Comment by mr-blobbyyy** [comment]
I'm glad I found this. Been on mate for a couple months now and the mouse navigable buttons not working on icon hover has been a **huge** source of frustration -- almost to the point of wanting to switch entire DE's over this very issue. I have a logitech g402 and actually it remembered its own macros from my previous win7 install, which is nice as no logitech software is needed -- so long as you set the macros up in windows first, lol. In my g402, mouse button G8 is hardware-binded to "ctrl+w" which is awesome and super-better than clicking 'x' for navigating tabs in firefox. I'm still relatively new to Linux but I'm willing to clone the current master and recompile entire mate if I have to -- to fix this very specific issue.

**Comment by monsta** [comment]
BTW, https://github.com/mate-desktop/caja/issues/78 seems to be about GTK+2, and there's also the detailed status of the issue described by @drws in the comments. Is there any fix for all that?

**Comment by mmatuska** [comment]
Yes, this one is for GTK2 (not that simple anymore): https://github.com/mmatuska/caja/commit/1393eccfe5ac307af8ae6b13deab883e294b2530

**Comment by monsta** [comment]
No pull request for that one?

**Comment by mmatuska** [comment]
That one was never accepted by gnome but comes from the same authors. If we can place correct #ifdef's I could unite these two into one larger pull request. What is the best define to find out if I am compiling against gtk2 or gtk3?

**Comment by monsta** [comment]
If it wasn't accepted there, we better give it some additional testing to be sure :smile:

For checking GTK+ version at build time, we use ```GTK_CHECK_VERSION``` macro:
```C
#if GTK_CHECK_VERSION (3, 0, 0)
// here goes stuff to do in GTK+3 build only
#else
// here goes stuff to do otherwise, i.e. in GTK+2 build only
#endif
```

**Comment by mmatuska** [comment]
I have updated the patch for both gtk2 and gtk3

**Comment by monsta** [comment]
Thanks. You can actually squash the commits into a single one, and also use checking for 3.0.0 (we're targeting 3.14 as minimum version for GTK+3 build anyway these days).

**Comment by mmatuska** [comment]
I have not squashed the commits because the credits go to two different persons. The checking against 3.4.1 is because that is the first gtk3 release that supports the new short version. If you insist it can be changed to 3.0.0 but then it is not exact and may make debugging harder (e.g. looking at the gnome code).

**Comment by raveit65** [comment]
Our minimal support version is 3.14, so 3.4.1 does make any sense.
Why should version check make debbuging harder?
I read currently 3.0.0, 3.16.0, 3.18.0, 3.20.0 and 3.21.0
If we make packages gtk3 only in future, btw. some packages are gtk3 only right now, all checks < 3.14 will gone ;)
Our goal is to simplify code and adding more Version checks doesn't do that.

**Comment by mmatuska** [comment]
I have changed the check to 3.0.0, rebased to 1 commit and added two Co-Authored-By: fields according to kernel.org [Commit Message Conventions](https://git.wiki.kernel.org/index.php/CommitMessageConventions)

**Comment by mmatuska** [comment]
Has this thread gone dead? Anyone still watching?

**Comment by mr-blobbyyy** [comment]
@mmatuska Hopefully not, I'd like to see this implemented asap. I've raised the issue with Martin Wimpress himself so hopefully he will comment on the Ubuntu podcast (which gets released tomorrow.)

**Comment by raveit65** [comment]
> Has this thread gone dead? Anyone still watching?

No, but no one has a 5 button mouse to review/test it at the moment.

**Comment by mr-blobbyyy** [comment]
@raveit65 I can review it.

**Comment by monsta** [comment]
@mr-blobbyyy: thanks, would be nice.

**Comment by mr-blobbyyy** [comment]
Just, uh...can anyone give me a few pointers on how to compile this caja branch correctly within mate? I've only done a few git checkouts and make installs before...those have all been on master branches or releases so I want to be sure I know what a should be doing (versus say, fooling around and breaking things ( ͜。 ͡ʖ ͜。))

**Comment by monsta** [comment]
It should be enough to clone that repo and checkout to ```gtk3-mouse-forward-backward``` branch, then build it as usual.

**Comment by mr-blobbyyy** [comment]
@monsta and others, can I do a **checkinstall** to have a convenient deb in case things blow up? Are things going to work out installing "on top of" the previous install of caja? These are the things I'm thinking about...

**Comment by lukefromdc** [comment]
I've used checkinstall debs for years, but not as checkinstall packs them by
default because 
/usr/share/glib-2.0/schemas/gschemas.compiled
/usr/share/icons/hicolor/icon-theme.cache
and worst of all a bunch of folders in /usr/share/mime get copied into the .deb
package. It will install if there is exactly ONE, but removal can (usually won't)
trash your /usr/share/mime directory and kill your desktop.


 Here's what works: 

1: call the source package something like caja_1.16.0, using the underscore
to create a deliberately invalid name

2: build and run checkinstall, it will error out on a failure to build the package
and hold open waiting for input on seeing the log file. Ignore that for now,
leave it open.

3: Naviagate to /var/tim/(something)/package and copy everything into a directory
somewhere else with the desired name of the .deb but without the .deb extension

4: Open that directory, remove 
(packagedir)/usr/share/glib-2.0/schemas/gschemas.compiled
(packagedir)/usr/share/icons/hicolor/icon-theme.cache
and everything in (packagedir)/usr/share/mime except the "packages" directory, which
contains only the item added by this package.

5: change ownership and group to root for the package directory as insurance against
possible installation with user ownership (seen this in the past but not recently)

6: Run dpkg -b (packagedir) and there is your .deb package. This is one deb per source
file, you might want before building to edit DEBIAN/control to "provide" the related
debian packages (*-data, *-dev etc).

This is how I build all my MATE, GTK3, Kdenlive etc debian packages.

**Comment by mr-blobbyyy** [comment]
Someone else might need to take over reviewing duties as I'm afraid I'm not knowledgeable enough in the dependency environment: `No package 'mate-desktop-2.0' found` :cry: :gun:

**Comment by lukefromdc** [comment]
If a package is not found at build time, some of the development files (I think the .pc files) are not installed. In Debian and Ubuntu, these are the -dev files from the set perhaps best described this way. Source "mypackage" builds to a set of Debian packages that may include "mypackage" mypackage-common" "mypackage-data" "mypackage-dbg" and the one you need "mypackage-dev" .

If you install the dependencies (or all of MATE) from source these files will already be present.

**Comment by mr-blobbyyy** [comment]
Ok, after doing some digging I managed to come up with a (non comprehensive) list of dependencies for ubuntu/mint:

```
checkinstall
libglib2.0-dev
gobject-introspection
libmate-desktop-dev
libcaja-extension-dev
libxml++2.6-dev
libgail-3-dev
libgtk-3-dev
```
However, **libmate-desktop-dev** is still an issue because autogen still wants a version >= 1.15.1. Mint is on 1.14.1 (and ubuntu is still on 1.12.1, lol.) Is it worth trying to install [the newest version of mate-desktop](https://github.com/mate-desktop/mate-desktop/releases/tag/v1.16.0) considering the Mint-specific mods to mate?

**Comment by raveit65** [comment]
This does not make any sense :)
@mr-blobbyyy What version have your installed caja package?
@monsta @lukefromdc Can you please build a deb and upload it somewhere?

**Comment by mr-blobbyyy** [comment]
@raveit65, like I said, mmatuska's [fork](https://github.com/mmatuska/caja/tree/gtk3-mouse-forward-backward). I just downloaded the zip file and went from there.

**Comment by monsta** [comment]
I'd not mix 1.16 and 1.14 packages just in case. Yes, you can build 1.16 versions of mate-common, mate-desktop and eventually caja, and install them, but we can't guarantee it will work in 1.14 environment. Maybe yes, maybe no, maybe rain, maybe snow... :smile:

**Comment by mr-blobbyyy** [comment]
Well, in that case, we need to crowdfund [a $37 mouse](https://amzn.com/B00LZVNWIA) and send it to @monsta. Give me a Dogecoin address, I'll put in $5 :dollar:

**Comment by mmatuska** [comment]
You guys are really surprising. What about installing Arch Linux or at least Ubuntu 16.10 in a VirtualBox? You can pass USB devices to VirtualBox.

And just for this you can find a 5-button mouse for $10-$15.

**Comment by flexiondotorg** [comment]
The Ubuntu MATE crowd funding has sent some money to @raveit65 so he can test this pull request using a 5 button mouse :-)

**Comment by mr-blobbyyy** [comment]
Thanks Martin, glad you can make this happen. Here's a small reviewer's guide for @raveit65:

1. First, confirm back and forward on the mouse are working out-of-box. In firefox or other browsers, the back and forward webpage function should work natively. 
2. Confirm the limited back and forward function already existing in Caja -- clicking back/forward when the mouse cursor is over empty space for both "icon/compact view". (This also includes empty space between icons in both "use compact layout" and also unselected. Technically, the empty space within Caja's window is called "input box" -- you can modify the color specifically if you want in the appearance settings.)
3. Now try for the implemented fixes: clicking back/forward while directly hovered over an icon in "icon/list/compact view". In "list view", note if the icon gets unexpectedly "selected" while hovered when clicking back/forward (this is the current behavior.) Make sure it works also when hovered over empty space in "list view" as well.
4. Make sure behavior is expected: "single press in to execute" versus "single press in and out to execute" and also make sure icons are highlighted when hovered.
5. Look for bugs while clicking back/forward all over the window. This includes the title bar, most of the window elements outside of the input box, the "places" sidebar, over the "resize" sidebar, scroll boxes, and also within right-click context menus (current behavior is "select item" while in a context menu.) Also check on the resize window borders as well.

**Comment by raveit65** [comment]
Weird, with latest caja from master (gtk3) back/forward buttons are working out of box in iconview/compactview and if the mouse is over other elements like menubar, statusbar, primary-toolbar and sidebar.
Only if the mouse is over listview clicking button4/5 does have any effect.
So what does the PR fix?

**Comment by mr-blobbyyy** [comment]
>  So what does the PR fix?

Like I said previously, my understanding the PR would fix functioning if the cursor is hovered specifically on any icon in all 3 views (versus just empty space.) If you're saying this works on the master that would be...interesting.

>  Only if the mouse is over listview clicking button4/5 does have any effect.

I'm sorry, I don't understand this. Are you saying it does "not" function in list view?

When you mentioned "menu bar" I did some more testing on my version (1.14.2) and found something interesting. **In this very confined area** (and no where else in the window), back and forward does indeed function on: "single press in and out and in" -- almost like double-clicking -- with an added delay not executing on the 2nd press in. The strange behavior exists in all 3 views. Here's a screenie showing the exact area (enclosed in red) where this behavior exists: http://imgur.com/s0OuW7y

**Comment by raveit65** [comment]
> Are you saying it does "not" function in list view?

Yes, It works everywhere except in listview.

> When you mentioned "menu bar" I did some more testing on my version (1.14.2) and found something interesting. In this very confined area (and no where else in the window), back and forward does indeed function on: "single press in and out and in" -- almost like double-clicking -- with an added delay not executing on the 2nd press in.

I don't see a delay here. If the mouse is over a menuitem the 4/5 buttons open/close the menu.
Also, it works here if one dir is in 'listview'.

Ok, i will test it with the PR to see if there is a different.

**Comment by raveit65** [comment]
For some reason it works also in gtk2 Mate environment (1.16)  w/o the PR, but here only if the mouse is over iconview and compactview, and not in listview.
Looks like i bought a magic mice (SPEEDLINK AXON Mouse) :)
With the PR the forward/back buttons are working also in listview.
Ok, as i see an improvement and it is reviewed by @monsta i will merge it.
I think we can cherry-pick it to 1.16 branch after a while more testing, as it is a bug fix.

**Comment by raveit65** [comment]
A bit rebased and merged https://github.com/mate-desktop/caja/commit/625a06c0a0781025693a6299b721b6bc7a065c1a
Thank you

**Pull request closed without merging**
