### PR TITLE
caja-bookmarks-window.ui: avoid deprecated:

### PR DESCRIPTION
**Pull request by sc0w**
avoid deprecated GtkVBox, GtkHBox and GtkLabel:xpad/ypad

### CODE REVIEW

**Comment by raveit65** [comment]
You can bump required gtk+3 version with glade. This will remove some open yellow warnings in glade.
glade
This will update this line in UI file.
```
<requires lib="gtk+" version="3.0"/>
```
Change version and click on the verify button.

The other warnings for GtkLabels are easy to fix disable the checkbox under  'alignment and padding', and using the setting 'horz. alignment = start" here.
glade2

**Comment by sc0w** [comment]
@raveit65 thanks for the info

I opened the file in this PR, with 3.0, and verify:

glade1

> The other warnings for GtkLabels are easy to fix with disabling the checkbox under 'alignment and padding'

I did it in this PR, disabling padding

> , and using the setting 'horz. alignment = start" here.

I see no warnings with the alignment properties

**Comment by raveit65** [comment]
Yes, but we should use 3.20/22 if possible, because 3.00 allows more deprecated widgets.
glade3

**Comment by sc0w** [comment]
@raveit65 I tried with 3.20 and 3.22 and I see no warnings with this PR

you tried with the .ui file in this PR ?

**Comment by raveit65** [comment]
I used the UI file from PR, but still ignore it, not important enough ;-)

**Comment by sc0w** [comment]
merged: https://github.com/mate-desktop/caja/commit/d66b717d0fe847979b2deac40cdf614eb60dda13

**Comment by sc0w** [comment]
@raveit65 

I suppose you can't see that warnings you mentioned now, with glade 3.20.4

**Comment by raveit65** [comment]
> I suppose you can't see that warnings you mentioned now, with glade 3.20.4

Yes, all warnings are gone with gtlade-3.20.4 :)

**Pull request closed without merging**
