### PR TITLE
caja-file-operations: fixes the operations timer handling

### LINKED ISSUE #1420: File Operations dialog incorrectly displays throughput speed when files are queued
#### Expected behaviour

display real copy speed in octet/s  since the beginning of the copy of the current file proceeded. 

#### Actual behaviour

display an average speed deducted from time since the beginning of the copy of the first file in the pool, instead of the beginning of copy of the current file been proceeded. 

#### Steps to reproduce the behaviour
copy a file to destination, then add another file to copy to the same destination so the operations is queued, then notice the difference in displayed throughput in the file operations window when the second file is copied.
 
#### MATE general version
1.24.0

#### Package version
caja           1.24.0-1     amd64

#### Linux Distribution
ubuntu 20.04 LTS

### PR DESCRIPTION
**Pull request by basicmaster**
Essentially fixes the bug that for queued file operations the wrong transfer rate is shown.

To reproduce the issue/check the fix, start a (larger) file copy/move operation and then start a second one, while the first one is still running.

Fixes #1420 and #1623.

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
With this applied, what I found most noticable was that queuing other files for copying now seems to give accurate bandwidth indication, and the waiting file shows "0 seconds" and zero bandwidth as it is not being processed yet. This is a lot better than what we used to get. Ideally the "0 seconds" would be hidden but users will probably know that's a value that can be ignored. Approving and calling for a 2nd review

**Comment by basicmaster** [comment]
The shown estimate for a queued operation indeed doesn't make sense. The reason is that actually a non-zero transfer rate is [one condition to *not* show the estimate](https://github.com/mate-desktop/caja/blob/8bb93666b35ee6277071d1b5ab4d52ae57d06975/libcaja-private/caja-file-operations.c#L3083). I fixed this in #1759, aligning to the delete operation case.

**Comment by lukefromdc** [comment]
Any updates on this or the alternate? Can this one be closed since we have https://github.com/mate-desktop/caja/pull/1759 ?

**Comment by basicmaster** [comment]
This and #1759 both affect file operations. However they are not alternative solutions, but address different aspects. So they are needed both.

From my side, this MR is ready to be merged (however there still has been no second review).

**Comment by basicmaster** [comment]
Is there maybe an update on this?

**Comment by lukefromdc** [comment]
I will pull this, squash, rebase and then merge to avoid any git surprises

**Comment by lukefromdc** [comment]
Merged with
https://github.com/mate-desktop/caja/commit/ed41589e35a534cb47ea7b6dcc685fef2e7ca578

**Comment by lukefromdc** [comment]
Will cherrypick to 1.28 if no suprises down the road from this

**Pull request closed without merging**
