### PR TITLE
Add --disable-self-check for configure

### PR DESCRIPTION
**Pull request by yetist**
Fixed make distcheck, see #1129

### CODE REVIEW

**Comment by raveit65** [comment]
I guess this needs to be back ported to 1.20 branch after merge?
To get travis-Ci for archlinux working for 1.20 branch too.

**Comment by yetist** [comment]
> I guess this needs to be back ported to 1.20 branch after merge?
This needs to be with #1136 

> To get travis-Ci for archlinux working for 1.20 branch too.
See #1134

**Comment by raveit65** [comment]
I cherry-picked both commits and did a new PR for 1.20 branch.
But it looks like that 1.20 branches aren't available at travis.

**Comment by raveit65** [comment]
Ahh, see https://travis-ci.org/mate-desktop/caja/requests
We need a build config file for 1.20 branch.
Ok, i will cheery-picked them too.

**Comment by raveit65** [comment]
I will cherry-pick existing travis configs to 1.20 branch of other packages.

**Pull request merged**
