### PR TITLE
help: use correct help links to match 'mate-help' directory

### PR DESCRIPTION
**Pull request by NiceandGently**

### CODE REVIEW

**Comment by infirit** [comment]
Which ```mate-help``` directory, I have none?

**Comment by NiceandGently** [comment]
@infirit 
please visit us at irc mate-dev
We have reasons to do that, and we are happy that your interested about MATE isn't died.

regards

**Comment by infirit** [comment]
I can't but regardless, the commit should contain that information for future reference.

**Comment by NiceandGently** [comment]
@infirit 
Ohh,
in short because i respect your work for mate in the past.
With new m-u-g help of main apps like caja or mate-panel are broken.
As we are a small team with heavy workload (only 3 persons are left),
we decided to reactivate the old help from 1.8 for applicatons which i mentioned before.
Using a directory /usr/share/mate-help don't break new m-u-g and give us a opportunity to port old help  step by step to new m-u-g without let users bleeding.

PS: one of our main prob is to transfer new m-u-g or other missing help directories to transiflex, maybe you can help us

**Comment by infirit** [comment]
Sigh, I see your attitude has not changed for the better, ever wonder why ppl leave?

@monsta, I suggest to revert the commit from mate-desktop that removed it and keep mate-user-guide directory for those old docbook files and use mate-help for the new mallard ones in the mate-user-guide repo. And I also suggest to "un-release" mate-user-guide and consider that a mistake as it was really not even close to release ready.

Then the only urls that need updating back to the old docbook user-guide are in mate-terminal. This saves you a shitload of url changes over all of MATE.

**Comment by NiceandGently** [comment]
> Sigh, I see your attitude has not changed for the better, ever wonder why ppl leave?

please do not attack other people here at github!
Everbody can see that i didn' say anything bad to you
....looks like it was a mistake to explain you the reason for this PR.

**Comment by NiceandGently** [comment]
> Sigh, I see your attitude has not changed for the better, ever wonder why ppl leave?

Please, do not attack other people at github
I didn't say anything bad about you.
Everybody can see that.

PS
All what you're saying we have have already discussed at mate-dev
Again, come there and speak with us.

**Comment by NiceandGently** [comment]
> Sigh, I see your attitude has not changed for the better, ever wonder why ppl leave?

Please, do not attack other people at github
I didn't say anything bad about you.
Everybody can see that.

PS
All what you're saying we have have already discussed at mate-dev
Again, come there and speak with us.

**Comment by NiceandGently** [comment]
> Sigh, I see your attitude has not changed for the better, ever wonder why ppl leave?

Please, do not attack other people at github
I didn't say anything bad about you.
Everybody can see that.

PS
All what you're saying we have already discussed at mate-dev
Again, come there and speak with us.

**Comment by NiceandGently** [comment]
> Sigh, I see your attitude has not changed for the better, ever wonder why ppl leave?

Please, do not attack other people at github
I didn't say anything bad about you.
Everybody can see that.

PS
All what you're saying we have already discussed at mate-dev
Again, come there and speak with us.

**Comment by NiceandGently** [comment]
> Sigh, I see your attitude has not changed for the better, ever wonder why ppl leave?

Please, do not attack other people at github
I didn't say anything bad about you.
Everybody can see that.

PS
All what you're saying we have already discussed at mate-dev
Again, come there and speak with us.

**Comment by infirit** [comment]
>All what you're saying we have already discussed at mate-dev

And again this discussion is lost to everyone else who was (or can not be) on irc. No one in a year will know why this change was done because someone could not be bothered to write a proper commit message.

Now unless someone explains what the plan is and documents this plan I see no point continuing this discussion.

**Comment by NiceandGently** [comment]
> This saves you a shitload of url changes over all of MATE.

This isn't true, most applications use their own help and wasn't ever ported to use parts of m-u-g.
> No one in a year will know why this change was done because someone could not be bothered to write a proper commit message.

Well, the main comment will be done in mate-desktop, so it is sufficient to document it there.

**Comment by infirit** [comment]
What is the plan and where is it documented? In the time stubbornly spend avoiding explaining it could have been answered many times.

**Comment by monsta** [comment]
omg... :open_mouth: 

Ok, I'll try to explain the details (and a bit of history).

We waited since January for m-u-g updates and didn't get any. @MotoHoss simply disappeared from both github and irc, the guide was incomplete, and it was the only roadmap item that kept us from releasing MATE 1.10. Eventually, after some discussion between the remaining developers, it's been decided to label the current m-u-g as 1.10 and therefore release MATE 1.10, which has been done a month ago.

Soon after that, we discovered that a lot of apps didn't have any help. Yelp was giving errors about non-existing links. We started to fix that. Turned out that most of apps have their own help bundled, it was just a matter of fixing broken links. Though in some apps we also had to enable help in makefiles as well, but that wasn't hard anyway.

Then we proceeded to fix caja and mate-panel. Here it was much worse. Both apps relied on m-u-g instead of having their own help (mate-panel had help for two bundled applets but not for all other parts). In m-u-g we found some pages that weren't included in makefiles and decided to add and use them.

So we started with Caja. Updated m-u-g worked fine, I just had to change some links in Caja code. It wasn't really good because the guide structure was different from what was expected in the code. So I just made all Caja's dialogs display the main page of Caja's help - until m-u-g is complete.

Then we tried to do the same for mate-panel. It was much worse. There were no draft m-u-g pages available so we had no place to pick help from. I don't know what we were thinking, but for some reason we decided to pick the panel-related part of the old guide (from mate-desktop repo) and ship it with the panel. Luckily, I was smart enough to make a dedicated branch for it (called user-guide-experimental) instead of pushing it straight to master... So the work began. Panel-related parts of the old guide were stripped of some unrelated info and copied to that branch.

Very quickly we found out that most of the pages in the old guide are so intertwined that we'd have to ship almost the whole guide with panel... Well, we should've thought about it before diving in head first. At the same time, we found out that m-u-g isn't translated at all. The old guide is. So introducing our new Caja help would be a regression from 1.8 (which had the old guide) for a lot of users.

So now here comes Plan B.
- user-guide-experimental branch is ditched as the experiment failed;
- old user-guide is resurrected completely in mate-desktop repo (from 1.8 branch) and shipped with it;
- our changes in the new m-u-g are reverted (mostly Caja stuff);
- both guides are be named differently to avoid any possible conflicts (one such conflict would surely arise over legal.xml file);
- links in the code are corrected (where it's needed) so both Caja and mate-panel use the proper sections of the old guide.

For now, the work on the old guide goes to my fork of mate-desktop repo, in a dedicated [branch](https://github.com/monsta/mate-desktop/tree/back-to-the-future). As it's not finished yet but @NiceandGently already made PRs for Caja (this one) and panel (https://github.com/mate-desktop/mate-panel/pull/320), no wonder it caused some confusion. :smile:

Now about the names. We decided to rename the old guide to ```mate-help``` and keep the new one as is, i.e. ```mate-user-guide```. This won't cause any issues if/when MotoHoss or someone else will try to complete (and translate) it. Besides, it's probably already being pushed to various distros.

As for completely discarding m-u-g, I'm not sure if this should be done now... It has help for mate-terminal plus some other sections that are missing in the old guide. I'm inclined to make both guides coexist so the users would get the complete help in the end. The changes are still being prepared, so this can be discussed further.

**Comment by infirit** [comment]
So the main problem here is not knowing of (or reading) the wiki which has everything documented wrt to m-u-g :cry:. It can't be helped I guess when folks go mia.

>Then we proceeded to fix caja and mate-panel. Here it was much worse. Both apps relied on m-u-g instead of having their own help

No they didn't, they relied on the gfdl docbook files in mate-desktop. Reverting the commit in mate-desktop will make these work again (maybe not scrolling down but that is not relevant for this discussion). Only mate-terminal was ready for which I updated the url to point to the new mallard pages.

>At the same time, we found out that m-u-g isn't translated at all. The old guide is.

Yes, and on the wiki for the [documentation team](http://wiki.mate-desktop.org/dev-doc:doc-team-guide#dtranslations) this is explained. The simple reason is that it will be a huge effort to ask of the translators and having them translate and re-translate over and over is a waste of their time.

>both guides are be named differently to avoid any possible conflicts (one such conflict would surely arise over legal.xml file);

You can in fact __not__ have mallard and docbook in the same directory. But changing the directory for m-u-g is a lot less work as it is a one line change in m-u-g and a two in mate-terminal. 

>links in the code are corrected (where it's needed)

This means hunting down and updating every "help:" url in all the repos (pluma will also need an update because of above). I think this is a waste of your efforts which can be spend on better things (like writing new mallard pages in m-u-g :wink:).

So, my suggestion is the following.

1. revert the commit in mate-desktop to resurrect the old gfdl docbook files and keep the original directory, [here](https://github.com/mate-desktop/mate-desktop/compare/master...infirit:restore-user-guide?expand=1)
2. Revert the url commits in mate-panel and caja so they are as they where in 1.8 (no commits as they are trivial).
3. Install m-u-g to a new directory (mate-help) and fix file collision (desktop file) [here](https://github.com/mate-desktop/mate-user-guide/compare/master...infirit:restore-user-guide?expand=1). 
4. Update mate-terminal help url to refect new directory, [here](https://github.com/mate-desktop/mate-terminal/compare/mate-desktop:master...infirit:restore-user-guide?expand=1).

That's it :smiley_cat:.

Next steps are to import/write mallard documentation in two tracks. One track for the individual applications, which can be done one by one, like pluma and atril. Then another to do the big task for MATE desktop (panels, applets file manager) which has to be done from scratch and in one go. In one go as it is heavily inter connected as you found out the hard way and from scratch as we can not "borrow" from gnome.

Now unless there are objections I'll push these changes  and ppl can go back to hacking and writings documentation.

~infirit

**Comment by flexiondotorg** [comment]
@monsta @infirit Thank you both for explaining your experiences, very useful. @infirit one question, were GNOME contacted to ask if we can relicense?

**Comment by infirit** [comment]
>were GNOME contacted to ask if we can relicense

No, I would not even have a clue what would be involved to be honest. It may require permission from every translator..

**Comment by flexiondotorg** [comment]
@infirit I will take on the task of requesting re-licensing, because regardless of where the help content ends up, if can prove a best efforts to contact the original copyright holders it will save us a huge amount of work.

**Comment by monsta** [comment]
@infirit: most apps have their own help bundled, no? You mentioned pluma but I see there's a help dir in the repo.

**Comment by monsta** [comment]
> revert the commit in mate-desktop to resurrect the old gfdl docbook files and keep the original directory

I agree, but why not use [this branch](https://github.com/monsta/mate-desktop/commits/back-to-the-future) instead? It already has some issues fixed. Just a small rename is needed if you wish to keep the old guide name here (and rename the new guide to mate-help). I'm currently waiting for more possible fixes from @NiceandGently so I could make a complete PR.

> Install m-u-g to a new directory (mate-help) and fix file collision (desktop file)

Personally, I don't care which one is renamed as long as the users get the complete help. I only worried about this because of @MotoHoss. Are you sure this rename will be ok for him?

> Update mate-terminal help url to refect new directory

I looked at it and saw it has its own help bundled. It just needs some small fixes. Won't it be better to use it instead? It's also translated - unlike the page in m-u-g.

**Comment by monsta** [comment]
@infirit: update - PR is done at https://github.com/mate-desktop/mate-desktop/pull/179.

**Comment by monsta** [comment]
Closing due to the changes in our strategy, see the discussion above and in https://github.com/mate-desktop/mate-desktop/issues/179.

**Pull request closed without merging**
