### PR TITLE
replace deprecated device_manager

### PR DESCRIPTION
**Pull request by raveit65**
@XRevan86
Can you do the review please, as you did the port in mate-panel?
@monsta @flexiondotorg @lukefromdc 
Please test.

Most commits are from nautilus.

### CODE REVIEW

**Comment by raveit65** [comment]
well, for some reasons fedora rawhide don't update to 3.21.3, here we have 3.21.1, which is quite unusual.
So, i can't reproduce the issue or test the PR.
But this PR can wait a while, first we should finished the GdkRGBA port.

**Comment by lukefromdc** [comment]
Just rebased the gtk_cairo_create replacement PR https://github.com/mate-desktop/caja/pull/574 against today's mate-desktop/master as
https://github.com/mate-desktop/caja/pull/579

**Comment by lukefromdc** [comment]
I just tested this on top of dev-style-context(https://github.com/mate-desktop/caja/pull/577) and dev-gtk_cairo_create_replace (https://github.com/mate-desktop/caja/pull/579) and had no problems at all. Behavior same as before, this looks good to go from my end

**Comment by lukefromdc** [comment]
My PR's concerning gkd_cairo_create here turned out to replace something only used by caja  in GTK2 already.  Closed them, seems to me this PR  (https://github.com/mate-desktop/caja/pull/578)
should now be next in line for caja. I've already tested it and found it to work just fine.

**Comment by monsta** [comment]
Tested with 3.20, seems to work as before.

**Comment by raveit65** [comment]
Ok, than i will merge it

**Pull request merged**
