### PR TITLE
caja-progress-info: show notifications with the gsettings key

### PR DESCRIPTION
**Pull request by sc0w**
Closes https://github.com/mate-desktop/caja/issues/1093

### CODE REVIEW

**Comment by lukefromdc** [comment]
What exactly am I looking for in testing this? Small copy jobs do not now generate notifications, only longer ones do but I don't know what the minimum time is for that in master

**Comment by sc0w** [comment]
seems the time is two seconds, you can see it here:

```
        g_timeout_add_seconds (2,
                           (GSourceFunc)delayed_window_showup,
                            g_object_ref (info));
```

in the function:

```
static void
new_op_started (CajaProgressInfo *info)
{
    GtkWidget * container;

    g_signal_handlers_disconnect_by_func (info, (GCallback)new_op_started, NULL);

    if (!caja_progress_info_get_is_finished (info)) {
        handle_new_progress_info (info);

        /* Start the job when no other job is running */
        // TODO use user defined policies
        if (info->waiting) {
            if (get_running_operations () == 0)
                progress_info_set_waiting (info, FALSE);
        }

        g_timeout_add_seconds (2,
                           (GSourceFunc)delayed_window_showup,
                           g_object_ref (info));
    }
}
```

and, of course, that time can be modified with a gsettings key if needed in more commits

@raveit65 you see differences against git master?

this is the expected behavior for you?

**Comment by sc0w** [comment]
if the behavior is the same, I will change the PR using a gsettings key to show the notifications, and I think the existing key "show-notifications" can be used here

**Comment by raveit65** [comment]
Thanks, let me test current state of PR.

**Comment by raveit65** [comment]
Indeed, i can't see a different behavior with PR.

**Comment by monsta** [comment]
Can I just disable this feature completely...?

**Comment by sc0w** [comment]
now can be enabled/disabled with the existing gsettings key:

`org.mate.caja.preferences.show-notifications`

please test

**Comment by sc0w** [comment]
I did little changes in latest commit

@lukefromdc @raveit65 @monsta  do you like the new behavior?

**Comment by lukefromdc** [comment]
The notification behavior is now more consistant: the gsettings preference controls both the file job done notification and the eject job notifications. The file job done notification is sometimes delayed, but that might be the disk not reporting back right away that it has finished. Had to run fstrim to clean up that drive after all these tests.  Got two warninngs but got them in master too, you will see them in testing from the terminal but they are NOT related to this PR:

(caja:4418): Gdk-CRITICAL **: 23:09:21.198: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

(caja:4418): GLib-GIO-WARNING **: 23:09:25.973: Your application does not implement g_application_activate() and has no handlers connected to the 'activate' signal.  It should do one of these.

First warning appears on the heavy I/O load and at about the same time as the file transfer dialog and tray icon. Second warning appears on clicking the notification. Again, these warnings appear both in master and with this PR and for this PR can be disregarded. Same for some freezes I got from loading the heck out of an old SSD in testing this: same in Master and probably the known kernel issue with heavy file transfer loading.

**Comment by raveit65** [comment]
Ready to go?

**Comment by sc0w** [comment]
> you will see them in testing from the terminal but they are NOT related to this PR:

> (caja:4418): GLib-GIO-WARNING **: 23:09:25.973: Your application does not implement g_application_activate() and has no handlers connected to the 'activate' signal. It should do one of these.

> Second warning appears on clicking the notification.

@lukefromdc I will investigate this warning, how can I see it? how to run caja in terminal?

**Pull request merged**
