### PR TITLE
Avoid deprecated g_type_class_add_private

### PR DESCRIPTION
**Pull request by yetist**
With minimal changes to avoid deprecated g_type_class_add_private.

### CODE REVIEW

**Comment by sc0w** [comment]
There are no more build warnings in the affected files and caja works fine

a lot of work is pending:

```
caja-menu.c:117:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-clipboard-monitor.c:193:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-column-chooser.c:132:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-desktop-icon-file.c:409:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-desktop-link.c:533:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-directory.c:117:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-file-conflict-dialog.c:724:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-file.c:8610:2: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-icon-canvas-item.c:2803:2: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-icon-canvas-item.c:3570:2: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-trash-monitor.c:93:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-undostack-manager.c:222:3: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
fm-desktop-icon-view.c:315:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
fm-properties-window.c:5766:2: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-application.c:2482:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-connect-server-dialog.c:1171:2: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-connect-server-operation.c:123:2: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-desktop-window.c:343:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-image-properties-page.c:639:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-information-panel.c:221:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-location-bar.c:472:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-navigation-action.c:401:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-navigation-window.c:1289:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-property-browser.c:257:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-side-pane.c:164:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-sidebar-title.c:224:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-spatial-window.c:1128:2: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-trash-bar.c:167:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-view-as-action.c:280:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-window.c:2192:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-x-content-bar.c:259:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-zoom-control.c:681:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
caja-zoom-action.c:203:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
```
but it can be done in other/s PRs

**Comment by raveit65** [comment]
I found some runtime warnings in xsession-errors log and caja crashes  sometimes without any abrt alarm. The desktop simple starts again but all open caja windows are closed.
Warnings are looking like they are related to  PR.
```
(caja:3674): GLib-GObject-WARNING **: 09:28:22.943: invalid (NULL) pointer instance

(caja:3674): GLib-GObject-CRITICAL **: 09:28:22.943: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(caja:3674): GLib-GObject-WARNING **: 09:28:22.943: invalid (NULL) pointer instance

(caja:3674): GLib-GObject-CRITICAL **: 09:28:22.943: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(caja:3674): EggSMClient-CRITICAL **: 09:28:22.943: egg_sm_client_is_resumed: assertion 'client == global_client' failed
```
But maybe this is the result that porting of other files are missing?
Well, this is with f28 where `g_type_class_add_private` wasn't deprecated.

**Comment by sc0w** [comment]
I can't see that warnings in `.xsession-errors` and I didn't notice crashes with git master

**Comment by yetist** [comment]
I did a test and found the warnings could be seen in the following states:
1. There are `DESKTOP_AUTOSTART_ID` environment variables in the current environment
2. Keep one caja instance is running, and then run caja as the second instance.
I tested the PR, the master code without the PR, and the caja version 1.21.3, and they all saw this warning.

**Comment by lukefromdc** [comment]
Can you duplicate this while running Caja under gdb? I don't know anything about `DESKTOP_AUTOSTART_ID` environmental variables. If we can't fix this we will have to revert

**Comment by yetist** [comment]
I'm not sure if this is the case with @raveit65 , but I think revert the code won't solve the issue.

The simplest reproducing method is to run the follow command on any terminal in the current environment.
```
$ env DESKTOP_AUTOSTART_ID=ANY_CHARS caja
```

**Comment by lukefromdc** [comment]
If I do that, I get 
```

(caja:11130): GLib-GObject-WARNING **: 23:03:31.275: invalid (NULL) pointer instance

(caja:11130): GLib-GObject-CRITICAL **: 23:03:31.275: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(caja:11130): GLib-GObject-WARNING **: 23:03:31.275: invalid (NULL) pointer instance

(caja:11130): GLib-GObject-CRITICAL **: 23:03:31.275: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(caja:11130): EggSMClient-CRITICAL **: 23:03:31.275: egg_sm_client_is_resumed: assertion 'client == global_client' failed

```
in terminal but the main instance of caja keeps running and any other caja windows stay open

**Comment by lukefromdc** [comment]
I just rebuilt Caja from a months-old source directory, old enough I had to remove caja-extensions to run it and got the exact same warnings. Thius, this PR had exactly nothing to do with the problem

On further tests (following my usual protocol for finding Caja warnings), I found that hiding the sidebar, statusbar,main toolbar, or location bar had no effect at all, and the warnings are the same in icon, list, or compact view. I then tried a build with every instance of g_signal_connect_data commented out-and it STILL appeared in the warnings, meaning it is coming from a linked library, probably  gtk3 or mate-desktop. Can't be an extension, I had that package removed in the old version test and still got the warnings.

**Comment by yetist** [comment]
When running the first caja instance, the `caja_application_startup` is run first, and then the `caja_application_local_command_line` is run, so `self->smclient` is initialized [here](https://github.com/mate-desktop/caja/blob/master/src/caja-application.c#L2375
).

When running the second caja instance, the `caja_application_startup` will not run before the `caja_application_local_command_line`, so `self-> smclient` is NULL [here](https://github.com/mate-desktop/caja/blob/master/src/caja-application.c#L197), so got the warnings in the follow lines:
```
    g_signal_connect (self->smclient, "save_state",
                          G_CALLBACK (smclient_save_state_cb),
                          self);
    g_signal_connect (self->smclient, "quit",
              G_CALLBACK (smclient_quit_cb),
              self);
```

**Comment by lukefromdc** [comment]
OK, that tells me this goes all the way back to the GtkApplication work, so that block needs to get a check for being the first instance. Should be a simple fix, I will play with it now

**Comment by lukefromdc** [comment]
This block below in caja_application_local_command_line is supposed to keep the offending block from executing but obviously does not always catch the command line start, my guess is passing that environmental variable is somehow getting past it.

```
    /* Initialize  and load session info if available */
    /* Load session if and only if autostarted        */
    /* This avoids errors on command line invocation  */
    if (autostart_id != NULL ) {
        caja_application_load_session (self);
    }

```

**Comment by lukefromdc** [comment]
Try
https://github.com/mate-desktop/caja/pull/1110
which should fix this, it adds a check for existance of the smclient before trying to load the session. Putting the check there cuts out a big block of code that should not have to run on a second or subsequent invocation, or any invocation where Caja was not started by the session manager.

**Comment by raveit65** [comment]
> I'm not sure if this is the case with aveit65 , but I think revert the code won't solve the issue.

No, that isn't needed.
I only found this warnings after a crash of caja in my logs. But it is complete unclear why this crash happened.
Sometimes i think my NVME drive causes issues with the file system, compare to using a normal SSD in the last years.

**Pull request merged**
