### PR TITLE
drop unused variables

### PR DESCRIPTION
**Pull request by sc0w**

### CODE REVIEW

**Comment by yetist** [comment]
More need to do, please go on:
```
eel-image-table.c: In function ‘eel_image_table_finalize’:
eel-image-table.c:102:20: warning: variable ‘image_table’ set but not used [-Wunused-but-set-variable]
     EelImageTable *image_table;
                    ^~~~~~~~~~~
eel-labeled-image.c: In function ‘eel_labeled_image_draw’:
eel-labeled-image.c:366:16: warning: variable ‘window’ set but not used [-Wunused-but-set-variable]
     GdkWindow *window;
                ^~~~~~
caja-file-conflict-dialog.c: In function ‘caja_file_conflict_dialog_init’:
caja-file-conflict-dialog.c:565:14: warning: variable ‘source_is_dir’ set but not used [-Wunused-but-set-variable]
     gboolean source_is_dir;
              ^~~~~~~~~~~~~
caja-program-choosing.c: In function ‘caja_launch_application_by_uri’:
caja-program-choosing.c:212:16: warning: variable ‘total’ set but not used [-Wunused-but-set-variable]
     int count, total;
                ^~~~~
caja-application.c: In function ‘caja_application_startup’:
caja-application.c:2352:12: warning: variable ‘drives’ set but not used [-Wunused-but-set-variable]
     GList *drives;
            ^~~~~~
...
```

**Comment by sc0w** [comment]
With this PR I fixed the warnings:

```
eel-string.c:937:9: warning: unused variable 'integer' [-Wunused-variable]
caja-global-preferences.c:69:9: warning: unused variable 'i' [-Wunused-variable]
caja-module.c:260:12: warning: unused variable 'res' [-Wunused-variable]
caja-progress-info.c:943:17: warning: unused variable 'container' [-Wunused-variable]
fm-directory-view.c:4692:12: warning: unused variable 'file' [-Wunused-variable]
caja-application.c:2353:22: warning: unused variable 'application' [-Wunused-variable]
caja-connect-server-dialog.c:845:16: warning: unused variable 'alignment' [-Wunused-variable]
caja-navigation-window-menus.c:459:9: warning: unused variable 'i' [-Wunused-variable]
caja-window.c:383:16: warning: unused variable 'cursor' [-Wunused-variable]
```

There are more pending warnings:

```
eel-image-table.c:102:20: warning: variable 'image_table' set but not used [-Wunused-but-set-variable]
eel-labeled-image.c:366:16: warning: variable 'window' set but not used [-Wunused-but-set-variable]
caja-file-conflict-dialog.c:565:14: warning: variable 'source_is_dir' set but not used [-Wunused-but-set-variable]
caja-icon-canvas-item.c:1700:24: warning: variable 'container' set but not used [-Wunused-but-set-variable]
caja-keep-last-vertical-box.c:92:13: warning: variable 'box' set but not used [-Wunused-but-set-variable]
caja-progress-info.c:466:12: warning: variable 'mypos' set but not used [-Wunused-but-set-variable]
caja-program-choosing.c:212:16: warning: variable 'total' set but not used [-Wunused-but-set-variable]
fm-icon-view.c:549:17: warning: variable 'icon_view' set but not used [-Wunused-but-set-variable]
caja-application.c:1370:14: warning: variable 'existing' set but not used [-Wunused-but-set-variable]
caja-application.c:2352:12: warning: variable 'drives' set but not used [-Wunused-but-set-variable]
caja-connect-server-dialog.c:391:36: warning: variable 'entry' set but not used [-Wunused-but-set-variable]
caja-connect-server-dialog-nonmain.c:41:30: warning: variable 'self' set but not used [-Wunused-but-set-variable]
caja-emblem-sidebar.c:1079:29: warning: variable 'klass' set but not used [-Wunused-but-set-variable]
caja-places-sidebar.c:2932:19: warning: variable 'model' set but not used [-Wunused-but-set-variable]
caja-places-sidebar.c:3076:24: warning: variable 'sidebar' set but not used [-Wunused-but-set-variable]
caja-property-browser.c:1714:19: warning: variable 'action' set but not used [-Wunused-but-set-variable]
caja-property-browser.c:1712:21: warning: variable 'context' set but not used [-Wunused-but-set-variable]
caja-side-pane.c:137:21: warning: variable 'widget_class' set but not used [-Wunused-but-set-variable]
caja-spatial-window.c:985:16: warning: variable 'menuitem' set but not used [-Wunused-but-set-variable]
```

But I prefer to do the work in other PR

So, for me this PR is ready

@mate-desktop/core-team your decision: can this be pushed to 1.22 ?

**Comment by raveit65** [comment]
Those warnings do only spam build logs and it is save to remove them, ........ mostly.
Personal, i am *undecided* to push this in freeze phase without longer testing a few days before the release.
Go ahead if other team members agree with it.

**Comment by rbuj** [comment]
Dead store: 41 Dead assignment
The report is available at https://rbuj.fedorapeople.org/caja/

**Comment by lukefromdc** [comment]
Fine with me, I can't see any way an unused variable would be suddenly used in some distro we aren't testing on locally or with the travis builds. Unused is unused

**Comment by sc0w** [comment]
@rbuj @yetist @raveit65 

seems travis supports clang, I don't know if it is possible to use the clang analyzer inside travis

**Comment by yetist** [comment]
yes, it's possible, the docker-build 0.1.1 version support to use custom commands or scripts for building.

**Comment by yetist** [comment]
But maybe we need a server to upload the result html file?

**Comment by yetist** [comment]
There is a way, I will try to use github pages to display these html files,  https://pages.github.com

**Comment by yetist** [comment]
The test for marco passed, demo is here: https://yetist.github.io/marco/

**Comment by yetist** [comment]
@raveit65 

Can you open https://github.com/mate-desktop/caja/settings and set Github Pages Source to use gh-pages branch?

Reference documentation: https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages

**Comment by raveit65** [comment]
It is already set to `gh-pages`

**Comment by yetist** [comment]
> It is already set to `gh-pages`

Thank you. The page works https://mate-desktop.github.io/caja

@rbuj @sc0w 

I use this scripts to build caja in travis: https://travis-ci.org/mate-desktop/caja/jobs/496959475#L9216
But get errors:

```
File "/usr/lib64/gobject-introspection/giscanner/scannermain.py", line 418, in create_binary
    gdump_parser.get_error_quark_functions())
  File "/usr/lib64/gobject-introspection/giscanner/dumper.py", line 294, in compile_introspection_binary
    return dc.run()
  File "/usr/lib64/gobject-introspection/giscanner/dumper.py", line 168, in run
    introspection_obj = self._compile(c_path)
  File "/usr/lib64/gobject-introspection/giscanner/dumper.py", line 197, in _compile
    self._options.init_sections)
  File "/usr/lib64/gobject-introspection/giscanner/ccompiler.py", line 250, in compile
    output_dir=os.path.abspath(os.sep))
  File "/usr/lib64/python3.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib64/python3.7/distutils/unixccompiler.py", line 129, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command '/usr/bin/../libexec/ccc-analyzer' failed with exit status 1
make[2]: *** [/usr/share/gobject-introspection-1.0/Makefile.introspection:156: Caja-2.0.gir] Error 1
make[2]: Leaving directory '/rootdir/libcaja-extension'
make[1]: *** [Makefile:515: all-recursive] Error 1
make[1]: Leaving directory '/rootdir'
make: *** [Makefile:446: all] Error 2
scan-build: 22 bugs found.
```

**Comment by rbuj** [comment]
@yetist 
```
    --use-analyzer="`which clang`" \
```
instead of
```
    --use-analyzer=/usr/share/clang \
```

**Comment by sc0w** [comment]
I continue the work here in https://github.com/mate-desktop/caja/pull/1168

**Pull request merged**
