### PR TITLE
Gtk3: Port deprecated GtkTable to GtkGrid

### PR DESCRIPTION
**Pull request by raveit65**

### CODE REVIEW

**Comment by lukefromdc** [comment]
I can confirm that this builds and runs with gtk3.18. Didn't fix the desktop flashes, but so far I have not found any new bugs from this.

**Comment by raveit65** [comment]
@monsta 
Please review the PR ?

**Comment by monsta** [comment]
Oops, merge conflicts...

BTW, I'd split https://github.com/raveit65/caja/commit/66b92ee192234ce6c2ad4ad42e6501d156cb7f48 into a separate PR (due to its size and complexity).

**Comment by raveit65** [comment]
merged
https://github.com/mate-desktop/caja/commit/05d56843bec81e24ff072ed63937bb02b2a6bde5
https://github.com/mate-desktop/caja/commit/d96cb50cd99b8785482c610145035ca09322be47
https://github.com/mate-desktop/caja/commit/f54aab0e53880c8e8c65d878ffe06e5e941e16e8
https://github.com/mate-desktop/caja/commit/a0c71663bbcf89db74eeee61cdf6eaf815af2323
https://github.com/mate-desktop/caja/commit/acd9202389781d863abf05e8e8feb65c7b380300

**Pull request closed without merging**
