### PR TITLE
Fix: Scaling the desktop wallpaper doesn't work

### PR DESCRIPTION
**Pull request by sc0w**
Fixes https://github.com/mate-desktop/caja/pull/824#issuecomment-323568583

@raveit65 @lukefromdc please test

### CODE REVIEW

**Comment by lukefromdc** [comment]
OK, I just managed to duplicate the issue by selecting "stretch" for the wallpaper scaling option, and indeed this PR fixes it.

"Zoom" always works, "scale" always leaves uncovered areas due to the way  it works, both of them seem to work the same way with or without this PR due to not triggering the issue in some way. With stretch it is quite drastic without this PR and very ugly.

**Comment by raveit65** [comment]
I think it depends on picture size which mode is affected. I can reproduce the issue with 'zoom' mode, which is the default and should work.

**Comment by raveit65** [comment]
So, gdk_window_get_geometry () was missing for gtk+-3.22, we need to check that in all similar PRs which are merged.
I will test this PR a bit and merge it later.

**Comment by raveit65** [comment]
Thanks for quick reaction.

**Pull request merged**
