### PR TITLE
[WIP] Add Meson build file

### PR DESCRIPTION
**Pull request by jhasse**
I've started to work on adding the possibility to build Caja with [Meson](http://mesonbuild.com/). This is currently blocked by https://github.com/mesonbuild/meson/issues/2748, I just thought I would push the work so far and update my branch when I get it working ;)

### CODE REVIEW

**Comment by raveit65** [comment]
We are already in feature freeze for 1.20.
And i would like to see a discussion first about benefits of meson.

**Comment by jhasse** [comment]
No need to rush because it currently doesn't work yet anyway ;)

One advantage of Meson is that it makes it easy to do a out-of-tree build, i.e. all the build artifacts in a separate folder. This was the main thing that annoyed me when build with autotools: All the files lying around next to the source files. Maybe that can be fixed with autotools too, but I don't know how to do that.

**Comment by raveit65** [comment]
Any News?

**Comment by lukefromdc** [comment]
Any updates on this? We already have some packages buildable with meson, would be nice to add this one to them

**Comment by jhasse** [comment]
I'm no longer working on this. Someone else would need to pick it up.

**Comment by lukefromdc** [comment]
OK, no problem, someone else did several packages I think.

**Pull request closed without merging**
