### PR TITLE
GTK+-3 eel-editable-label: drop usage of GtkMisc 

### PR DESCRIPTION
**Pull request by raveit65**

### CODE REVIEW

**Comment by raveit65** [comment]
Current result looks like this.
bildschirmfoto zu 2016-07-06 17-27-50
As you can see the selected text isn't in center, btw. no top padding.

**Comment by raveit65** [comment]
Now it looks perfect for me :)
bildschirmfoto zu 2016-07-06 18-59-03 
bildschirmfoto zu 2016-07-06 18-59-38 
bildschirmfoto zu 2016-07-06 19-00-25
@monsta @lukefromdc 
If last commit makes sense for you i'd like to use it.
Of course i will remove 
```
    struct _EelEditableLabel
    {
        GtkMisc misc;

    struct _EelEditableLabelClass
    {
        GtkMiscClass parent_class;
```
from eel-editable-label.h for gtk3 and squash all commits in one.

**Comment by raveit65** [comment]
@monsta 
Should i repace  GtkMisc misc; with GtkWidget widget in eel-editable-label.h?
And same for GtkMiscClass parent_class;
Or simply remove it for gtK3?

**Comment by monsta** [comment]
For the record, here's how it looks in 1.14...

GTK+2 (Ubuntu MATE 16.04):
gtk2 gtk2-edit-selected gtk2-edit

GTK+3 (Ubuntu MATE 16.10):
gtk3 gtk3-edit-selected gtk3-edit

Theme is TraditionalGreen, but it looks the same with other themes.
As you can see, there's no any padding on top or bottom... should we really try to introduce it?

**Pull request merged**
