### PR TITLE
modify code error: end the statement with a semicolon

### PR DESCRIPTION
**Pull request by zhangwen2**
modify code error: end the statement with a semicolon

### CODE REVIEW

**Comment by zhangwen2** [comment]
it’s not a problem under normal circumstances，but the writing is not the intention of this code。

**Comment by lukefromdc** [comment]
As I said, what surprised me is that the code with the mistake EVER worked, this somehow was missed and your fix is long overdue. Hoping for another review before I merge this

**Comment by will-kong** [comment]
of course it can work well.
as the rule in C/CPP language, two expressions can be written on single one line with a comma/semicolon as a delimiter. these two expressions wil be executed sequentially. (Sorry for i forgetting the order of executing ^_^)
in this case, two function will be invoked sequentially, this is why there is no functional error ocurrs. But i think this maybe a bad style.

**Comment by monsta** [comment]
Wiki has pretty good summary for this operator:
https://en.wikipedia.org/wiki/Comma_operator

**Pull request merged**
