### PR TITLE
Replace GtkStateType (GTK2 enum) with GtkStateFlags (GTK3 enum)

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by rbuj** [comment]
@lukefromdc I think it's fixed now.

**Comment by lukefromdc** [comment]
Is this ready to go? waiting on a second reviewer here

**Comment by raveit65** [comment]
Usually i started to review the oldest open PRs and not the newest.
Sadly, there are a lot of PRs open which are older and nobody review them.
Yesterday i merged 2 PRs and @rbuj submitted 3 new ones.
I can't and i don't want to spend so much time for reviews or in generally for MATE, like i did in the last 6 years.
See this bugreport from last year.
https://github.com/orgs/mate-desktop/teams/core-team/discussions/17
The day will come that team member needs to review their own PRs ;)

Any way, i will take a look at this one when i found time.

**Comment by sc0w** [comment]
and also see:

https://github.com/orgs/mate-desktop/teams/core-team/discussions/21

If no donations, no motivation...

**Comment by raveit65** [comment]
> and also see:
> https://github.com/orgs/mate-desktop/teams/core-team/discussions/21
> If no donations, no motivation...

So, Mate users are guilty because they don't donate for open source software?

**Pull request merged**
