### PR TITLE
caja-file-operations: fix caption/button in destination error dialogue

### PR DESCRIPTION
**Pull request by basicmaster**
For certain operations, the destination is checked. If an error occurs, the user is asked how to proceed using a dialogue. So far this dialogue was hard-coded to only consider the copy operation.

This fix also considers the other affected operations and generalizes the continue button text.

### CODE REVIEW

**Comment by basicmaster** [comment]
The mentioned dialogue for a move operation:

Before ("kopieren" translates to "to copy"):
grafik

After:
grafik

**Review by lukefromdc — COMMENTED** [review]
The text change in the button works, though translations would presumably have to be re-synced before the middle button would be translated.

I don't see any easy way to test (or really an application for) this in the "move" case as such errors as out of space cannot exist in that case. NOT sure how copy-on-write filesystems handle this though. I am using EXT4 for basically everything. When permissions are the issue,a force option does not exist. Creating a new file created a 0 byte file, and would fail only with an absolutely full filesystem that cannot handle the metadata. Continuing in such a case would surely corrupt the entire fs.

The two button error dialog for trying to copy into a root-owned directory as user is unchanged, create, make link, etc are greyed out when permissions is the issue and that seems unchanged, as it should be

**Comment by basicmaster** [comment]
A real-world use case is e.g. to copy (or move) a larger file to a different file system (e.g. to a USB drive), which doesn't have enough space left to store the file.

My screenshots show the attempt to move a file to a RAM drive (for which caja always shows 0 bytes free space). Everytime I want to copy or move a file to it, I get the shown error message and have to click on the center button to (successfully) copy/move a file to it.
The following line in `/etc/fstab` is used to create/mount the RAM drive:

    ramfs   /ramdisk     ramfs   defaults,mode=777        0       0

**Comment by raveit65** [comment]
I could reproduce the issue with creating a ramdisk on the fly https://www.linuxbabe.com/command-line/create-ramdisk-linux , and i can confirm that PR fixes the wrong text message.

**Review by raveit65 — APPROVED** [review]
LGTM

**Review by lukefromdc — APPROVED** [review]
From what I understand a file cannot be moved to a different filesystem, only copied there and deleted from the source directory. If caja supports doing that as a "move" operation than yes, this is needed. It works so approving. The dialog worked fine when I tested attempting to copy a big video file into a bootable flash drive's boot partition

**Comment by basicmaster** [comment]
> From what I understand a file cannot be moved to a different filesystem, only copied there and deleted from the source directory. If caja supports doing that as a "move" operation than yes, this is needed.

This is indeed what caja is doing here when moving a file. Usually [GLib's `g_file_move`](https://docs.gtk.org/gio/method.File.move.html) (called by caja) already takes care of this.

**Pull request merged**
