### PR TITLE
test-eel-labeled-image: Fix showing the image on the controls

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by lukefromdc** [comment]
How do I test this?`  caja -c` is a command line check, doesn't display images anywhere, and completes fine. The code change looks like a cleanup of a remnant error from the original fork from Nautilius

**Comment by rbuj** [comment]
just run the command below from a command line:
```
$ ./test/test-eel-labeled-image
```
Screenshot at 2020-11-13 14-36-41

**Review by lukefromdc — APPROVED** [review]
Oh yeah: this works (icons shown), and in master the icons are NOT shown. 

Question on memory management: I assume exiting the test is considered exiting an entire program so all the variables are then cleaned up? If not, I notice we have one new variable, the icon theme declared with 
`GtkIconTheme *icon_theme = NULL;`
and I don't see anything to unref or free this. I don't know if this is an issue or not, as I don't know whether everything gets cleaned up when the test exits or not. 

Beyond that, this definately works so approving

**Comment by raveit65** [comment]
Confirmed.
```
[rave@mother caja-dist]$ ./test/test-eel-labeled-image

** (lt-test-eel-labeled-image:163117): CRITICAL **: 13:30:13.790: test_pixbuf_new_named: assertion 'pixbuf != NULL' failed
^C
[rave@mother caja-dist]$
```

**Review by raveit65 — APPROVED** [review]
Works fine and displays the icon-image again.

**Comment by raveit65** [comment]
Bildschirmfoto zu 2020-11-15 13-45-57
`/test/.libs/test-eel-labeled-image` is a separate process which closed fine. So, we can't get a leak here.

**Pull request merged**
