### PR TITLE
Fix warnings about xmlChar cast

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
Builds and runs fine, but did not fix https://github.com/mate-desktop/caja/issues/1480
Nothing wrong with it and the warnings need to be fixed so approved. Issue I am dealing with must be elsewhere

**Comment by lukefromdc** [comment]
This does of course break reverting https://github.com/mate-desktop/caja/commit/40f061c638ae125fc6a4170807fa890362050e0f in my local builds of caja, so I will have to find a way to fix that locally

**Comment by lukefromdc** [comment]
I do still get these warnings at least in a new --disable-nls build:

```
eel-xml-extensions.c: In function ‘eel_xml_get_child_by_name_and_property’:
eel-xml-extensions.c:61:26: warning: pointer targets in passing argument 1 of ‘strcmp’ differ in signedness [-Wpointer-sign]
   61 |         if (strcmp (child->name, child_name) == 0)
      |                     ~~~~~^~~~~~
      |                          |
      |                          const xmlChar * {aka const unsigned char *}
In file included from /usr/include/glib-2.0/glib/gslice.h:26,
                 from /usr/include/glib-2.0/glib.h:79,
                 from eel-xml-extensions.h:29,
                 from eel-xml-extensions.c:26:
/usr/include/string.h:137:32: note: expected ‘const char *’ but argument is of type ‘const xmlChar *’ {aka ‘const unsigned char *’}
  137 | extern int strcmp (const char *__s1, const char *__s2)
      |                    ~~~~~~~~~~~~^~~~
eel-xml-extensions.c:63:43: warning: pointer targets in passing argument 2 of ‘xmlGetProp’ differ in signedness [-Wpointer-sign]
   63 |             property = xmlGetProp (child, property_name);
      |                                           ^~~~~~~~~~~~~
      |                                           |
      |                                           const char *
In file included from eel-xml-extensions.h:28,
                 from eel-xml-extensions.c:26:
/usr/include/libxml2/libxml/tree.h:1030:22: note: expected ‘const xmlChar *’ {aka ‘const unsigned char *’} but argument is of type ‘const char *’
 1030 |       const xmlChar *name);
      |       ~~~~~~~~~~~~~~~^~~~
eel-xml-extensions.c:64:33: warning: pointer targets in passing argument 1 of ‘eel_strcmp’ differ in signedness [-Wpointer-sign]
   64 |             match = eel_strcmp (property, property_value) == 0;
      |                                 ^~~~~~~~
      |                                 |
      |                                 xmlChar * {aka unsigned char *}
In file included from eel-xml-extensions.c:28:
eel-string.h:47:60: note: expected ‘const char *’ but argument is of type ‘xmlChar *’ {aka ‘unsigned char *’}
   47 | int      eel_strcmp     
```

**Comment by lukefromdc** [comment]
Using --disable-nls again had no effect, though note that https://github.com/mate-desktop/caja/commit/40f061c638ae125fc6a4170807fa890362050e0f changes some functions unconditionally

**Comment by rbuj** [comment]
all xmlChar cast warnings should be fixed now

**Comment by lukefromdc** [comment]
I can confirm the XML warnings are gone now

**Review by raveit65 — APPROVED** [review]
LGTM,
warnings are gone and i see no issues in a quick test.

**Comment by lukefromdc** [comment]
Still no effect on https://github.com/mate-desktop/caja/issues/1480 even when combined with the "do not build the path" PR affecting this dialog that was just merged, but I now suspect a local XML issue may be behind that as nobody else has been able to duplicate that bug

**Pull request merged**
