### PR TITLE
Backport verify_destination from Nautilus - Symlink and freespace fixes

### PR DESCRIPTION
**Pull request by rcaridade145**
Should help with the symlink issues like #315 , #947 , #748 . This version also verifies the amount of freespace available before copy.

### CODE REVIEW

**Comment by lukefromdc** [comment]
Note that with g_autofree only gcc and clang can build the code (see https://github.com/dunst-project/dunst/issues/522) but I'm not sure we need to worry about this at all, and if this is a backport from GNOME they don't either.

**Comment by rcaridade145** [comment]
@raveit65  The commit I first looked into was https://gitlab.gnome.org/GNOME/nautilus/commit/f83d19ac913964240515338e8858977cf6632157 but ended up porting the latest version of the code. This commit mentions issue #947 but the code is from master. At least #947 ought to be solved by this.

**Comment by rcaridade145** [comment]
#748  is already fixed by the last backport on #1058 . Sorry for the confusion with all these backports :/

**Comment by raveit65** [comment]
I don't get why origin patch from https://github.com/mate-desktop/caja/issues/947 or https://bugzilla.redhat.com/show_bug.cgi?id=1554084
only edit 3 lines.
And you edit much more code.

**Comment by raveit65** [comment]
No answer from author since nealy 1 year, closing this one. We can re-open PR if someone start again to work on it.

**Pull request closed without merging**
