### PR TITLE
Clang analyzer

### PR DESCRIPTION
**Pull request by yetist**
Let me try, if every thing is ok, the `gh-pages` branch will have many html files.

EDIT: The result can view at https://mate-desktop.github.io/caja

### CODE REVIEW

**Comment by yetist** [comment]
@rbuj @sc0w @raveit65

Strange result, clang on fedora can't build caja, https://travis-ci.org/mate-desktop/caja/builds/497356003

But it can build marco https://travis-ci.org/mate-desktop/marco/builds/497355571

**Comment by yetist** [comment]
Error from this command line:
```
[root@1ecc703197b8 libcaja-extension]# /usr/bin/../libexec/ccc-analyzer -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -Wall -Werror=format-security -fPIC -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/fribidi -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/gio-unix-2.0 -I/usr/include/gtk-3.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/rootdir -I/rootdir -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/uuid -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/libdrm -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -c /rootdir/libcaja-extension/tmp-introspectcln0d7nb/Caja-2.0.c -o /rootdir/libcaja-extension/tmp-introspectcln0d7nb/Caja-2.0.o -Wno-deprecated-declarations -pthread -pthread
could not find clang line
[root@1ecc703197b8 libcaja-extension]# echo $?
1
```

**Comment by raveit65** [comment]
I am not familiar with clang but maybe `clang-tools-extra` is missing.
```
[root@mother rave]# dnf search clang | grep x86_64
Letzte Prüfung auf abgelaufene Metadaten: vor 0:24:41 am Sa 23 Feb 2019 08:49:56 CET.
clang.x86_64 : A C language family front-end for LLVM
clang-libs.x86_64 : Runtime library for clang
clang-libs.x86_64 : Runtime library for clang
clang6.0-libs.x86_64 : Runtime library for clang
clang-tools-extra.x86_64 : Extra tools for clang
clang5.0-libs.x86_64 : Runtime library for clang
clang6.0-libs.x86_64 : Runtime library for clang
python2-clang.x86_64 : Python2 bindings for clang
clang-devel.x86_64 : Development header files for clang
clang5.0-devel.x86_64 : Development header files for clang.
clang6.0-devel.x86_64 : Development header files for clang.
git-clang-format.x86_64 : Integration of clang-format for git
american-fuzzy-lop-clang.x86_64 : Clang and clang++ support for
american-fuzzy-lop-clang-fast.x86_64 : Fast clang and clang++ support for
libomp.x86_64 : OpenMP runtime for clang
libomp.x86_64 : OpenMP runtime for clang
csclng.x86_64 : A compiler wrapper that runs Clang in background
clazy.x86_64 : Qt oriented code checker based on clang framework
iwyu.x86_64 : C/C++ source files #include analyzer based on clang
bear.x86_64 : Tool that generates a compilation database for clang tooling
[root@mother rave]# dnf search clang | grep noarch
Letzte Prüfung auf abgelaufene Metadaten: vor 0:25:04 am Sa 23 Feb 2019 08:49:56 CET.
rust-clang-sys-devel.noarch : Rust bindings for libclang
rust-clang-sys+default-devel.noarch : Rust bindings for libclang
rust-clang-sys+runtime-devel.noarch : Rust bindings for libclang
rust-clang-sys+clang_3_5-devel.noarch : Rust bindings for libclang
rust-clang-sys+clang_3_6-devel.noarch : Rust bindings for libclang
rust-clang-sys+clang_3_7-devel.noarch : Rust bindings for libclang
rust-clang-sys+clang_3_8-devel.noarch : Rust bindings for libclang
rust-clang-sys+clang_3_9-devel.noarch : Rust bindings for libclang
rust-clang-sys+clang_4_0-devel.noarch : Rust bindings for libclang
rust-clang-sys+clang_5_0-devel.noarch : Rust bindings for libclang
rust-clang-sys+clang_6_0-devel.noarch : Rust bindings for libclang
rust-clang-sys+clang_7_0-devel.noarch : Rust bindings for libclang
rust-clang-sys+libloading-devel.noarch : Rust bindings for libclang
rust-clang-sys+gte_clang_3_6-devel.noarch : Rust bindings for libclang
rust-clang-sys+gte_clang_3_7-devel.noarch : Rust bindings for libclang
rust-clang-sys+gte_clang_3_8-devel.noarch : Rust bindings for libclang
rust-clang-sys+gte_clang_3_9-devel.noarch : Rust bindings for libclang
rust-clang-sys+gte_clang_4_0-devel.noarch : Rust bindings for libclang
rust-clang-sys+gte_clang_5_0-devel.noarch : Rust bindings for libclang
rust-clang-sys+gte_clang_6_0-devel.noarch : Rust bindings for libclang
rust-clang-sys+gte_clang_7_0-devel.noarch : Rust bindings for libclang
rust-clang-sys+assert-minimum-devel.noarch : Rust bindings for libclang
texlive-sclang-prettifier-doc.noarch : Documentation for sclang-prettifier
csmock-plugin-clang.noarch : csmock plug-in providing the support for Clang
clang-analyzer.noarch : A source code analysis framework
texlive-sclang-prettifier.noarch : Prettyprinting SuperCollider source code
```

**Comment by yetist** [comment]
https://github.com/mesonbuild/meson/issues/4709#issuecomment-451514839
* clang-analyzer uses Python's distutils to compile code (or something like this)
* distutils uses Python's embedded CFLAGS which on fedora include those flags which Clang doesn't support
* Then clang-analyzer simply fails.

It seems a python distutils bug on fedora.

**Comment by rbuj** [comment]
[clang-tools-extra](https://clang.llvm.org/extra/index.html) is not required for static analizer.

**Comment by yetist** [comment]
After patching fedora, everything is fine.
The patch can be found here: https://github.com/mate-desktop/mate-dev-scripts/blob/travis/travis/fedora.sh
The results of the analysis can be found here: https://mate-desktop.github.io/caja

**Comment by raveit65** [comment]
Looks like this needs to be reported to fedora?

**Comment by raveit65** [comment]
omg, we have security issues.

**Comment by raveit65** [comment]
Why we have this warnings in `clang` part for fedora build?
```
travis_fold:end:dpl.1
Logged in as @yetist (Wu Xiaotian)
travis_fold:start:dpl.2
[33mPreparing deploy[0m
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment#Uploading-Files-and-skip_cleanup.
Saved working directory and index state WIP on (no branch): 4378057 patch fedora dirsto
warning: failed to remove autom4te.cache/traces.0: Permission denied
warning: failed to remove autom4te.cache/requests: Permission denied
warning: failed to remove autom4te.cache/output.3: Permission denied
warning: failed to remove autom4te.cache/output.2: Permission denied
warning: failed to remove autom4te.cache/traces.1: Permission denied
warning: failed to remove autom4te.cache/traces.2: Permission denied
warning: failed to remove autom4te.cache/traces.3: Permission denied
warning: failed to remove autom4te.cache/output.0: Permission denied
warning: failed to remove autom4te.cache/output.1: Permission denied
warning: failed to remove docs/reference/libcaja-extension/.libs/lt-libcaja-extension-scan: Permission denied
warning: failed to remove docs/reference/libcaja-extension/.libs/libcaja-extension-scan: Permission denied
warning: failed to remove docs/reference/libcaja-extension/.libs/libcaja-extension-scan.o: Permission denied
warning: failed to remove docs/reference/libcaja-extension/html/ch01.html: Permission denied
warning: failed to remove docs/reference/libcaja-extension/html/left.png: Permission denied
warning: failed to remove docs/reference/libcaja-extension/html/CajaMenuProvider.html: Permission denied
warning: failed to remove docs/reference/libcaja-extension/html/pt01.html: Permission denied
warning: failed to remove docs/reference/libcaja-extension/html/CajaFileInfo.html: Permission denied
warning: failed to remove docs/reference/libcaja-extension/html/up.png: Permission denied
warning: failed to remove docs/reference/libcaja-extension/html/home.png: Permission denied
......
---and so on...
```

**Comment by yetist** [comment]
I set up the deployment only in the fedora environment, and the warning was generated during the deployment phase.

The reason is that in the docker container, the root user is used to compile, so the generated files are all owned by root.

The deployment phase is running on the host using normal users. and `skip_cleanup` is not set in `deploy`, so the git working directory will be cleaned up, but there is no permission to delete files created by the root user.

**Comment by yetist** [comment]
Clang Analyzer results of e9d6e91745b4f1d2b8aa6a7e641851ddfb76fc5b at https://mate-desktop.github.io/caja/

**Comment by yetist** [comment]
Clang Analyzer results of e9d6e91745b4f1d2b8aa6a7e641851ddfb76fc5b at https://mate-desktop.github.io/caja/

**Comment by yetist** [comment]
Clang Analyzer results of e9d6e91745b4f1d2b8aa6a7e641851ddfb76fc5b at https://mate-desktop.github.io/caja/

**Comment by yetist** [comment]
Clang Analyzer results of e9d6e91745b4f1d2b8aa6a7e641851ddfb76fc5b at https://mate-desktop.github.io/caja/

**Comment by yetist** [comment]
Clang Analyzer results of 5aaab9879b2ebd77293f19281fa666fccc26ee54 at https://mate-desktop.github.io/caja/

**Comment by yetist** [comment]
Clang Analyzer results of 5aaab9879b2ebd77293f19281fa666fccc26ee54 at https://mate-desktop.github.io/caja/

**Comment by yetist** [comment]
Clang Analyzer results of 5aaab9879b2ebd77293f19281fa666fccc26ee54 at https://mate-desktop.github.io/caja/

**Comment by yetist** [comment]
Clang Analyzer results of 5aaab9879b2ebd77293f19281fa666fccc26ee54 at https://mate-desktop.github.io/caja/

**Comment by selectiveduplicate** [comment]
That's a lot of bugs! :open_mouth:

**Comment by yetist** [comment]
Clang Analyzer results of 6ad999d189035b7e550239dc0ca1800868f372b2 at https://mate-desktop.github.io/caja/

**Comment by yetist** [comment]
Clang Analyzer results of 6ad999d189035b7e550239dc0ca1800868f372b2 at https://mate-desktop.github.io/caja/

**Comment by yetist** [comment]
Clang Analyzer results of 6ad999d189035b7e550239dc0ca1800868f372b2 at https://mate-desktop.github.io/caja/

**Comment by yetist** [comment]
Clang Analyzer results of 6ad999d189035b7e550239dc0ca1800868f372b2 at https://mate-desktop.github.io/caja/

**Comment by yetist** [comment]
Clang Analyzer results of c3db8fe2365f7c9111538fddf361e0e8c1b5c9a7 at https://mate-desktop.github.io/caja/

**Comment by yetist** [comment]
[Notification]: Clang Analyzer results of 63b8fc86a44c48ea279af35615c12dce7d8361ab at https://mate-desktop.github.io/caja/

**Comment by sc0w** [comment]
@yetist please, can you change the "notifications behavior", like you did in https://github.com/mate-desktop/mate-panel/pull/941 ?

**Comment by yetist** [comment]
@sc0w 

Done, and rebase at master,  so new results will see less issues.

**Comment by yetist** [comment]
Rebase on master, so we can see fewer warning messages.
If merge it into master, the results page will be updated automatically, please review @mate-desktop/core-team

**Comment by raveit65** [comment]
I didn't really follow this topic the last weeks becauce or releasing, .....sorry.
https://caja.mate-desktop.dev/ is part of your site?
If yes, thanks for that.
I hope that i get access to our main site and that we can use it for this feature.

**Comment by raveit65** [comment]
Answer my question for myself :)
gh-pages is part of github , found that in settings.

**Comment by yetist** [comment]
@raveit65 

Now use github pages with a custom domain name, see https://help.github.com/en/articles/using-a-custom-domain-with-github-pages
The mate-desktop.dev is the new domain name I registered last week. I think this domain name is better for development websites. Currently it is only used on github pages to view clang analyzer results.
If the team members like it, I can transfor this domain name to you or our leader.

**Comment by yetist** [comment]
Rebase on master branch, and switch to use build scripts on master branch.

**Comment by sc0w** [comment]
mate desktop 1.22, the "phantom" version, because there is no official announcement

how much time we need to wait to the next movement and use another domain?

+1 for https://www.mate-desktop.dev

**Comment by raveit65** [comment]
> how much time we need to wait to the next movement and use another domain?

You only need to help to contact @flexiondotorg 
PS: Sometimes people have serious personal reasons for their doing..........

> Now use github pages with a custom domain name, see https://help.github.com/en/articles/using-a-custom-domain-with-github-pages
The mate-desktop.dev is the new domain name I registered last week. I think this domain name is better for development websites. Currently it is only used on github pages to view clang analyzer results.
If the team members like it, I can transform this domain name to you or our leader.

Thanks explanation, using a custom domain name for gh-pages is a good idea.
I don't think that we have have a leader. In my understanding mate-desktop  is more a group of people  with equal rights but different task areas.
And @flexiondotorg task was to manage the website.
He was at irc mate-dev this Tuesday again and promised to fix Nicola deployment for website which is broken.
And i ask him to give @monsta an me access to server, than we can manage problems for ourself next time.
Please be patient for a while.

**Comment by raveit65** [comment]
Do we need clang-analyzer on stable branches?
Seems to be sufficient to have it only on master for me, or not?

**Comment by yetist** [comment]
> Do we need clang-analyzer on stable branches?

I don't think it's necessary to do code analysis on the stable branch, as long as cherry-pick some PR to the stable branch is enough, if the release-server development is complete, add it at most.

If we have control over the domain name, we can temporarily use the github pages to display the site, so that we can have a 1.22 release note.

https://yetist.mate-desktop.dev is an example for previewing PR, using a custom domain name to access the github pages of the project, here I have migrated nikola to the latest version and compiled the latest commit on master branch.

**Comment by sc0w** [comment]
@yetist 

it seems when new report is created, the previous is removed instead the last, it is possible to remove always the last instead the previous?

I mean, I think is better to remove always the oldest report

**Comment by raveit65** [comment]
> I mean, I think is better to remove always the oldest report

Yes, that's better.

**Comment by yetist** [comment]
This will keep the latest 10 records, the oldest records will be deleted automatically.

**Comment by sc0w** [comment]
@yetist 

These reports are there permanently, never are removed

**Comment by yetist** [comment]
@sc0w 

You are right, my script is wrong. I created a PR to fix this https://github.com/mate-desktop/mate-dev-scripts/pull/17

**Comment by yetist** [comment]
@sc0w 

mate-desktop/mate-dev-scripts#17 has been merged, then if caja has a new build, the expected result is `2019-03-01-092612-7263-1@b962d4c4701e` deleted, and new log added.

**Comment by sc0w** [comment]
(offtopic) I noticed **nemo** uses `codacy` in PRs ( https://www.codacy.com )



https://app.codacy.com/app/cinnamon/nemo/pullRequests

@mate-desktop/core-team do you think this is good to add for mate-desktop PRs ?

**Comment by sc0w** [comment]
I forked caja to test, and codacy works fine

PR with codacy check:

https://github.com/sc0w/caja/pull/1

we have 682 issues (61 security issues):

https://app.codacy.com/project/sc0w/caja/dashboard

https://app.codacy.com/app/sc0w/caja/issues

**Pull request merged**
