### PR TITLE
Fix plural forms for slovak language

### PR DESCRIPTION
**Pull request by prescott66**

### CODE REVIEW

**Comment by raveit65** [comment]
I don't think that is the right file and place to fix it, because every pull from transifex will override *.po files!

**Comment by prescott66** [comment]
Oh! I dont knew that....So can i fix it via Transifex?

**Comment by raveit65** [comment]
@sc0w 
How we did fix this problem in the past with eom?
A transifex admin needs to upload a fixed .po file by hand to transifex server?

**Comment by raveit65** [comment]
Let us try something.
1. I will pull latest translation for (sk) from transifex, to be sure to have latest version here at github.
2. I will apply your fix.
3. Than i will upload modfied sk.po to transifex.
4. After i will ping you to get a feedback :)

**Comment by prescott66** [comment]
OK. infor me please if it works and i will finish creating pull requests for rest of apps :smiley:

**Comment by sc0w** [comment]
I think plural forms can't be changed because they are automatically made it by transifex

Documentation:
https://docs.transifex.com/localization-tips-workflows/plurals-and-genders

Transifex follow this rues:
https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html

For slovak: one, few, many, other.

@prescott66 if you think this is wrong, you can contact to transifex in support@transifex.com

**Comment by prescott66** [comment]
@sc0w  i see this for the first time in my life...in whole GNOME and KDE we are using form:
nplurals=3; plural=(n==1) ? 1 : (n>=2 && n<=4) ? 2 : 0

**Comment by raveit65** [comment]
Beside from that building is broken with that commit.
https://travis-ci.org/github/mate-desktop/caja/jobs/679369057#L1512
```
sk.po:17: nplurals = 3...

sk.po:1403: ...but some messages have 4 plural forms

/usr/bin/msgfmt: found 1 fatal error

sk.po: 1464 translated messages, 137 untranslated messages.

make[3]: *** [Makefile:297: sk.gmo] Error 1
```

**Comment by prescott66** [comment]
@raveit65 i think it is because i forgot to remove the useless form from translation...anyway this pull request is useless because transifex will override it.

**Comment by sc0w** [comment]
@prescott66 

> i see this for the first time in my life...in whole GNOME and KDE we are using form:
> nplurals=3; plural=(n==1) ? 1 : (n>=2 && n<=4) ? 2 : 0

because they don't use transifex

please contact to support@transifex.com

**Comment by sc0w** [comment]
btw, I see 4 plural forms for slovak in:

https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html

**Comment by raveit65** [comment]
Yes, transifex support should know how to fix this problem.

**Comment by prescott66** [comment]
@sc0w we never used form "many" in apps, so it is really unused....When you open translation in Poedit, it tells you, that this form is unused.
ok, i will write to transifex support.
thanks!

**Comment by raveit65** [comment]
Any news from transifex?

**Pull request closed without merging**
