### PR TITLE
Fix cast from non-struct type to struct type

### PR DESCRIPTION
**Pull request by sc0w**
Fix cast from non-struct type to struct type

Fixes Clang static analyzer warnings:

```
eggsmclient-xsmp.c:1156:18: warning: Casting a non-structure type to a structure type and accessing a field can lead to memory access errors or data corruption
    prop->vals = (SmPropValue *)vals->data;
                 ^~~~~~~~~~~~~~~~~~~~~~~~~

eggsmclient-xsmp.c:1189:18: warning: Casting a non-structure type to a structure type and accessing a field can lead to memory access errors or data corruption
    prop->vals = (SmPropValue *)vals->data;
                 ^~~~~~~~~~~~~~~~~~~~~~~~~

caja-file-utilities.c:283:12: warning: Casting a non-structure type to a structure type and accessing a field can lead to memory access errors or data corruption
    return (XdgDirEntry *)g_array_free (array, FALSE);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

caja-property-browser.c:1242:45: warning: Casting a non-structure type to a structure type and accessing a field can lead to memory access errors or data corruption
    CajaPropertyBrowser *property_browser = CAJA_PROPERTY_BROWSER (data);
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

caja-property-browser.c:1414:45: warning: Casting a non-structure type to a structure type and accessing a field can lead to memory access errors or data corruption
    CajaPropertyBrowser *property_browser = CAJA_PROPERTY_BROWSER (data);
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

caja-property-browser.c:1450:45: warning: Casting a non-structure type to a structure type and accessing a field can lead to memory access errors or data corruption
    CajaPropertyBrowser *property_browser = CAJA_PROPERTY_BROWSER(data);
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### CODE REVIEW

**Comment by sc0w** [comment]
I did the same change with the remaining files with the same warnings

**Comment by sc0w** [comment]
@yetist @raveit65 

new push error in travis:

```
$ ./docker-build --name ${DISTRO} --config .travis.yml --install
./docker-build: line 7: syntax error near unexpected token `newline'
./docker-build: line 7: `<!DOCTYPE html>'
The command "./docker-build --name ${DISTRO} --config .travis.yml --install" failed and exited with 2 during .
Your build has been stopped.
```

**Comment by yetist** [comment]
I think you should rebase this PR on master branch.

**Comment by sc0w** [comment]
@yetist thanks!

**Comment by sc0w** [comment]
I added one more commit to fix the same warnings in `caja-property-browser.c`, and now all the related warnings in caja are gone

**Comment by monsta** [comment]
Changing `CAJA_PROPERTY_BROWSER (data)` to `CAJA_PROPERTY_BROWSER (*data)` adds one more pointer dereference, that's what most probably causes that crash.

**Comment by sc0w** [comment]
@vkareh please test again

**Pull request merged**
