### PR TITLE
GTK3: port libunique ->GtkApplication

### PR DESCRIPTION
**Pull request by lukefromdc**
Port GTK 3 builds from libunique to GtkApplication, leave GTK2 builds alone. 

Change startup system in GTK3/GtkApplication builds to same as that used in Nemo and Nautilus, with a desktop file in /etc/XDG/autostart as using the file in /usr/share/applications hangs mate-session-manager until a failed attempt to register Caja times out. With GTK3 the key desktop>session.required-components>File Manager is now silently ignored and does not hang the session, caja starts from the file in /etc/.XDG/autostart same as Nautilus or Nemo.

Distcheck completes in GTK3 test, test builds completed in both GTK3 and GTK2 but could not run GTK2 version in a MATE GTK3 environment, thus could not complete distcheck for GTK2 build in GTK3 MATE environment either as this requires test execution.

### CODE REVIEW

**Comment by sc0w** [comment]
I think you must change some references to libunique on configure.ac

This seems to be fine, I dont have tested:

```patch
diff --git a/configure.ac b/configure.ac
index d52fef5..d7aa9da 100644
--- a/configure.ac
+++ b/configure.ac
@@ -45,7 +45,6 @@ case "$with_gtk" in
   3.0) GTK_API_VERSION=3.0
        GTK_REQUIRED=3.0.0
        GAIL_API_VERSION=-3.0
-       LIBUNIQUE_VERSION=3.0
        ;;
 esac
 AC_SUBST([GTK_API_VERSION])
@@ -229,17 +228,19 @@ fi
 #============================================================================
 # libunique
 #============================================================================
-PKG_CHECK_MODULES(UNIQUE, unique-$LIBUNIQUE_VERSION)
+if test "$GTK_API_VERSION" = "2.0"; then
+	PKG_CHECK_MODULES(UNIQUE, unique-$LIBUNIQUE_VERSION)
 
-AC_SUBST([UNIQUE_CFLAGS])
-AC_SUBST([UNIQUE_LIBS])
+	AC_SUBST([UNIQUE_CFLAGS])
+	AC_SUBST([UNIQUE_LIBS])
 
-# this deprecated stuff should be removed from unique in most distros
-# but it's still not removed upstream in unique 1.x, so leaving it alone
-# just in case.
-UNIQUE_CFLAGS="$UNIQUE_CFLAGS -DG_CONST_RETURN=const"
+	# this deprecated stuff should be removed from unique in most distros
+	# but it's still not removed upstream in unique 1.x, so leaving it alone
+	# just in case.
+	UNIQUE_CFLAGS="$UNIQUE_CFLAGS -DG_CONST_RETURN=const"
 
-EXTRA_CORE_MODULES="$EXTRA_CORE_MODULES unique-$LIBUNIQUE_VERSION"
+	EXTRA_CORE_MODULES="$EXTRA_CORE_MODULES unique-$LIBUNIQUE_VERSION"
+fi
 
 
 # ==========================================================================

**Comment by lukefromdc** [comment]
Just tested your patch, it worked fine here so I added it to the PR, but a test on my system might be inconclusive due to the forced workaround for https://github.com/mate-desktop/mate-common/issues/19, which required me to comment out the version checks in mate-autogen to get past a "shift" error in configuring any MATE package after a round of Debian updates.

I did not want to experiment with this locally because that could have invalidated any code I wrote that interacted with the version checks,  Someone who does not have to deal with  https://github.com/mate-desktop/mate-common/issues/19 needs to retest this as a result.

Thanks for the patch, the whole point of this PR is to permit Caja to be built after Debian (and possibly other distros) stops shipping libunique. The other option would be to scratch this PR and instead package libunuique itself into cut-n-paste code along with libegg.

**Comment by raveit65** [comment]
> but a test on my system might be inconclusive due to the forced workaround for mate-desktop/mate-common#19, which required me to comment out the version checks in mate-autogen to get past a "shift" error in configuring any MATE package after a round of Debian updates.

Instead of autogen use 'autoreconf -fi', which does the same work.
I will test the PR now.

**Comment by raveit65** [comment]
I don't think that we need to change the caja start behaviour in session.
I simply edit /usr/share/applications/caja.desktop
Exec=caja --> Exec=caja -n (n= --no-default-window)
Than  caja starts well in session without opening a browser window.
I just tested this w/o applying 'fix session start same as nemo/nautilus' + corrections.
In both cases, w or w/o using autostart folder, caja dont restart after a 'killall caja'.
So changing the start behaviour is quite useless.

Beside from this i noticed no regressions at this point and caja works well.

**Comment by raveit65** [comment]
I found a warning in ~.xsession-errors if gebug is enabled.
```
mate-session[4512]: WARNING: Application 'caja.desktop' failed to register before timeout
mate-session[4512]: DEBUG(+): GsmManager: ending phase DESKTOP

mate-session[4512]: DEBUG(+): GsmManager: starting phase APPLICATION
```
Caja failed to register to session-manager and auto-restart failed for this reason.

**Comment by lukefromdc** [comment]
That timeout is what hangs opening any part of the session that opens
after caja if the file in /usr/share/applications is used for autostarting.

**Comment by lukefromdc** [comment]
I finally manage to port the very important Nautilus commit 
https://github.com/GNOME/nautilus/commit/5c949fffcb0de62fd5375f546fa94dd50ec7f86f#diff-04a360d9a81aa820dff5b4e1ae10f971R940 that rewrites command line handling and fixes both the help a "caja ." bugs correctly to Caja.

https://github.com/lukefromdc/caja/commit/2c3a304cf8085a4535ee5df3d172a2da7815c613
Sets up new branch
https://github.com/lukefromdc/caja/tree/dev-GtkApplication2
and recommended replacement PR
https://github.com/mate-desktop/caja/pull/614

I could merge the new commit  back into this PR but decided to use a separate branch (and thus PR) just in case

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/pull/614
is not quite ready, I am chasing a segfault when opening a directory in --no-desktop mode and I am out of time tonight. The older PR is well tested, been using this code quite a while. I'll have the newer code ready soon as well.

**Comment by lukefromdc** [comment]
Where things stand right now I simply cannot get rid of the old Nautilus 3.0 bug https://bugzilla.gnome.org/show_bug.cgi?id=649336 without causing Caja to segfault on opening a folder in --no-desktop mode. That alone I have at least 12 hours in. Debian is asking us to do a very difficult job in porting over Caja, I don't think they realized how complex the changes in Nautilus really are.  I must have 60+ hours in this and little help from their presumably far more experienced coders. 

I just looked at libunique on Github, it's a fairly complex program so if we wanted to simply include it in Caja we'd have to drop the entire build directory into ours and build it in place-and hope nothing broke THAT build.   I suggest we make a decision that if Debian insists on dropping libunique we make it a MATE package as a whole, after all it too seems to orginate with GNOME and has seen no work in many years.

It's also possible to simply write libunique out of Caja and not replace it. 
https://github.com/lukefromdc/caja/commit/a843a9eb582dda764bae759b8e96d2a5a63e3465
I limited libunique to GTK2 builds in the first step of porting over code to use GtkApplication in GTK3 builds. With neither libunique nor GtkApplication,  each invocation of Caja becomes a separate process. That means caja --quit would be ignored, and that if the session is being saved with open Caja windows only those opened from the desktop (the instance called by the session manager) would be saved. An advantage exists as well to separate processes: if one crashes the rest stay up.

**Comment by raveit65** [comment]
It's OK, we should first fell a decision, no need to spend more time at this moment.

**Comment by lukefromdc** [comment]
Distcheck note: with auto-restart and running in a mate-session, caja will have to be killed once when distcheck hangs on the multiple instance/GtkApplication issue. It will restart and distcheck will then run to completion, being past that hangup. Alternately run make-distcheck from a session other than MATE or from the console.

**Comment by raveit65** [comment]
Don't worry about distcheck at the moment, the test part checks on real file system for some reason.
I did run in a distcheck issue for caja-1.15.4 caused by a gtk theme issue 2 days ago ;)

**Comment by lukefromdc** [comment]
https://github.com/lukefromdc/caja/tree/dev-GtkApplication2
has been debugged and rebased.

Behavior now matches the older dev-GtkApplication branch except that
https://bugzilla.gnome.org/show_bug.cgi?id=649336  is finally gone. The segfault I chased for two days turned out to be the loop that handles calling caja with multiple locations overrunning the number of locations due to a comparison that did not always work. Finally fixed it.

Two remaining things: caja --quit does not work, and I would like to get saving the session (open folders) to work now that the session manager startup works. That would yield a drop-in replacement for caja with libunique for GTK3 builds. Things like spatial windows, automounting drives at startup, and turning desktop icons on and off all just plain work.

**Comment by raveit65** [comment]
Just tested both the PR and dev-GtkApplication2.
Caja is controlled by session again and auto-restart works, but i can't start caja with sudo anymore.
On the other side starting caja as root works well, which has never work before.
stacktrace with dev-GtkApplication2 branch and sudo command.
```
Thread 1 (Thread 0x7f8d50be1a80 (LWP 5405)):
#0  0x00007f8d4bce2936 in __strcmp_ssse3 () at ../sysdeps/x86_64/strcmp.S:173
#1  0x00007f8d4cf9b5d9 in g_str_equal (v1=<optimized out>, v2=v2@entry=0x7f8d4edb7b1d) at ghash.c:1846
        string1 = <optimized out>
        string2 = 0x7f8d4edb7b1d "org.gnome.SessionManager"
#2  0x00007f8d4ed2ae23 in gtk_application_impl_dbus_startup (impl=0x560542ba35a0 [GtkApplicationImplX11], register_session=<optimized out>) at gtkapplication-dbus.c:240
        dbus = 0x560542ba35a0 [GtkApplicationImplX11]
        client_id = 0x560542bc7280 ""
        error = 0x0
        res = 0x0
        same_bus = <optimized out>
        bus_name = <optimized out>
        client_interface = <optimized out>
#3  0x00007f8d4ea43d37 in gtk_application_startup (g_application=<optimized out>) at gtkapplication.c:296
        application = 0x560542b49240 [CajaApplication]
#4  0x0000560540cbcfc1 in caja_application_startup (app=0x560542b49240 [CajaApplication]) at caja-application.c:3003
        self = 0x560542b49240 [CajaApplication]

**CUT**

#8  0x00007f8d4d568102 in g_application_register (application=application@entry=0x560542b49240 [CajaApplication], cancellable=cancellable@entry=0x0, error=error@entry=0x7ffc5783fa50) at gapplication.c:2049
        __func__ = "g_application_register"
```
full stacktrace: https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/caja-backtrace-GtkApplication-with-sudo
Here caja crashed because a root session org.gnome.SessionManager is missing, imo.

And with dev-GtkApplication2 branch the --browser option is missing.
```
[rave@f25-gtk3 ~]$ caja --no-desktop --browser
(process:6208): GLib-GIO-CRITICAL **: g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed
(process:6208): GLib-CRITICAL **: g_variant_get_type: assertion 'value != NULL' failed
(process:6208): GLib-CRITICAL **: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
(process:6208): GLib-CRITICAL **: g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed
(process:6208): GLib-CRITICAL **: g_variant_unref: assertion 'value != NULL' failed
Could not parse arguments: unknown option --browser
```

Anyway, best state of work on this issue, thank you.

**Comment by raveit65** [comment]
Weird, with caja from PR installed on f24 (gtk+-3.20) i don't have the issue with sudo.

**Comment by lukefromdc** [comment]
Sudo works fine here on Debian Unstable with GTK 3.21 from git master.
The "browser" issue I can bring back, it was a "compatability" match for 
a while in Nautilus since invoking "caja" by itself does the same thing.

I DO get the messages about not finding session managers in sudo, but
I get those too in Nautilus and Nemo. I had trouble with "sudo nemo" for 
a while, came in with one round of GTK updates and then just went away
after more GTK updates. Thus, the sudo issue reported may be specific
to GTK 3.21.4 from the released tarball, I am on master.

Testing is simple: install Nemo and try to run "sudo nemo." If that fails
you've got the GTK issue. Be advised that running Nemo as su root can
cause problems the next time you try to open a MATE session with a 
dconf file in /home being owned by root and requiring deletion.

**Comment by raveit65** [comment]
yes, 'sudo nemo' fails too with gtk+-3.21.4.
Let's see if this fixed in 3.21.5, this can take some time here as we are in alpha freeze.

**Comment by lukefromdc** [comment]
https://github.com/lukefromdc/caja/commit/6cb010e27972ee7fb941f368f4d88e10cbdde5b5 to the GtkApplication2 branch re-enables saving sessions and reloading them. 

Based on 
https://github.com/GNOME/nautilus/commit/7c042f64ee59d9f149252f7e78e11ca6ad7d9dbe but required multiple subtle changes to work in Caja.

**Comment by lukefromdc** [comment]
Closing this one in favor of
 https://github.com/mate-desktop/caja/pull/618
Which has many bugfixes, does not throw new warnings on the command line on a 2nd invocation, and preserves full session management/saving functionality. Also respects --browser option when user invokes spatial mode, save that windows opened from the command line as root had to be set to always open as browser windows due to issues with reading preferences as sudo

**Pull request closed without merging**
