### PR TITLE
Port libunique ->GtkApplication w/ correct command line handling

### PR DESCRIPTION
**Pull request by lukefromdc**
Port GTK 3 builds from libunique to GtkApplication, leave GTK2 builds alone. In GTK 3 builds include Nautlus commit https://github.com/GNOME/nautilus/commit/5c949fffcb0de62fd5375f546fa94dd50ec7f86f#diff-04a360d9a81aa820dff5b4e1ae10f971R940, 
which prevents Caja from importing Nautilus 3.0 bugs 
https://bugzilla.gnome.org/show_bug.cgi?id=649336
and
https://bugzilla.gnome.org/show_bug.cgi?id=637157

Also change startup system in GTK3/GtkApplication builds to same as that used in Nemo and Nautilus, with a desktop file in /etc/XDG/autostart as using the file in /usr/share/applications hangs mate-session-manager until a failed attempt to register Caja times out. With GTK3 the key desktop>session.required-components>File Manager is now silently ignored and does not hang the session, caja starts from the file in /etc/.XDG/autostart same as Nautilus or Nemo.

### CODE REVIEW

**Comment by lukefromdc** [comment]
Just passed distcheck with GTK 3.21.4+git master 8-11-2016

**Comment by lukefromdc** [comment]
Not quite ready, getting a segfault on opening a folder in --no-desktop mode

**Comment by raveit65** [comment]
This really needs a rebase, i see here to much double commits and some should be squashed in previous commits.
This can be done with 'rebase -i commit-id-of-the-last-commit-from-master'
-i means interactive and you will see several options in a vim window.
You can also move the order of the commits there. After that do a 'git push -f' and this PR will be automatic updated. 
I did that with previous PR and the result was 2 commits.

**Comment by lukefromdc** [comment]
That will have to wait until I can fix that segfault issue, which is next in line,
The I can turn the whole mess into a single commit, if necessary in another
branch. All of that was about 8 hours work in a single day-with nasty 
suprises that only turned up after I pushed the initial branch. Probably
worked too long and too late into the night on it for one day.

Obviously Nautilus made it work, I;ve already got some ideas in my head about
how to trace these segfaults coming from URIS not being properly read when
and only when in --no-desktop mode.

The other question is this: how much energy to put into this vs how much if any
to divert into a new branch with libunique locally included in  cut-n-paste code
and not externally depended on? That would let up keep restart and session 
saving, something not offered by Nautilus or by Nemo to my knowledge.

**Comment by lukefromdc** [comment]
Closing as I am still chasing the segfault issue. Will squash or make a new branch for another PR when I get this working

**Pull request closed without merging**
