### PR TITLE
port to gtk_style_context and other fixes

### PR DESCRIPTION
**Pull request by raveit65**
- port gtk_style --> gtk_style_context (most files)
- port GdkColor --> GdkRGBA (most files)
- fixes https://github.com/mate-desktop/caja/issues/445
- fixes https://github.com/mate-desktop/caja/issues/81 (gtk3)
- fixes selected color does not change with gtk theme change (gtk3)

Some theme changes are needed, i will post this later and update our themes.
I know this are a lot of commits and i don't want push this to master w/o testing.
@monsta 
@flexiondotorg 
@lukefromdc
Please test, hopfully i don't introduce a reggression.
Also for gtk2, 2 commits affects gtk2 too.

### CODE REVIEW

**Comment by lukefromdc** [comment]
Confirmed good here GTK3.18 and GTK3.19.6/.

I just build a Debian package from this and installed it, tested with both gtk3.18
and 3.19. Works great even in Adwaita with different text colors in backdrop, and
no flash even when installing a bunch of debs and moving files to the flash drive.

If I don't get issues later, I will upload that Debian package to my archive of MATE
gtk3 packages with a strong recommendation to use it. Should save over 10MB of
RAM on my small laptop (next test) as my flash workaround let to extra RAM use.

**Comment by raveit65** [comment]
I rebased some commits to follow @monsta suggestions.
This should only affect gtk2 build.

**Comment by monsta** [comment]
Cool. BTW, we can use https://github.com/mate-desktop/caja/commit/560345757c7a80a4a31e8bd06a0c75861d546e65 for GTK+2 too - I've tested it today.

**Comment by raveit65** [comment]
yeap, good idea :)

**Comment by raveit65** [comment]
https://github.com/mate-desktop/caja/commit/560345757c7a80a4a31e8bd06a0c75861d546e65 is rebased for using with gtk2 too.

**Pull request merged**
