### PR TITLE
Improved merge folder dialog

### PR DESCRIPTION
**Pull request by sc0w**
based on nautilus commit:
https://git.gnome.org/browse/nautilus/commit/?id=b370817

Fixes partially #535 

**currently:**

modify_caja_folder_before

**with my PR:**

caja_folder_later_classic

we only need to solve: **Null**

By the moment I don't know how to solve it

### CODE REVIEW

**Comment by lukefromdc** [comment]
I can confirm that this builds and runs on GTK 3.22, and that the dialog is cleaned up as shown. There is one difference here though: I don't get the "Items(null)" issue for folder contents, rather I get "Items (0 items)" both with and without this commit. The rest works as described.

**Comment by lukefromdc** [comment]
Merged via https://github.com/mate-desktop/caja/commit/1ca6c5f9c7ced0f906de5dda119cdd37c76d8cfa

**Comment by monsta** [comment]
@sc0w: I have the same results as @lukefromdc - I can't reproduce the "null" problem. The dialog shows "0 items" instead. I used the same steps to reproduce as you posted in https://github.com/mate-desktop/caja/issues/535. Do you still get the issue?

Tested with:
- Caja 1.16.5, GTK+2 build
- Caja 1.16.5, GTK+3 build, GTK+ 3.20.9
- Caja from git master, GTK+ 3.22.11

**Comment by sc0w** [comment]
@monsta ok, thanks for your tests

I see it with caja 1.16.2 gtk 3.22.11

I will try with latest versions

**Pull request merged**
