### PR TITLE
build: allow users to disable gettext support (--disable-nls)

### PR DESCRIPTION
**Pull request by rbuj**
### With NLS
```
$ find /usr/share/locale -type f -name 'caja.mo' -exec sudo rm -f {} +
$ ./autogen.sh --prefix=/usr && make && sudo make install
$ find /usr/share/locale -type f -name 'caja.mo' -exec du -ch {} + | grep total
14M	total
```
### Without NLS
```
$ find /usr/share/locale -type f -name 'caja.mo' -exec sudo rm -f {} +
$ ./autogen.sh --prefix=/usr --disable-nls && make && sudo make install
$ find /usr/share/locale -type f -name 'caja.mo' -exec du -ch {} + | grep total
```

See https://www.gnu.org/software/gettext/manual/gettext.html#INSTALL-Matters

### CODE REVIEW

**Review by lukefromdc — COMMENTED** [review]
Builds and runs fine wth --disable-nls but does NOT fix the "backgrounds and emblems" dialog. I think one of the changed functions rather than translations (I am testing in English) is the culprit there.

**Comment by raveit65** [comment]
What is NLS?
Why is this needed?
Does most Mate users building without gettext support?

**Comment by rbuj** [comment]
NLS means Native Language Support and It's enabled by default unless you use the --disable-nls configure option. We are currently checking whether the NLS support is enabled in the MATE components.
```
$ grep -R ENABLE_NLS --include=*.c
mate-settings-daemon/plugins/a11y-keyboard/test-a11y-preferences-dialog.c:#ifdef ENABLE_NLS
mate-settings-daemon/plugins/media-keys/test-media-keys.c:#ifdef ENABLE_NLS
mate-settings-daemon/plugins/media-keys/test-media-window.c:#ifdef ENABLE_NLS
atril/previewer/ev-previewer.c:#ifdef ENABLE_NLS
atril/shell/ev-window.c:#ifdef ENABLE_NLS
atril/shell/main.c:#ifdef ENABLE_NLS
mate-applets/accessx-status/src/applet.c:#ifdef ENABLE_NLS
mate-applets/battstat/battstat_applet.c:#ifdef ENABLE_NLS
mate-applets/charpick/charpick.c:#ifdef ENABLE_NLS
mate-applets/cpufreq/src/cpufreq-applet.c:#ifdef ENABLE_NLS
mate-applets/drivemount/src/drivemount.c:#ifdef ENABLE_NLS
mate-applets/geyes/src/geyes.c:#ifdef ENABLE_NLS
mate-applets/mateweather/src/mateweather-about.c:#ifdef ENABLE_NLS
mate-applets/multiload/src/main.c:#ifdef ENABLE_NLS
mate-applets/stickynotes/stickynotes_applet_callbacks.c:#ifdef ENABLE_NLS
mate-applets/trashapplet/src/trashapplet.c:#ifdef ENABLE_NLS
mate-control-center/capplets/common/capplet-util.c:#ifdef ENABLE_NLS
mate-control-center/shell/control-center.c:#ifdef ENABLE_NLS
mate-screensaver/src/mate-screensaver-command.c:#ifdef ENABLE_NLS
mate-screensaver/src/mate-screensaver-dialog.c:	#ifdef ENABLE_NLS
mate-screensaver/src/mate-screensaver-gl-helper.c:#ifdef ENABLE_NLS
mate-screensaver/src/mate-screensaver-preferences.c:#ifdef ENABLE_NLS
mate-screensaver/src/mate-screensaver.c:	#ifdef ENABLE_NLS
mate-screensaver/src/test-fade.c:#ifdef ENABLE_NLS
mate-screensaver/src/test-passwd.c:#ifdef ENABLE_NLS
mate-screensaver/src/test-watcher.c:#ifdef ENABLE_NLS
mate-screensaver/src/test-window.c:#ifdef ENABLE_NLS
mate-utils/baobab/src/callbacks.c:#ifdef ENABLE_NLS
mate-utils/logview/src/logview-window.c:#ifdef ENABLE_NLS
mate-utils/mate-dictionary/src/gdict-about.c:#ifdef ENABLE_NLS
```
A package without NLS doesn't include the translations (po files, localized manuals, entries in desktop files...), and it overrides or removes the required operations for retrieving the translations such as _, N_, C_, NC, g_dngettext... i.e. it disables the localization and the internationalization.

Most users don't use this option, however it's useful on critical systems or with few resources.

**Comment by raveit65** [comment]
Ok, but there is a file conflict.

**Comment by rbuj** [comment]
@raveit65 the merge conflict has been fixed

**Review by raveit65 — COMMENTED** [review]
LGTM

**Pull request merged**
