### PR TITLE
avoid deprecated gdk_screen_get_width/height and gdk_screen_width/height

### PR DESCRIPTION
**Pull request by sc0w**
avoid deprecated:

- gdk_screen_get_width/height

- gdk_screen_width/height

### CODE REVIEW

**Comment by raveit65** [comment]
@flexiondotorg @XRevan86 @clefebvre @monsta 
Guys, please help out with reviewing.
We have tons of open reviews in projects.....

**Comment by raveit65** [comment]
Building is fine and generates no new warnings, i am just testing runtime behaviour....

**Comment by sc0w** [comment]
I added the commit: `avoid deprecated gdk_screen_width/height`

@lukefromdc @raveit65 please test again

**Comment by lukefromdc** [comment]
Retest worked fine, checked the editable labels from theming and use problems and found none. Test is with GTK 3.22.18 over Debian Unstable

**Comment by raveit65** [comment]
New commit doesn't introduce any new build warnings or problems with caja-icon-container and editable lables in caja windows or desktop windows.

**Comment by lukefromdc** [comment]
Works fine here with the new changes applied. GTK 3.22.18 over Debian Unstable. This seems good to go.  Tested with a rebase over current master, as it would be applied

**Comment by lukefromdc** [comment]
Rebased and merged with
https://github.com/mate-desktop/caja/commit/17b3c0ca924ffcd4bd06fded98227eba626d4f0b
and
https://github.com/mate-desktop/caja/pull/824/commits/fdd1b0ce1e774200d4700a1af26d6d0ae1b065e7

**Comment by raveit65** [comment]
Sadly , this PR caused a serious regression.
I could track down this to https://github.com/mate-desktop/caja/commit/17b3c0ca924ffcd4bd06fded98227eba626d4f0b
**avoid deprecated gdk_screen_get_width/height**
Scaling the desktop wallpaper dosn't work any more if you choose a higher monitor resolution.
My normal desktop with 1920x1200:
caja-desktop1920x1200-normal
changing resolution to 1680x1050 (or any other):
caja-desktop-1680x1050
Now back to normal resolution:
caja-desktop-1920-1200-broken
Caja is build from master with **avoid deprecated gdk_screen_get_width/height** culprit commit as latest commit.
I disabled the other commit from this PR at the moment , **avoid deprecated gdk_screen_width/height**
Sadly, i can't reopen the PR here as the branch is deleted.
I suggest not to merge any other open PR before this is fixed.
And i hope that m-s-d or mate-desktop isn't involved.
Both other packages i built here from master + all GDK_SCREEN PRs, but it seems that only caja causes this regression.
@sc0w @lukefromdc ^^^^^

**Comment by raveit65** [comment]
Ok, it seems to be possible to enable ** avoid deprecated gdk_screen_width/height** and latest open GdkSreen related PR in a build, and the issue doesn't exists.
So, only **avoid deprecated gdk_screen_width/height** is the culprit.
Maybe it is only related to changes in caja-desktop.c ?

**Comment by sc0w** [comment]
I can confirm the issue, I will investigate it

**Comment by sc0w** [comment]
ok, the problem is here, in this function:

https://github.com/mate-desktop/caja/pull/824/commits/3f7ae0096392bc55a39b7c0e02a1cf770b4c1b87#diff-c1d7258bca7abbfd5edbaa1ae09875a3R308

**Comment by lukefromdc** [comment]
There is the option of reverting this if needed

**Comment by lukefromdc** [comment]
I normally use Zoom and cannot duplicate this scaling issue, if I use scale I get images that don't fit anyway. Will compare behavior with and without this PR though

**Comment by lukefromdc** [comment]
Issue shows up if I use "stretch," retesting

**Comment by raveit65** [comment]
I use always the default which is 'zoom'. An my screenshot was with 'zoom' and those image has a size of 5390x3584 pixel.

**Comment by raveit65** [comment]
Btw. If i disable 'show-desktop-icons' the issue isn't there. 
So, mate-settings-daemon seems not affected.

**Comment by lukefromdc** [comment]
Zoom worked differently for me, possibly because my desktop image size is  a match for my normal screen resolution. Stretch showed the issue so I was able to test anyway

**Pull request closed without merging**
