### PR TITLE
Fix cursor on single-click navigation mode.

### PR DESCRIPTION
**Pull request by torto9**
On this mode, after opening a folder, the hand cursor was used until the user moved the cursor over a file or folder.
Based on Nautilus.

### CODE REVIEW

**Comment by lukefromdc** [comment]
I was able to verify the described issue, and that this fix works. Waiting for input by others on the team before merging

**Comment by monsta** [comment]
I confirm the issue and the fix, but... it seems like the issue is reversed now. :smile:
Now the cursor always becomes a pointer after opening some folder - even if there's another subfolder inside right under the cursor. You need to move it a bit (still staying over the subfolder) so it will change into hand.

**Comment by monsta** [comment]
Upstream commit for reference:
https://git.gnome.org/browse/nautilus/commit/?id=2644c6ef4e7839e976d4861d6c86e16e34d46a13

**Comment by raveit65** [comment]
Ok, i see the same new issue with this PR.
Well, it is very minor but i don't see that with nautilus-3.20.x
Anyway, we can merge it before we lost years to find the fix for the fix, if all agree.

**Comment by lukefromdc** [comment]
What GTK version did you test with?

I just tested this in Nautilus, the reversed issue does not exist there with Nautlus and GTK 3.22. Also in Caja the pointer stayed a hand on my system if opening a folder put the cursor on another folder inside. Using GTK 3.22.5 plus recent commits to suppress some warnings.

**Comment by lukefromdc** [comment]
I'm OK with merging as-is if others are

**Comment by raveit65** [comment]
i just tested it with f24 and gtk+-3.20.

**Comment by monsta** [comment]
I have GTK+ 3.18.9 on this machine and a VM with 3.22.5 (Debian Testing), both have the new issue. It's actually reproducible not only with subfolders, but with files inside as well.

Ok, the new issue is easier to get rid of (just a bit of mouse moving), so I'm fine with merging.
I suggest adding the upstream commit link to the commit message, just in case.

**Comment by torto9** [comment]
I hadn't noticed the new problem...
After testing old Nautilus versions, I found that the issue was fixed by commit [https://git.gnome.org/browse/nautilus/commit/?id=d486af277f491ff5cfcfa254ebce618cd41a3edb](url)
To be honest, I have no idea why that fixes it... :)

**Comment by lukefromdc** [comment]
Merged with
https://github.com/mate-desktop/caja/commit/f604ba59b9a1e45c1fc45c0e94869e416f5a94b0
and the GNOME/nautilus commit added to the extended description. I will now try out that second GNOME commit. We may need it anyway, because MATE can be used (or should be usable) with a touchscreen the same way people put Windows 8/10 back in desktop mode but still use their touchscreens.

**Comment by torto9** [comment]
Thanks!

**Comment by lukefromdc** [comment]
I was able to duplicate the hand cursor not holding in when opening a folder brought the cursor over a new folder or file, turns out I was still double-clicking most of the time, turning the cursor back to an arrow. That allowed me to apply and test https://git.gnome.org/browse/nautilus/commit/?id=d486af277f491ff5cfcfa254ebce618cd41a3edb and it worked, so committed it to Caja as
https://github.com/mate-desktop/caja/commit/dbce9dbdf16b7d8afc8e0c1b6166b26221e1466f

**Comment by raveit65** [comment]
Yeap, that fixes the second issue.
Thanks guys.

**Comment by monsta** [comment]
Good, I confirm it's fixed now. Thanks :smile:

**Pull request closed without merging**
