### PR TITLE
sidebar popup menu: show "media-eject" icon

### PR DESCRIPTION
**Pull request by sc0w**

### CODE REVIEW

**Comment by monsta** [comment]
Couldn't figure out why I don't see it... then I realized I need to insert USB flash drive to get "Eject" menu item. My HDD only has "Unmount" item which doesn't have the icon. Should we add it there too?

**Comment by sc0w** [comment]
@monsta 

> Couldn't figure out why I don't see it... then I realized I need to insert USB flash drive to get "Eject" menu item.

I have tested the icon with one cd

> My second internal HDD (SATA) only has "Unmount" item which doesn't have the icon. Should we add it there too?

In my opinion, yes, I think it is a good idea, and the icon is understandable there

I can't see the "unmount" item, because I don't have a second internal hdd

**Comment by raveit65** [comment]
I don't see that icon if i plug in an external usb-disk-drive.
Where is that mysterious menu?
Picture please?

**Comment by raveit65** [comment]
Ok, got it.
If i plugin an usb-stick i see the icon in menu.
Still wondering why caja makes an different between an usb-stick and an external usb-disk-drive?

**Comment by monsta** [comment]
IIRC it's decided at gvfs level (I don't remember the details).

**Comment by sc0w** [comment]
@monsta 

> My second internal HDD (SATA) only has "Unmount" item which doesn't have the icon. Should we add it there too?

done in https://github.com/mate-desktop/caja/pull/977

**Pull request merged**
