### PR TITLE
Allow independent showing/hiding of backup files

### PR DESCRIPTION
**Pull request by Sargastic**
Caja can hide/show 'hidden or backup' files to the user. This is great, but it should be possible to show hidden or backup files independently. 

Existing functionnality has been split :

- The existing 'show hidden' functions have been altered to process/ignore only hidden files.
- A similar (copied/pasted/few edit) function group has been added to process/ignore backup files.

### CODE REVIEW

**Comment by lukefromdc** [comment]
How should this be tested?

**Comment by Sargastic** [comment]
I'm working on it

**Comment by Sargastic** [comment]
It's almost done, but I'll use it a few days at least before pushing it here.
BTW (clueless noob here), how could I update this PR since the patches will hit another branch ???

**Comment by lukefromdc** [comment]
Not sure, probably best just to open a new one, refer to it here, and close this one.

**Comment by Sargastic** [comment]
Closing PR (old branch). See PR https://github.com/mate-desktop/caja/pull/1044

**Pull request closed without merging**
