### PR TITLE
Changing the resolution will cause the desktop icons to not be adaptively arranged

### PR DESCRIPTION
**Pull request by nanxiongchao**
After changing the screen desktop resolution, the icon
can not be completely display and automatic arrangement

Get the actual screen height, determine whether the screen
"smaller", and only this situation rearrange the icon
Add the "screen size change" event and call the
rearranged icon function

Test Methods:
Create vertical two-row desktop icons close to the upper
and lower boundaries of the screen, increase and decrease
the resolution, observe whether all the icons are displayed properly

### CODE REVIEW

**Comment by nanxiongchao** [comment]
I  tested on fedora25

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/caja/pull/731 involved a lot of changes to drawing the desktop's background and is simply awaiting more testing before merge. I created a test copy of my local git repo and first merged dev-bg-fix, then this PR and it all merged clean. I then built it and it all ran fine with no obvious issues, though I was unable to test icon rearrangement as I have an extremely crowded desktop right now and did not want to mess with resolutions and move all my icons.

**Comment by nanxiongchao** [comment]
@lukefromdc Thanks, can not test now? Is the lack of test conditions?
In addition, for #731 , whether there is priority or have any impact on each other, but I hope this PR can be tested in time to determine if it can be merged rather than wait for it.

I have tested on fedora25,looks well

**Comment by raveit65** [comment]
It builds fine on top of fix-bg branch , but i do see what is the different with the arrangement of the desktop icons if i change resolutions?
Btw. if you have a f25 with origin 1.16 you cant test bg changes for 1.16 branch with my corps repo.
https://copr.fedorainfracloud.org/coprs/raveit65/Mate-Compiz-Fix/
Which fixes compiz in fedora.

**Comment by raveit65** [comment]
Ok, i see a different. W/o your PR and changing resolution from 1920x1200 to 1440x900 and back
i see always 2 columns, but i miss some icons with lower resolution.
With you PR is see 2 colums and missing icons too with lower resolution, but after switching back to higher resolution i have 3 columns.
But i don't understand what is better now?

**Comment by lukefromdc** [comment]
What I am not willing to do is deal with having to rearrange my very crowded desktop from scratch. All my testing is done on my actual production machine, with a backup system partition available if things go bad.

**Comment by lukefromdc** [comment]
If you want to try merging this PR first, make a copy of your local git repo, merge this locally, then merge https://github.com/mate-desktop/caja/pull/731 and build. I would imagine it would work fine, since there were no conflicts the other way.

**Comment by nanxiongchao** [comment]
@raveit65 Your test results are inconsistent with mine, in order to ensure reliable test results, my test is to create a new user to ensure a clean test environment to avoid other effects, you do so? Maybe it can be tested again.
In addition, maybe I can finish the test you mentioned in my spare time because I have to guarantee my work at work time.

**Comment by nanxiongchao** [comment]
@lukefromdc This test process is only related to the rearrangement of desktop icons, will not cause other effects on the system.
Creating a new user for testing will create a completely independent desktop that will not affect the desktop you are using.
I consider the next test #731

**Comment by raveit65** [comment]
> Your test results are inconsistent with mine, in order to ensure reliable test results, my test is to create a new user to ensure a clean test environment to avoid other effects, you do so? Maybe it can be tested again.
In addition, maybe I can finish the test you mentioned in my spare time because I have to guarantee my work at work time.

I really have a problem to understand what the PR does?
And my results was the only different i saw.
So maybe you can add some screenshots (with or w/o your PR) for better understanding.

**Comment by nanxiongchao** [comment]
For the last commit test results did not show the expected results I found the reason that there are three lines of code added not put in the right place.
I have fixed, please see commit 74c89cb.
commit 387038a and 6c580d2 are not being used, there is another question to ask, how do I delete these two commits，can they be deleted? these two commits are misuse.

**Comment by raveit65** [comment]
You can use 'git rebase -i **last-commit-before-PR**'
i= interactive
Beside from that using gdk_screen_get_height is deprecated with gtk+-3.22 (f25)
https://developer.gnome.org/gdk3/stable/GdkScreen.html#gdk-screen-get-height
You should see the build warnings about.
Any chance for using **new** code which isn't deprecated?

**Comment by raveit65** [comment]
First using a fresh account doesn't make any different for me.
Now, switching to a lower resolution will always sort the icons and i see all icons, which is important. 👍

But switching back to higher normal resolution will not sort the icons like it was before.
Sometimes they are sorted again and sometimes not, and sometimes i saw overlapped icons.
In any case resorting the icons alphabetic from right click menu will give another result.

```
caja-icon-container.c: In function 'lay_down_icons_vertical_desktop':
caja-icon-container.c:2114:5: warning: 'gdk_screen_get_height' is deprecated [-Wdeprecated-declarations]
     screen_height = gdk_screen_get_height (gtk_widget_get_screen(GTK_WIDGET(container)));
     ^~~~~~~~~~~~~
In file included from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:31:0,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from ../eel/eel-canvas.h:40,
                 from caja-icon-container.h:29,
                 from caja-icon-container.c:30:
/usr/include/gtk-3.0/gdk/gdkscreen.h:60:14: note: declared here
 gint         gdk_screen_get_height            (GdkScreen   *screen);
              ^~~~~~~~~~~~~~~~~~~~~
```
But deprecated gdk_screen_.......is used everywhere in code, so it seems to be impossible to fix that only at one place.

Any ways, much better than before.
But i want to know an opinnion from a third reviewer.
@monsta thoughts ?
And i don't think that we merge that before background handling changes are done.

**Comment by nanxiongchao** [comment]
@raveit65 Can you help me find a more appropriate function to solve this problem? I have a new commit e508d16, although the function can be achieved, but the implementation process is more cumbersome, I have no better way so I will look forward to better optimization through other people.

**Comment by raveit65** [comment]
Hmm, it look like it was better w/o latest commit.
@XRevan86 
@monsta 
@lukefromdc 
any suggestions?

**Comment by XRevan86** [comment]
I've noticed that "size_changed" of GdkScreen fires up before even the RootWindow gets resized – too early.
So ```gdk_screen_get_{width/height}``` should be fought :-).

**Comment by lukefromdc** [comment]
This created a nasty problem when I tested it.: If the user has manually arranged the icons, this arrangement is lost if the desktop resolution is changed. Some games can do this, and people really aren't going to want to lose their icon arrangement even after the screen returns to its previous resolution. For my purposes that is completely unacceptable, and was exactly what I feared. Lots of work seting them back where they were.

**Comment by lukefromdc** [comment]
Confirmed: Caja without this commit does not trash the user's ordering of icons if the desktop resolution is changed, then changed back. Previous layouts need to be saved, with only the spacing (not the ordering) being adaptively changed.

**Comment by sc0w** [comment]
I don't know how to reproduce the issue, someone can upload a video?

At this time some gdk_screen deprecations were solved ( https://github.com/mate-desktop/caja/commit/93a5e46e96a251b7574859bc1cd211fdbde01c3d https://github.com/mate-desktop/caja/commit/6c51a333e80df22587df4d9e0e2789fd1289d728 https://github.com/mate-desktop/caja/commit/42c8d2c3373c25d6e321be6950997c0d7ce44279 https://github.com/mate-desktop/caja/commit/17b3c0ca924ffcd4bd06fded98227eba626d4f0b )

The issue exists after that?

**Comment by raveit65** [comment]
> I don't know how to reproduce the issue, someone can upload a video?

Making a video doesn't work here with recordmydesktop if i switch monitor resolutions.
An yes, i can reproduce it with master and all PRs.
If you choose an lower resolution for your monitor than some icons can be out of the screen.
See my 2 screenshot at https://github.com/mate-desktop/caja/pull/824#issuecomment-323568583
Here some icons are under the bottom panel after switching to a lower resolution.

**Comment by lukefromdc** [comment]
Reproducing the problem with this PR is simple: build and install, restart Caja. Arrange some desktop icons manually, then change the monitor resolution. As intended the icons get reset. 

Now change resolution back to where you originally had it: your hand-set icon positions are lost, icons are in default layout. In other words, changing monitor resolution, then changing it back, resets the icon positions to default and does not save the original layout.

Adaptive rearangement on moving to a larger resolution is also a problem and should be removed from this entirely if possible. Here's one major use case example:  firing up a second monitor should not reset all the icons on the first monitor back to default position.

In my judgement, user-set icons should never be rearranged without either an explicit command from the user or a scaling to a desktop size that does not accomodate them. One fix might be simply to have a popup dialog ask users if they want to rearrange the icons or not.

**Comment by sc0w** [comment]
ah ok, now I understand the issue and I can reproduce it

**Comment by raveit65** [comment]
No activity since more than 2 years, closing.

**Pull request closed without merging**
