### PR TITLE
caja-bookmark.c: Fix icons in bookmarks

### PR DESCRIPTION
**Pull request by sc0w**
Fixes https://github.com/mate-desktop/caja/pull/962#issuecomment-389114129

### CODE REVIEW

**Comment by monsta** [comment]
Hmm... for some reason, I can't reproduce the issue in Ubuntu MATE 18.04 which has Caja 1.20.2 + patches from https://github.com/mate-desktop/caja/pull/974, https://github.com/mate-desktop/caja/pull/978, https://github.com/mate-desktop/caja/pull/979, https://github.com/mate-desktop/caja/pull/981. The icons are in place...

**Comment by monsta** [comment]
I saw your comment about it, but we also have that commit picked to 1.20: https://github.com/mate-desktop/caja/commit/dade92d4f1edb6f47933e77229801971cb458ef1

**Comment by sc0w** [comment]
@monsta aha, I know why, probably because the 1.20 branch doesn't have the commit https://github.com/mate-desktop/caja/commit/e9bd5cbddec49b02e7ff451d4c721de7946baacc (caja-bookmark: avoid deprecated GtkImageMenuItem)

**Comment by monsta** [comment]
Ah, I see, `bookmark_image_menu_item_new_from_pixbuf` only appeared there.

**Comment by raveit65** [comment]
Looks like this commit generates a build warning?
```
caja-bookmark.c: In function 'create_image_cairo_for_bookmark':
caja-bookmark.c:592:16: warning: unused variable 'widget' [-Wunused-variable]
     GtkWidget *widget;
                ^~~~~~
```
Should be easy to fix ;)

**Comment by raveit65** [comment]
Btw. icons are back with this commit.

**Comment by sc0w** [comment]
@raveit65 done in https://github.com/mate-desktop/caja/commit/cfc9b47cf1bfb49bec5eaae30af4c7726496f81f

**Pull request merged**
